<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/src/allocation.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**<br>
&nbsp;*&nbsp;@file<br>
&nbsp;*&nbsp;@brief&nbsp;Unified&nbsp;packet&nbsp;memory&nbsp;management&nbsp;with&nbsp;runtime&nbsp;allocator&nbsp;selection<br>
&nbsp;*<br>
&nbsp;*&nbsp;By&nbsp;default&nbsp;uses&nbsp;malloc.&nbsp;Call&nbsp;crow::engage_packet_pool()&nbsp;to&nbsp;switch&nbsp;to&nbsp;pool&nbsp;mode.<br>
&nbsp;*&nbsp;Pool&nbsp;mode&nbsp;is&nbsp;useful&nbsp;for&nbsp;embedded&nbsp;systems&nbsp;without&nbsp;dynamic&nbsp;memory.<br>
&nbsp;*/<br>
<br>
#include&nbsp;&lt;crow/packet.h&gt;<br>
#include&nbsp;&lt;igris/container/pool.h&gt;<br>
#include&nbsp;&lt;igris/sync/syslock.h&gt;<br>
<br>
#include&nbsp;&lt;cassert&gt;<br>
#include&nbsp;&lt;cstdlib&gt;<br>
#include&nbsp;&lt;cstring&gt;<br>
<br>
static&nbsp;igris::pool&nbsp;_crow_packet_pool;<br>
static&nbsp;bool&nbsp;_use_pool&nbsp;=&nbsp;false;<br>
static&nbsp;int&nbsp;_crow_allocated_count&nbsp;=&nbsp;0;<br>
<br>
igris::pool&nbsp;*crow::get_package_pool()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&amp;_crow_packet_pool;<br>
}<br>
<br>
void&nbsp;crow::engage_packet_pool(void&nbsp;*zone,&nbsp;size_t&nbsp;zonesize,&nbsp;size_t&nbsp;elsize)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_crow_packet_pool.init(zone,&nbsp;zonesize,&nbsp;elsize);<br>
&nbsp;&nbsp;&nbsp;&nbsp;_use_pool&nbsp;=&nbsp;true;<br>
}<br>
<br>
void&nbsp;crow::disengage_packet_pool()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_use_pool&nbsp;=&nbsp;false;<br>
}<br>
<br>
bool&nbsp;crow::is_pool_engaged()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_use_pool;<br>
}<br>
<br>
bool&nbsp;crow::has_allocated()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_crow_allocated_count&nbsp;&gt;&nbsp;0;<br>
}<br>
<br>
int&nbsp;crow::allocated_count()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_crow_allocated_count;<br>
}<br>
<br>
void&nbsp;crow::reset_allocated_count()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_crow_allocated_count&nbsp;=&nbsp;0;<br>
}<br>
<br>
//&nbsp;Pool-based&nbsp;allocation<br>
static&nbsp;crow::packet&nbsp;*allocate_from_pool(size_t&nbsp;required_size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(_crow_packet_pool.element_size()&nbsp;&gt;=&nbsp;required_size&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Pool&nbsp;element&nbsp;size&nbsp;too&nbsp;small&nbsp;for&nbsp;requested&nbsp;packet&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;*mem&nbsp;=&nbsp;_crow_packet_pool.get();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(mem)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_crow_allocated_count++;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memset(mem,&nbsp;0,&nbsp;_crow_packet_pool.element_size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(crow::packet&nbsp;*)mem;<br>
}<br>
<br>
static&nbsp;void&nbsp;deallocate_to_pool(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;_crow_allocated_count--;<br>
&nbsp;&nbsp;&nbsp;&nbsp;_crow_packet_pool.put(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(_crow_allocated_count&nbsp;&gt;=&nbsp;0);<br>
}<br>
<br>
//&nbsp;Malloc-based&nbsp;allocation<br>
static&nbsp;crow::packet&nbsp;*allocate_with_malloc(size_t&nbsp;size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;_crow_allocated_count++;<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(_crow_allocated_count&nbsp;&lt;&nbsp;64);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;*buffer&nbsp;=&nbsp;(uint8_t&nbsp;*)malloc(size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(buffer)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memset(buffer,&nbsp;0,&nbsp;size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(crow::packet&nbsp;*)buffer;<br>
}<br>
<br>
static&nbsp;void&nbsp;deallocate_with_free(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;_crow_allocated_count--;<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;free((void&nbsp;*)pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(_crow_allocated_count&nbsp;&gt;=&nbsp;0);<br>
}<br>
<br>
void&nbsp;crow::deallocate_packet(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_use_pool)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;deallocate_to_pool(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;deallocate_with_free(pack);<br>
}<br>
<br>
crow::packet&nbsp;*crow::allocate_packet_header_v1(int&nbsp;adlen)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;required&nbsp;=&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v1)&nbsp;+&nbsp;adlen;<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;*buffer;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_use_pool)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buffer&nbsp;=&nbsp;(uint8_t&nbsp;*)allocate_from_pool(required);<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buffer&nbsp;=&nbsp;(uint8_t&nbsp;*)allocate_with_malloc(required);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(buffer&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;new&nbsp;(buffer)&nbsp;crow::packet(crow::deallocate_packet);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;attach_header((crow::header_v1&nbsp;*)(buffer&nbsp;+&nbsp;sizeof(crow::packet)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;attach_addrdata(buffer&nbsp;+&nbsp;sizeof(crow::packet)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::header_v1));<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;pack;<br>
}<br>
<br>
crow::packet&nbsp;*crow::allocate_packet_header_v0(int&nbsp;adlen)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;required&nbsp;=&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v0)&nbsp;+&nbsp;adlen;<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;*buffer;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_use_pool)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buffer&nbsp;=&nbsp;(uint8_t&nbsp;*)allocate_from_pool(required);<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buffer&nbsp;=&nbsp;(uint8_t&nbsp;*)allocate_with_malloc(required);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(buffer&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;new&nbsp;(buffer)&nbsp;crow::packet(crow::deallocate_packet);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;attach_header((crow::header_v0&nbsp;*)(buffer&nbsp;+&nbsp;sizeof(crow::packet)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;attach_addrdata(buffer&nbsp;+&nbsp;sizeof(crow::packet)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::header_v0));<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;pack;<br>
}<br>
<br>
crow::packet&nbsp;*crow::allocate_packet_header_v1(int&nbsp;alen,&nbsp;int&nbsp;dlen)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;allocate_packet_header_v1(alen&nbsp;+&nbsp;dlen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_addrsize(alen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_datasize(dlen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;pack;<br>
}<br>
<br>
crow::packet&nbsp;*crow::allocate_packet_header_v0(int&nbsp;alen,&nbsp;int&nbsp;dlen)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;allocate_packet_header_v0(alen&nbsp;+&nbsp;dlen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_addrsize(alen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_datasize(dlen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;pack;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
