<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/src/hostaddr_view.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/hostaddr.h&gt;<br>
#include&nbsp;&lt;crow/hostaddr_view.h&gt;<br>
#include&nbsp;&lt;cstring&gt;<br>
<br>
crow::hostaddr_view::hostaddr_view(const&nbsp;hostaddr&nbsp;&amp;h)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;addr(h.data()),&nbsp;alen(h.size())<br>
{<br>
}<br>
<br>
crow::hostaddr_view::hostaddr_view(const&nbsp;nos::buffer&nbsp;&amp;v)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;addr((uint8_t&nbsp;*)v.data()),&nbsp;alen(v.size())<br>
{<br>
}<br>
<br>
crow::hostaddr_view::hostaddr_view(const&nbsp;uint8_t&nbsp;*addr,&nbsp;size_t&nbsp;alen)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;addr(addr),&nbsp;alen(alen)<br>
{<br>
}<br>
<br>
crow::hostaddr_view::hostaddr_view(const&nbsp;char&nbsp;*addr,&nbsp;size_t&nbsp;alen)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;addr((uint8_t&nbsp;*)addr),&nbsp;alen(alen)<br>
{<br>
}<br>
<br>
crow::hostaddr_view::hostaddr_view(const&nbsp;void&nbsp;*addr,&nbsp;size_t&nbsp;alen)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;addr((uint8_t&nbsp;*)addr),&nbsp;alen(alen)<br>
{<br>
}<br>
<br>
const&nbsp;uint8_t&nbsp;*crow::hostaddr_view::data()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;addr;<br>
}<br>
<br>
size_t&nbsp;crow::hostaddr_view::size()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;alen;<br>
}<br>
<br>
bool&nbsp;crow::hostaddr_view::operator==(nos::buffer&nbsp;buf)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;alen&nbsp;==&nbsp;buf.size()&nbsp;&amp;&amp;&nbsp;memcmp(addr,&nbsp;buf.data(),&nbsp;alen)&nbsp;==&nbsp;0;<br>
}<br>
<br>
bool&nbsp;crow::hostaddr_view::operator==(const&nbsp;hostaddr_view&nbsp;&amp;buf)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;alen&nbsp;==&nbsp;buf.size()&nbsp;&amp;&amp;&nbsp;memcmp(addr,&nbsp;buf.data(),&nbsp;alen)&nbsp;==&nbsp;0;<br>
}<br>
<br>
const&nbsp;uint8_t&nbsp;*crow::hostaddr_view::begin()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;data();<br>
}<br>
const&nbsp;uint8_t&nbsp;*crow::hostaddr_view::end()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;data()&nbsp;+&nbsp;size();<br>
}<br>
<br>
std::string&nbsp;crow::hostaddr_view::to_string()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;res;<br>
&nbsp;&nbsp;&nbsp;&nbsp;res.resize(size()&nbsp;*&nbsp;3&nbsp;-&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(size_t&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;size();&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sprintf(&amp;res[i&nbsp;*&nbsp;3],&nbsp;&quot;%02x:&quot;,&nbsp;addr[i]);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;res.pop_back();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;res;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
