<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/src/packet.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**<br>
@file&nbsp;packet.cpp<br>
*/<br>
<br>
#include&nbsp;&lt;crow/gateway.h&gt;<br>
#include&nbsp;&lt;crow/packet.h&gt;<br>
#include&nbsp;&lt;igris/compiler.h&gt;<br>
#include&nbsp;&lt;igris/sync/syslock.h&gt;<br>
#include&nbsp;&lt;stdbool.h&gt;<br>
#include&nbsp;&lt;stdio.h&gt;<br>
#include&nbsp;&lt;string.h&gt;<br>
<br>
int&nbsp;crow_allocated_count&nbsp;=&nbsp;0;<br>
<br>
void&nbsp;crow::packet_initialization(crow::packet&nbsp;*pack,&nbsp;crow::gateway&nbsp;*ingate)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_init(&amp;pack-&gt;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_init(&amp;pack-&gt;ulnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;ingate&nbsp;=&nbsp;ingate;<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;_ackcount&nbsp;=&nbsp;5;<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.flags&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;refs&nbsp;=&nbsp;0;<br>
}<br>
<br>
crow::packet&nbsp;*<br>
crow::create_packet(crow::gateway&nbsp;*ingate,&nbsp;uint8_t&nbsp;addrsize,&nbsp;size_t&nbsp;datasize)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::allocate_packet&lt;crow::header_v1&gt;(addrsize,&nbsp;datasize);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(200);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_stage(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet_initialization(pack,&nbsp;ingate);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;pack;<br>
}<br>
<br>
//&nbsp;Номер&nbsp;врат&nbsp;-&nbsp;1&nbsp;байт,&nbsp;так&nbsp;что&nbsp;просто&nbsp;меняем&nbsp;одно&nbsp;число&nbsp;на<br>
//&nbsp;номер&nbsp;врат,&nbsp;через&nbsp;которые&nbsp;проходит&nbsp;пакет.<br>
void&nbsp;crow::packet::revert_gate(uint8_t&nbsp;gateindex)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;*stageptr()&nbsp;=&nbsp;gateindex;<br>
&nbsp;&nbsp;&nbsp;&nbsp;increment_stage(1);<br>
}<br>
<br>
//&nbsp;Перезаписываем&nbsp;информацию&nbsp;на&nbsp;ту&nbsp;информацию,&nbsp;какую&nbsp;предоставили&nbsp;врата<br>
//&nbsp;в&nbsp;качестве&nbsp;обратного&nbsp;адреса.<br>
void&nbsp;crow::packet::revert(nos::buffer&nbsp;*vec,&nbsp;size_t&nbsp;veclen)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::buffer&nbsp;*it&nbsp;=&nbsp;vec&nbsp;+&nbsp;veclen&nbsp;-&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::buffer&nbsp;*eit&nbsp;=&nbsp;vec&nbsp;-&nbsp;1;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;sz&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;*tgt&nbsp;=&nbsp;stageptr();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;--it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sz&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;*ptr&nbsp;=&nbsp;(char&nbsp;*)it-&gt;data()&nbsp;+&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;*eptr&nbsp;=&nbsp;(char&nbsp;*)it-&gt;data();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(ptr&nbsp;!=&nbsp;eptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*tgt++&nbsp;=&nbsp;*--ptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;increment_stage(sz);<br>
}<br>
<br>
bool&nbsp;crow::has_allocated()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;!!crow_allocated_count;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
