<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/src/threads-posix.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;chrono&gt;<br>
#include&nbsp;&lt;crow/asyncio.h&gt;<br>
#include&nbsp;&lt;crow/tower.h&gt;<br>
#include&nbsp;&lt;crow/tower_cls.h&gt;<br>
#include&nbsp;&lt;crow/warn.h&gt;<br>
#include&nbsp;&lt;igris/osutil/fd.h&gt;<br>
#include&nbsp;&lt;thread&gt;<br>
#include&nbsp;&lt;unistd.h&gt;<br>
<br>
using&nbsp;namespace&nbsp;std::chrono_literals;<br>
<br>
static&nbsp;bool&nbsp;cancel_token&nbsp;=&nbsp;false;<br>
static&nbsp;std::thread&nbsp;_thread;<br>
bool&nbsp;_spin_runned&nbsp;=&nbsp;false;<br>
bool&nbsp;_spin_runned_unbounded&nbsp;=&nbsp;false;<br>
<br>
namespace&nbsp;crow<br>
{<br>
<br>
//&nbsp;Tower-specific&nbsp;spin&nbsp;function<br>
void&nbsp;spin_with_select(Tower&nbsp;&amp;tower)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_spin_runned&nbsp;=&nbsp;true;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(cancel_token)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;do<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.onestep();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(cancel_token)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;while&nbsp;(tower.has_untravelled_now());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int64_t&nbsp;timeout&nbsp;=&nbsp;tower.get_minimal_timeout();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asyncio.step(timeout);<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;_spin_runned&nbsp;=&nbsp;false;<br>
}<br>
<br>
void&nbsp;spin(Tower&nbsp;&amp;tower)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;spin_with_select(tower);<br>
}<br>
<br>
int&nbsp;stop_spin(bool&nbsp;wait)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!_spin_runned)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;thread&nbsp;is&nbsp;not&nbsp;started&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;cancel_token&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;asyncio.cancel();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(wait)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_thread.join();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(...)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;_spin_runned_unbounded&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::this_thread::sleep_for(100ms);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
void&nbsp;spin_join()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_thread.join();<br>
}<br>
<br>
void&nbsp;join_spin()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_thread.join();<br>
}<br>
<br>
void&nbsp;set_spin_cancel_token()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;cancel_token&nbsp;=&nbsp;true;<br>
}<br>
<br>
//#if&nbsp;defined(CROW_REALTIME_THREADS)<br>
#include&nbsp;&lt;igris/osutil/realtime.h&gt;<br>
<br>
static&nbsp;Tower&nbsp;*_realtime_tower&nbsp;=&nbsp;nullptr;<br>
<br>
void&nbsp;spin_with_select_realtime_impl(int&nbsp;abort_on_fault)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;ret;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;((ret&nbsp;=&nbsp;this_thread_set_realtime_priority()))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::warn(&quot;Error&nbsp;on&nbsp;set_realtime_priority&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(abort_on_fault)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;abort();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;spin_with_select(*_realtime_tower);<br>
}<br>
<br>
int&nbsp;start_spin_with_select_realtime(Tower&nbsp;&amp;tower,&nbsp;int&nbsp;abort_on_fault)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_spin_runned)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;spin&nbsp;thread&nbsp;double&nbsp;start&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;_realtime_tower&nbsp;=&nbsp;&amp;tower;<br>
&nbsp;&nbsp;&nbsp;&nbsp;cancel_token&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;_spin_runned_unbounded&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;_spin_runned&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;_thread&nbsp;=&nbsp;std::thread(spin_with_select_realtime_impl,&nbsp;abort_on_fault);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
int&nbsp;start_spin_realtime(Tower&nbsp;&amp;tower,&nbsp;int&nbsp;abort_on_fault)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;start_spin_with_select_realtime(tower,&nbsp;abort_on_fault);<br>
}<br>
//#endif<br>
<br>
}&nbsp;//&nbsp;namespace&nbsp;crow<br>
<!-- END SCAT CODE -->
</body>
</html>
