<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/src/tower_thread_executor.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/tower_thread_executor.h&gt;<br>
#include&nbsp;&lt;crow/asyncio.h&gt;<br>
<br>
namespace&nbsp;crow<br>
{<br>
<br>
int&nbsp;TowerThreadExecutor::start()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_running.load())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;_cancel_token.store(false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;_running.store(true);<br>
&nbsp;&nbsp;&nbsp;&nbsp;_thread&nbsp;=&nbsp;std::thread(&amp;TowerThreadExecutor::thread_func,&nbsp;this);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
int&nbsp;TowerThreadExecutor::stop(bool&nbsp;wait)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!_running.load())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;_cancel_token.store(true);<br>
&nbsp;&nbsp;&nbsp;&nbsp;asyncio.cancel();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(wait)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;join();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
void&nbsp;TowerThreadExecutor::join()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_thread.joinable())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_thread.join();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;TowerThreadExecutor::thread_func()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(!_cancel_token.load())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;do<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_tower.onestep();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_cancel_token.load())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;while&nbsp;(_tower.has_untravelled_now());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_cancel_token.load())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int64_t&nbsp;timeout&nbsp;=&nbsp;_tower.get_minimal_timeout();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asyncio.step(timeout);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;_running.store(false);<br>
}<br>
<br>
}&nbsp;//&nbsp;namespace&nbsp;crow<br>
<!-- END SCAT CODE -->
</body>
</html>
