<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/src/tower.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**&nbsp;@file&nbsp;*/<br>
<br>
#include&nbsp;&lt;assert.h&gt;<br>
#include&nbsp;&lt;limits&gt;<br>
#include&nbsp;&lt;stdbool.h&gt;<br>
#include&nbsp;&lt;string.h&gt;<br>
<br>
#include&nbsp;&lt;igris/dprint.h&gt;<br>
#include&nbsp;&lt;igris/event/delegate.h&gt;<br>
#include&nbsp;&lt;igris/sync/syslock.h&gt;<br>
#include&nbsp;&lt;igris/time/systime.h&gt;<br>
<br>
#include&nbsp;&lt;crow/gateway.h&gt;<br>
#include&nbsp;&lt;crow/print.h&gt;<br>
#include&nbsp;&lt;crow/proto/node.h&gt;<br>
#include&nbsp;&lt;crow/pubsub/pubsub.h&gt;<br>
#include&nbsp;&lt;crow/tower.h&gt;<br>
#include&nbsp;&lt;crow/tower_cls.h&gt;<br>
#include&nbsp;&lt;crow/warn.h&gt;<br>
<br>
#include&nbsp;&lt;nos/print.h&gt;<br>
<br>
#ifdef&nbsp;CROW_USE_ASYNCIO<br>
#include&nbsp;&lt;crow/asyncio.h&gt;<br>
#endif<br>
<br>
//&nbsp;============================================================================<br>
//&nbsp;Tower&nbsp;class&nbsp;implementation<br>
//&nbsp;============================================================================<br>
<br>
crow::Tower::Tower()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Initialize&nbsp;TIME_WAIT&nbsp;hash&nbsp;table&nbsp;buckets<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(size_t&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;TIME_WAIT_HTABLE_SIZE;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_init(&amp;_time_wait_htable[i]);<br>
}<br>
<br>
crow::Tower::~Tower()&nbsp;=&nbsp;default;<br>
<br>
void&nbsp;crow::Tower::time_wait_init()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_time_wait_initialized)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(size_t&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;MAX_TIME_WAIT_ENTRIES;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_init(&amp;_time_wait_pool[i].lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_init(&amp;_time_wait_pool[i].hlnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_add(&amp;_time_wait_pool[i].lnk,&nbsp;&amp;_time_wait_free_list);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;_time_wait_initialized&nbsp;=&nbsp;true;<br>
}<br>
<br>
size_t&nbsp;crow::Tower::time_wait_hash(uint16_t&nbsp;seqid)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;seqid&nbsp;%&nbsp;TIME_WAIT_HTABLE_SIZE;<br>
}<br>
<br>
void&nbsp;crow::Tower::time_wait_cleanup_expired()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint64_t&nbsp;now&nbsp;=&nbsp;igris::millis();<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_head&nbsp;*it,&nbsp;*nxt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_safe(it,&nbsp;nxt,&nbsp;&amp;_time_wait_list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;time_wait_entry&nbsp;*entry&nbsp;=&nbsp;dlist_entry(it,&nbsp;time_wait_entry,&nbsp;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(now&nbsp;&gt;=&nbsp;entry-&gt;expire_time)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del(&amp;entry-&gt;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del(&amp;entry-&gt;hlnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_add(&amp;entry-&gt;lnk,&nbsp;&amp;_time_wait_free_list);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--_time_wait_count;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;List&nbsp;is&nbsp;ordered&nbsp;by&nbsp;expire&nbsp;time,&nbsp;so&nbsp;we&nbsp;can&nbsp;stop&nbsp;here<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
bool&nbsp;crow::Tower::time_wait_check(uint16_t&nbsp;seqid,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;uint8_t&nbsp;*addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;addrsize)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;time_wait_init();<br>
&nbsp;&nbsp;&nbsp;&nbsp;time_wait_cleanup_expired();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_head&nbsp;*bucket&nbsp;=&nbsp;&amp;_time_wait_htable[time_wait_hash(seqid)];<br>
&nbsp;&nbsp;&nbsp;&nbsp;time_wait_entry&nbsp;*entry;<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry(entry,&nbsp;bucket,&nbsp;hlnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(entry-&gt;seqid&nbsp;==&nbsp;seqid&nbsp;&amp;&amp;&nbsp;entry-&gt;addrsize&nbsp;==&nbsp;addrsize&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcmp(entry-&gt;addr,&nbsp;addr,&nbsp;addrsize)&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;true;&nbsp;//&nbsp;Found&nbsp;in&nbsp;TIME_WAIT&nbsp;-&nbsp;this&nbsp;is&nbsp;a&nbsp;duplicate<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;false;<br>
}<br>
<br>
void&nbsp;crow::Tower::time_wait_add(uint16_t&nbsp;seqid,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;uint8_t&nbsp;*addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;addrsize)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;time_wait_init();<br>
&nbsp;&nbsp;&nbsp;&nbsp;time_wait_cleanup_expired();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(addrsize&nbsp;&gt;&nbsp;sizeof(time_wait_entry::addr))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;&nbsp;//&nbsp;Address&nbsp;too&nbsp;long<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Get&nbsp;entry&nbsp;from&nbsp;free&nbsp;list&nbsp;or&nbsp;evict&nbsp;oldest<br>
&nbsp;&nbsp;&nbsp;&nbsp;time_wait_entry&nbsp;*entry;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!dlist_empty(&amp;_time_wait_free_list))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;entry&nbsp;=&nbsp;dlist_first_entry(&amp;_time_wait_free_list,&nbsp;time_wait_entry,&nbsp;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del(&amp;entry-&gt;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else&nbsp;if&nbsp;(!dlist_empty(&amp;_time_wait_list))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Evict&nbsp;oldest&nbsp;entry<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;entry&nbsp;=&nbsp;dlist_first_entry(&amp;_time_wait_list,&nbsp;time_wait_entry,&nbsp;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del(&amp;entry-&gt;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del(&amp;entry-&gt;hlnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--_time_wait_count;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;&nbsp;//&nbsp;No&nbsp;entries&nbsp;available&nbsp;(shouldn't&nbsp;happen)<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;entry-&gt;seqid&nbsp;=&nbsp;seqid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;entry-&gt;addrsize&nbsp;=&nbsp;addrsize;<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(entry-&gt;addr,&nbsp;addr,&nbsp;addrsize);<br>
&nbsp;&nbsp;&nbsp;&nbsp;entry-&gt;expire_time&nbsp;=&nbsp;igris::millis()&nbsp;+&nbsp;_time_wait_duration_ms;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Add&nbsp;to&nbsp;end&nbsp;of&nbsp;list&nbsp;(ordered&nbsp;by&nbsp;expire&nbsp;time)<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_add_tail(&amp;entry-&gt;lnk,&nbsp;&amp;_time_wait_list);<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Add&nbsp;to&nbsp;hash&nbsp;table<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_add(&amp;entry-&gt;hlnk,&nbsp;&amp;_time_wait_htable[time_wait_hash(seqid)]);<br>
&nbsp;&nbsp;&nbsp;&nbsp;++_time_wait_count;<br>
}<br>
<br>
void&nbsp;crow::Tower::utilize(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_del(&amp;pack-&gt;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_del(&amp;pack-&gt;ulnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;invalidate();<br>
}<br>
<br>
void&nbsp;crow::Tower::release(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;u.f.released_by_tower&nbsp;&amp;&amp;&nbsp;pack-&gt;refs&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.released_by_world&nbsp;=&nbsp;true;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow::Tower::tower_release(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_del_init(&amp;pack-&gt;lnk);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Remove&nbsp;from&nbsp;hash&nbsp;table&nbsp;if&nbsp;present&nbsp;(just&nbsp;disconnect&nbsp;the&nbsp;intrusive&nbsp;link)<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;We&nbsp;use&nbsp;dlist_del_init&nbsp;directly&nbsp;instead&nbsp;of&nbsp;_outters_htable.remove()<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;to&nbsp;avoid&nbsp;dependency&nbsp;on&nbsp;specific&nbsp;Tower&nbsp;instance&nbsp;-&nbsp;the&nbsp;link&nbsp;can&nbsp;safely<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;disconnect&nbsp;itself&nbsp;from&nbsp;any&nbsp;hash&nbsp;table&nbsp;bucket&nbsp;it&nbsp;belongs&nbsp;to.<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!dlist_empty(&amp;pack-&gt;hlnk))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del_init(&amp;pack-&gt;hlnk);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;u.f.released_by_world&nbsp;&amp;&amp;&nbsp;pack-&gt;refs&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.released_by_tower&nbsp;=&nbsp;true;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow::Tower::confirmed_utilize_from_outers(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*it;<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Use&nbsp;hash&nbsp;table&nbsp;for&nbsp;O(1)&nbsp;bucket&nbsp;lookup&nbsp;instead&nbsp;of&nbsp;O(n)&nbsp;list&nbsp;scan<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_head&nbsp;*bucket&nbsp;=&nbsp;_outters_htable.bucket(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry(it,&nbsp;bucket,&nbsp;hlnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it-&gt;seqid()&nbsp;==&nbsp;pack-&gt;seqid()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;addrsize()&nbsp;==&nbsp;it-&gt;addrsize()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;!memcmp(it-&gt;addrptr(),&nbsp;pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize()))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;OUTFLT:&nbsp;ACK&nbsp;received,&nbsp;removing&nbsp;seqid=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dprhex(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;&nbsp;from&nbsp;outters,&nbsp;out_count=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(_outters_count);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dln();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;it-&gt;u.f.confirmed&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_outters_htable.remove(&amp;it-&gt;hlnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_outters_count&nbsp;&gt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--_outters_count;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::node_protocol.delivered(it,&nbsp;*this);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower_release(it);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;OUTFLT:&nbsp;ACK&nbsp;for&nbsp;seqid=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dprhex(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;&nbsp;but&nbsp;NOT&nbsp;FOUND&nbsp;in&nbsp;outters!\n&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow::Tower::qos_release_from_incoming(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*it;<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Use&nbsp;hash&nbsp;table&nbsp;for&nbsp;O(1)&nbsp;bucket&nbsp;lookup&nbsp;instead&nbsp;of&nbsp;O(n)&nbsp;list&nbsp;scan<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_head&nbsp;*bucket&nbsp;=&nbsp;_incoming_htable.bucket(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry(it,&nbsp;bucket,&nbsp;ihlnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it-&gt;seqid()&nbsp;==&nbsp;pack-&gt;seqid()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;addrsize()&nbsp;==&nbsp;it-&gt;addrsize()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;!memcmp(it-&gt;addrptr(),&nbsp;pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize()))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;DUPFLT:&nbsp;ACK22&nbsp;removing&nbsp;seqid=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dprhex(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;&nbsp;from&nbsp;htable&nbsp;-&gt;&nbsp;TIME_WAIT,&nbsp;inc_count=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(_incoming_count);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dln();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Add&nbsp;to&nbsp;TIME_WAIT&nbsp;before&nbsp;removing&nbsp;from&nbsp;incoming<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;time_wait_add(it-&gt;seqid(),&nbsp;it-&gt;addrptr(),&nbsp;it-&gt;addrsize());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_incoming_htable.remove(&amp;it-&gt;ihlnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_incoming_count&nbsp;&gt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--_incoming_count;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower_release(it);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
static&nbsp;bool&nbsp;crow_time_comparator(crow::packet&nbsp;*a,&nbsp;crow::packet&nbsp;*b)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint64_t&nbsp;a_timer&nbsp;=&nbsp;a-&gt;last_request_time&nbsp;+&nbsp;a-&gt;ackquant();<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint64_t&nbsp;b_timer&nbsp;=&nbsp;b-&gt;last_request_time&nbsp;+&nbsp;b-&gt;ackquant();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;a_timer&nbsp;&lt;&nbsp;b_timer;<br>
}<br>
<br>
bool&nbsp;crow::Tower::add_to_incoming_list(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Check&nbsp;limit&nbsp;before&nbsp;adding<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_incoming_count&nbsp;&gt;=&nbsp;MAX_INCOMING)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;crow:&nbsp;incoming&nbsp;list&nbsp;full&nbsp;(&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(_incoming_count);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;/&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(MAX_INCOMING);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;),&nbsp;dropping&nbsp;seqid=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dprhex(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dln();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;last_request_time&nbsp;=&nbsp;igris::millis();<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_move_sorted(pack,&nbsp;&amp;_incoming,&nbsp;lnk,&nbsp;crow_time_comparator);<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Add&nbsp;to&nbsp;hash&nbsp;table&nbsp;for&nbsp;fast&nbsp;lookup&nbsp;by&nbsp;seqid<br>
&nbsp;&nbsp;&nbsp;&nbsp;_incoming_htable.put(pack,&nbsp;&amp;pack-&gt;ihlnk,&nbsp;pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;++_incoming_count;<br>
&nbsp;&nbsp;&nbsp;&nbsp;unsleep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;true;<br>
}<br>
<br>
bool&nbsp;crow::Tower::add_to_outters_list(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Check&nbsp;limit&nbsp;before&nbsp;adding&nbsp;(but&nbsp;allow&nbsp;retransmits&nbsp;-&nbsp;already&nbsp;in&nbsp;list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;is_retransmit&nbsp;=&nbsp;!dlist_empty(&amp;pack-&gt;hlnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_retransmit&nbsp;&amp;&amp;&nbsp;_outters_count&nbsp;&gt;=&nbsp;MAX_OUTTERS)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;crow:&nbsp;outters&nbsp;list&nbsp;full&nbsp;(&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(_outters_count);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;/&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(MAX_OUTTERS);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;),&nbsp;dropping&nbsp;seqid=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dprhex(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dln();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;last_request_time&nbsp;=&nbsp;igris::millis();<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_move_sorted(pack,&nbsp;&amp;_outters,&nbsp;lnk,&nbsp;crow_time_comparator);<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Add&nbsp;to&nbsp;hash&nbsp;table&nbsp;for&nbsp;fast&nbsp;lookup&nbsp;by&nbsp;seqid<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;First&nbsp;remove&nbsp;if&nbsp;already&nbsp;in&nbsp;table&nbsp;(for&nbsp;retransmits)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(is_retransmit)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_outters_htable.remove(&amp;pack-&gt;hlnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;++_outters_count;<br>
&nbsp;&nbsp;&nbsp;&nbsp;_outters_htable.put(pack,&nbsp;&amp;pack-&gt;hlnk,&nbsp;pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;unsleep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;true;<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::Tower::travel(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_add_tail(&amp;pack-&gt;lnk,&nbsp;&amp;_travelled);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;unsleep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;crow::packet_ptr(pack);<br>
}<br>
<br>
void&nbsp;crow::Tower::unsleep()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_unsleep_handler)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_unsleep_handler();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
#ifdef&nbsp;CROW_USE_ASYNCIO<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::asyncio.unsleep();<br>
#endif<br>
}<br>
<br>
void&nbsp;crow::Tower::incoming_handler(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(CROW_NODE_PROTOCOL&nbsp;==&nbsp;pack-&gt;type())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_incoming_handler&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::node_protocol.incoming(pack,&nbsp;*this);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_incoming_handler&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
#ifdef&nbsp;CROW_PUBSUB_PROTOCOL_SUPPORTED<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(CROW_PUBSUB_PROTOCOL&nbsp;==&nbsp;pack-&gt;type())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_incoming_handler&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::pubsub_protocol.incoming(pack,&nbsp;*this);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_incoming_handler&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
#endif<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_default_incoming_handler)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_incoming_handler&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_default_incoming_handler(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_incoming_handler&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;wproto&quot;,&nbsp;pack,&nbsp;_diagnostic_label,&nbsp;_debug_data_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::Tower::send_ack(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*ack&nbsp;=&nbsp;crow::create_packet(NULL,&nbsp;pack-&gt;addrsize(),&nbsp;0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(ack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_type(pack-&gt;quality()&nbsp;==&nbsp;CROW_BINARY_ACK&nbsp;?&nbsp;G1_ACK21_TYPE<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;G1_ACK_TYPE);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_ack(1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_quality(CROW_WITHOUT_ACK);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_ackquant(pack-&gt;ackquant());<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_seqid(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(ack-&gt;addrptr(),&nbsp;pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;u.f.released_by_world&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;travel(ack);<br>
}<br>
<br>
void&nbsp;crow::Tower::send_ack2(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*ack&nbsp;=&nbsp;crow::create_packet(NULL,&nbsp;pack-&gt;addrsize(),&nbsp;0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(ack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_type(G1_ACK22_TYPE);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_ack(1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_quality(CROW_WITHOUT_ACK);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_ackquant(pack-&gt;ackquant());<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_seqid(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(ack-&gt;addrptr(),&nbsp;pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;travel(ack);<br>
}<br>
<br>
void&nbsp;crow::Tower::revert_address(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;*first&nbsp;=&nbsp;pack-&gt;addrptr();<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;*last&nbsp;=&nbsp;pack-&gt;addrptr()&nbsp;+&nbsp;pack-&gt;addrsize();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;((first&nbsp;!=&nbsp;last)&nbsp;&amp;&amp;&nbsp;(first&nbsp;!=&nbsp;--last))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;tmp&nbsp;=&nbsp;*last;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*last&nbsp;=&nbsp;*first;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*first++&nbsp;=&nbsp;tmp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::Tower::send_to_gate_phase(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;gidx&nbsp;=&nbsp;*pack-&gt;stageptr();<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::gateway&nbsp;*gate&nbsp;=&nbsp;get_gateway(gidx);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(gate&nbsp;==&nbsp;NULL)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;second&nbsp;version&nbsp;compatible<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;crow_gateway&nbsp;*gateway&nbsp;=&nbsp;get_c_gateway(gidx);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(gateway)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ack())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled&nbsp;&amp;&amp;&nbsp;_diagnostic_noack&nbsp;==&nbsp;false)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;track&quot;,&nbsp;pack,&nbsp;_diagnostic_label,&nbsp;_debug_data_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;trans&quot;,&nbsp;pack,&nbsp;_diagnostic_label,&nbsp;_debug_data_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assert(pack-&gt;u.f.sended_to_gate&nbsp;==&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.sended_to_gate&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gateway-&gt;ops-&gt;send(gateway,&nbsp;pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;wgate&quot;,&nbsp;pack,&nbsp;_diagnostic_label,&nbsp;_debug_data_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ingate&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::warn(&quot;wrong&nbsp;gate&nbsp;in&nbsp;out&nbsp;packet&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ack())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled&nbsp;&amp;&amp;&nbsp;_diagnostic_noack&nbsp;==&nbsp;false)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;track&quot;,&nbsp;pack,&nbsp;_diagnostic_label,&nbsp;_debug_data_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;trans&quot;,&nbsp;pack,&nbsp;_diagnostic_label,&nbsp;_debug_data_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assert(pack-&gt;u.f.sended_to_gate&nbsp;==&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.sended_to_gate&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate-&gt;send(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::Tower::incoming_ack_phase(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled&nbsp;&amp;&amp;&nbsp;_diagnostic_noack&nbsp;==&nbsp;false)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;inack&quot;,&nbsp;pack,&nbsp;_diagnostic_label,&nbsp;_debug_data_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(pack-&gt;type())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;G1_ACK_TYPE:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;confirmed_utilize_from_outers(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;G1_ACK21_TYPE:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;confirmed_utilize_from_outers(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;send_ack2(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;G1_ACK22_TYPE:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;qos_release_from_incoming(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow::Tower::do_travel(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_total_travelled++;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;stage()&nbsp;==&nbsp;pack-&gt;addrsize())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Delivered&nbsp;packet&nbsp;branch<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;revert_address(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ack())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Intercept&nbsp;ack&nbsp;packets<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;incoming_ack_phase(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;incom&quot;,&nbsp;pack,&nbsp;_diagnostic_label,&nbsp;_debug_data_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ingate)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;If&nbsp;packet&nbsp;came&nbsp;from&nbsp;outside,&nbsp;use&nbsp;quality&nbsp;assurance&nbsp;logic<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;quality()&nbsp;==&nbsp;CROW_TARGET_ACK&nbsp;||<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;quality()&nbsp;==&nbsp;CROW_BINARY_ACK)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;send_ack(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;quality()&nbsp;==&nbsp;CROW_BINARY_ACK)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Check&nbsp;if&nbsp;packet&nbsp;is&nbsp;in&nbsp;incoming&nbsp;list<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*inc;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_head&nbsp;*bucket&nbsp;=&nbsp;_incoming_htable.bucket(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry(inc,&nbsp;bucket,&nbsp;ihlnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(inc-&gt;seqid()&nbsp;==&nbsp;pack-&gt;seqid()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inc-&gt;addrsize()&nbsp;==&nbsp;pack-&gt;addrsize()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcmp(inc-&gt;addrptr(),&nbsp;pack-&gt;addrptr(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inc-&gt;addrsize())&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;DUPFLT:&nbsp;filtered&nbsp;duplicate&nbsp;seqid=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dprhex(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;&nbsp;(in&nbsp;incoming_htable)\n&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Check&nbsp;TIME_WAIT&nbsp;for&nbsp;late&nbsp;retransmits&nbsp;after&nbsp;ACK22<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(time_wait_check(pack-&gt;seqid(),&nbsp;pack-&gt;addrptr(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;addrsize()))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;DUPFLT:&nbsp;filtered&nbsp;duplicate&nbsp;seqid=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dprhex(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;&nbsp;(in&nbsp;TIME_WAIT)\n&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;DUPFLT:&nbsp;new&nbsp;packet&nbsp;seqid=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dprhex(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;&nbsp;adding&nbsp;to&nbsp;htable,&nbsp;inc_count=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(_incoming_count);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dln();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Mark&nbsp;packet&nbsp;as&nbsp;received&nbsp;for&nbsp;filtering&nbsp;subsequent&nbsp;copies<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!add_to_incoming_list(pack))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;List&nbsp;full,&nbsp;drop&nbsp;packet<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ingate&nbsp;&amp;&amp;&nbsp;pack-&gt;quality()&nbsp;!=&nbsp;2)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower_release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Process&nbsp;incoming&nbsp;packet<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;incoming_handler(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Transit&nbsp;packet&nbsp;branch<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ingate&nbsp;&amp;&amp;&nbsp;_retransling_allowed&nbsp;==&nbsp;false)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;int&nbsp;warned&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(warned&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;warned&nbsp;=&nbsp;1;<br>
#ifndef&nbsp;MEMORY_ECONOMY<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::warn(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Crow&nbsp;get&nbsp;retransling&nbsp;request&nbsp;but&nbsp;retransling&nbsp;is&nbsp;not&nbsp;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;allowed.\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Use&nbsp;tower.set_retransling_allowed(true)&nbsp;to&nbsp;enable&nbsp;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;retransling\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Or&nbsp;use&nbsp;--retransler&nbsp;option&nbsp;if&nbsp;utility&nbsp;allowed&nbsp;it.\n&quot;);<br>
#endif<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;send_to_gate_phase(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::Tower::transport(crow::packet&nbsp;*pack,&nbsp;bool&nbsp;async)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_stage(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ack(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_seqid(_seqcounter++);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet_ptr&nbsp;ptr(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(async)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;travel(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;do_travel(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::Tower::nocontrol_travel(crow::packet&nbsp;*pack,&nbsp;bool&nbsp;fastsend)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(fastsend)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;do_travel(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_add_tail(&amp;pack-&gt;lnk,&nbsp;&amp;_travelled);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::Tower::send(const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;data,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;crow::create_packet(NULL,&nbsp;addr.size(),&nbsp;data.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::warn(&quot;cannot&nbsp;create&nbsp;packet&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(type&nbsp;&amp;&nbsp;0x1F);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(qos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(ackquant);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;addr.data(),&nbsp;addr.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;dataptr(),&nbsp;data.data(),&nbsp;data.size());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;transport(pack,&nbsp;async);<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::Tower::send_v(const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;dsize&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*it&nbsp;=&nbsp;vec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*const&nbsp;eit&nbsp;=&nbsp;vec&nbsp;+&nbsp;veclen;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dsize&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;crow::create_packet(NULL,&nbsp;addr.size(),&nbsp;dsize);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(type&nbsp;&amp;&nbsp;0x1F);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(qos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(ackquant);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;addr.data(),&nbsp;addr.size());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;*dst&nbsp;=&nbsp;pack-&gt;dataptr();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(dst,&nbsp;it-&gt;data(),&nbsp;it-&gt;size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;transport(pack,&nbsp;async);<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::Tower::send_vv(const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;dsize&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*it;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*eit;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec&nbsp;+&nbsp;veclen;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dsize&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec2&nbsp;+&nbsp;veclen2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dsize&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;crow::create_packet(NULL,&nbsp;addr.size(),&nbsp;dsize);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(type&nbsp;&amp;&nbsp;0x1F);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(qos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(ackquant);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;addr.data(),&nbsp;addr.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;*dst&nbsp;=&nbsp;pack-&gt;dataptr();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec&nbsp;+&nbsp;veclen;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(dst,&nbsp;it-&gt;data(),&nbsp;it-&gt;size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec2&nbsp;+&nbsp;veclen2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(dst,&nbsp;it-&gt;data(),&nbsp;it-&gt;size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;transport(pack,&nbsp;async);<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::Tower::send_vvv(const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec3,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen3,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;dsize&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*it;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*eit;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec&nbsp;+&nbsp;veclen;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dsize&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec2&nbsp;+&nbsp;veclen2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dsize&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec3;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec3&nbsp;+&nbsp;veclen3;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dsize&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;crow::create_packet(NULL,&nbsp;addr.size(),&nbsp;dsize);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(type&nbsp;&amp;&nbsp;0x1F);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(qos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(ackquant);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;addr.data(),&nbsp;addr.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;*dst&nbsp;=&nbsp;pack-&gt;dataptr();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec&nbsp;+&nbsp;veclen;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(dst,&nbsp;it-&gt;data(),&nbsp;it-&gt;size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec2&nbsp;+&nbsp;veclen2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(dst,&nbsp;it-&gt;data(),&nbsp;it-&gt;size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec3;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec3&nbsp;+&nbsp;veclen3;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(dst,&nbsp;it-&gt;data(),&nbsp;it-&gt;size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;transport(pack,&nbsp;async);<br>
}<br>
<br>
void&nbsp;crow::Tower::return_to_tower(crow::packet&nbsp;*pack,&nbsp;uint8_t&nbsp;sts)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.sended_to_gate&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ingate&nbsp;!=&nbsp;NULL)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Packet&nbsp;was&nbsp;sent&nbsp;and&nbsp;it's&nbsp;not&nbsp;from&nbsp;here.&nbsp;Destroy.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Local&nbsp;packet<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sts&nbsp;!=&nbsp;CROW_SENDED&nbsp;||&nbsp;pack-&gt;quality()&nbsp;==&nbsp;CROW_WITHOUT_ACK)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower_release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else&nbsp;if&nbsp;(!add_to_outters_list(pack))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;List&nbsp;full,&nbsp;mark&nbsp;as&nbsp;undelivered<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.undelivered&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower_release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow::Tower::undelivered(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.undelivered&nbsp;=&nbsp;1;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_undelivered_handler)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_undelivered_handler&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_undelivered_handler(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_undelivered_handler&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(CROW_NODE_PROTOCOL&nbsp;==&nbsp;pack-&gt;type())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_undelivered_handler&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::node_protocol.undelivered(pack,&nbsp;*this);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_undelivered_handler&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
#ifdef&nbsp;CROW_PUBSUB_PROTOCOL_SUPPORTED<br>
&nbsp;&nbsp;&nbsp;&nbsp;else&nbsp;if&nbsp;(CROW_PUBSUB_PROTOCOL&nbsp;==&nbsp;pack-&gt;type())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_undelivered_handler&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::pubsub_protocol.undelivered(pack,&nbsp;*this);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_undelivered_handler&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
#endif<br>
}<br>
<br>
void&nbsp;crow::Tower::onestep_send_stage()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(dlist_empty(&amp;_travelled))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack&nbsp;=&nbsp;dlist_first_entry(&amp;_travelled,&nbsp;crow::packet,&nbsp;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del_init(&amp;pack-&gt;lnk);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;do_travel(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow::Tower::onestep_outers_stage()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*n;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;curtime&nbsp;=&nbsp;igris::millis();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(dlist_empty(&amp;_outters))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry_safe(pack,&nbsp;n,&nbsp;&amp;_outters,&nbsp;lnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assert(pack-&gt;u.f.released_by_tower&nbsp;==&nbsp;0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(curtime&nbsp;-&nbsp;pack-&gt;last_request_time&nbsp;&gt;=&nbsp;pack-&gt;ackquant())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del_init(&amp;pack-&gt;lnk);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;_ackcount&nbsp;!=&nbsp;0xFFFF)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--pack-&gt;_ackcount;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;_ackcount&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_outters_count&nbsp;&gt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--_outters_count;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;undelivered(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower_release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;OUTFLT:&nbsp;RETRANSMIT&nbsp;seqid=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dprhex(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;&nbsp;ackcount=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(pack-&gt;_ackcount);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dln();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;travel(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow::Tower::onestep_incoming_stage()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*n;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;curtime&nbsp;=&nbsp;igris::millis();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(dlist_empty(&amp;_incoming))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry_safe(pack,&nbsp;n,&nbsp;&amp;_incoming,&nbsp;lnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assert(pack-&gt;u.f.released_by_tower&nbsp;==&nbsp;0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(curtime&nbsp;-&nbsp;pack-&gt;last_request_time&nbsp;&gt;=&nbsp;pack-&gt;ackquant())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del_init(&amp;pack-&gt;lnk);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;_ackcount&nbsp;!=&nbsp;0xFFFF)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--pack-&gt;_ackcount;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;_ackcount&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;DUPFLT:&nbsp;TIMEOUT&nbsp;removing&nbsp;seqid=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dprhex(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(&quot;&nbsp;from&nbsp;htable,&nbsp;inc_count=&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(_incoming_count);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dln();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_incoming_htable.remove(&amp;pack-&gt;ihlnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_incoming_count&nbsp;&gt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--_incoming_count;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.undelivered&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.released_by_tower&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;u.f.released_by_world&nbsp;&amp;&amp;&nbsp;pack-&gt;refs&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_move_sorted(pack,&nbsp;&amp;_incoming,&nbsp;lnk,&nbsp;crow_time_comparator);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;last_request_time&nbsp;=&nbsp;curtime;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;send_ack(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow::Tower::onestep_keepalive_stage()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::keepalive_timer_manager.exec(igris::millis());<br>
}<br>
<br>
void&nbsp;crow::Tower::onestep()<br>
{<br>
#ifndef&nbsp;CROW_USE_ASYNCIO<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::gateway&nbsp;*gate;<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry(gate,&nbsp;&amp;_gateway_list,&nbsp;lnk)&nbsp;{&nbsp;gate-&gt;nblock_onestep();&nbsp;}<br>
#endif<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;onestep_send_stage();<br>
&nbsp;&nbsp;&nbsp;&nbsp;onestep_keepalive_stage();<br>
&nbsp;&nbsp;&nbsp;&nbsp;onestep_outers_stage();<br>
&nbsp;&nbsp;&nbsp;&nbsp;onestep_incoming_stage();<br>
}<br>
<br>
void&nbsp;crow::Tower::onestep_travel_only()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;onestep_send_stage();<br>
}<br>
<br>
int&nbsp;crow::Tower::incomming_stage_count()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;dlist_size(&amp;_incoming);<br>
}<br>
<br>
int&nbsp;crow::Tower::outers_stage_count()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;dlist_size(&amp;_outters);<br>
}<br>
<br>
bool&nbsp;crow::Tower::has_untravelled()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;ret&nbsp;=&nbsp;!(dlist_empty(&amp;_travelled)&nbsp;&amp;&amp;&nbsp;dlist_empty(&amp;_outters)&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_empty(&amp;_incoming));<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ret;<br>
}<br>
<br>
bool&nbsp;crow::Tower::has_untravelled_now()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;ret&nbsp;=&nbsp;!dlist_empty(&amp;_travelled);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ret;<br>
}<br>
<br>
void&nbsp;crow::Tower::finish()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::gateway&nbsp;*gate;<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry(gate,&nbsp;&amp;_gateway_list,&nbsp;lnk)&nbsp;{&nbsp;gate-&gt;finish();&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::Tower::reset_for_test()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Clear&nbsp;travelled&nbsp;list<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(!dlist_empty(&amp;_travelled))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_first_entry(&amp;_travelled,&nbsp;crow::packet,&nbsp;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del(&amp;pack-&gt;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Clear&nbsp;incoming&nbsp;list<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(!dlist_empty(&amp;_incoming))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;dlist_first_entry(&amp;_incoming,&nbsp;crow::packet,&nbsp;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del(&amp;pack-&gt;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Clear&nbsp;outters&nbsp;list<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(!dlist_empty(&amp;_outters))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;dlist_first_entry(&amp;_outters,&nbsp;crow::packet,&nbsp;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del(&amp;pack-&gt;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;_total_travelled&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::reset_allocated_count();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
bool&nbsp;crow::Tower::fully_empty()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;ret&nbsp;=&nbsp;dlist_empty(&amp;_travelled)&nbsp;&amp;&amp;&nbsp;dlist_empty(&amp;_incoming)&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_empty(&amp;_outters);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ret;<br>
}<br>
<br>
int64_t&nbsp;crow::Tower::get_minimal_timeout()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int64_t&nbsp;mininterval&nbsp;=&nbsp;std::numeric_limits&lt;int64_t&gt;::max();<br>
&nbsp;&nbsp;&nbsp;&nbsp;int64_t&nbsp;curtime&nbsp;=&nbsp;igris::millis();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;update_candidate&nbsp;=&nbsp;[&amp;](int64_t&nbsp;candidate)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(mininterval&nbsp;&gt;&nbsp;candidate)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mininterval&nbsp;=&nbsp;candidate;<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!keepalive_timer_manager.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;update_candidate(keepalive_timer_manager.minimal_interval(curtime));<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!dlist_empty(&amp;_incoming))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*i&nbsp;=&nbsp;dlist_first_entry(&amp;_incoming,&nbsp;crow::packet,&nbsp;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;update_candidate(i-&gt;last_request_time&nbsp;+&nbsp;i-&gt;ackquant()&nbsp;-&nbsp;curtime);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!dlist_empty(&amp;_outters))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*o&nbsp;=&nbsp;dlist_first_entry(&amp;_outters,&nbsp;crow::packet,&nbsp;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;update_candidate(o-&gt;last_request_time&nbsp;+&nbsp;o-&gt;ackquant()&nbsp;-&nbsp;curtime);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(mininterval&nbsp;==&nbsp;std::numeric_limits&lt;int64_t&gt;::max())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;else&nbsp;if&nbsp;(mininterval&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;mininterval;<br>
}<br>
<br>
void&nbsp;crow::Tower::enable_diagnostic()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_diagnostic_enabled&nbsp;=&nbsp;true;<br>
}<br>
<br>
bool&nbsp;crow::Tower::diagnostic_enabled()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_diagnostic_enabled;<br>
}<br>
<br>
void&nbsp;crow::Tower::diagnostic_setup(bool&nbsp;en)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_diagnostic_enabled&nbsp;=&nbsp;en;<br>
}<br>
<br>
void&nbsp;crow::Tower::set_time_wait_duration(uint32_t&nbsp;duration_ms)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_time_wait_duration_ms&nbsp;=&nbsp;duration_ms;<br>
}<br>
<br>
uint32_t&nbsp;crow::Tower::get_time_wait_duration()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_time_wait_duration_ms;<br>
}<br>
<br>
void&nbsp;crow::Tower::set_initial_seqid(uint16_t&nbsp;seqid)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_seqcounter&nbsp;=&nbsp;seqid;<br>
}<br>
<br>
uint16_t&nbsp;crow::Tower::get_current_seqid()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_seqcounter;<br>
}<br>
<br>
void&nbsp;crow::Tower::set_diagnostic_label(const&nbsp;std::string&nbsp;&amp;name)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_diagnostic_label&nbsp;=&nbsp;name;<br>
}<br>
<br>
const&nbsp;std::string&nbsp;&amp;crow::Tower::get_diagnostic_label()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_diagnostic_label;<br>
}<br>
<br>
void&nbsp;crow::Tower::set_diagnostic_noack(bool&nbsp;value)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_diagnostic_noack&nbsp;=&nbsp;value;<br>
}<br>
<br>
bool&nbsp;crow::Tower::get_diagnostic_noack()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_diagnostic_noack;<br>
}<br>
<br>
void&nbsp;crow::Tower::set_debug_data_size(uint16_t&nbsp;size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_debug_data_size&nbsp;=&nbsp;size;<br>
}<br>
<br>
uint16_t&nbsp;crow::Tower::get_debug_data_size()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_debug_data_size;<br>
}<br>
<br>
void&nbsp;crow::Tower::set_retransling_allowed(bool&nbsp;value)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_retransling_allowed&nbsp;=&nbsp;value;<br>
}<br>
<br>
bool&nbsp;crow::Tower::get_retransling_allowed()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_retransling_allowed;<br>
}<br>
<br>
unsigned&nbsp;int&nbsp;crow::Tower::get_total_travelled()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_total_travelled;<br>
}<br>
<br>
void&nbsp;crow::Tower::reset_total_travelled()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_total_travelled&nbsp;=&nbsp;0;<br>
}<br>
<br>
void&nbsp;crow::Tower::set_default_incoming_handler(void&nbsp;(*handler)(packet&nbsp;*))<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_default_incoming_handler&nbsp;=&nbsp;handler;<br>
}<br>
<br>
void&nbsp;(*crow::Tower::get_default_incoming_handler()&nbsp;const)(packet&nbsp;*)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_default_incoming_handler;<br>
}<br>
<br>
void&nbsp;crow::Tower::set_undelivered_handler(void&nbsp;(*handler)(packet&nbsp;*))<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_undelivered_handler&nbsp;=&nbsp;handler;<br>
}<br>
<br>
void&nbsp;(*crow::Tower::get_undelivered_handler()&nbsp;const)(packet&nbsp;*)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_undelivered_handler;<br>
}<br>
<br>
void&nbsp;crow::Tower::set_unsleep_handler(igris::delegate&lt;void&gt;&nbsp;handler)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_unsleep_handler&nbsp;=&nbsp;handler;<br>
}<br>
<br>
igris::delegate&lt;void&gt;&nbsp;crow::Tower::get_unsleep_handler()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_unsleep_handler;<br>
}<br>
<br>
dlist_head&nbsp;&amp;crow::Tower::gateway_list()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_gateway_list;<br>
}<br>
<br>
dlist_head&nbsp;&amp;crow::Tower::c_gateway_list()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_c_gateway_list;<br>
}<br>
<br>
crow::gateway&nbsp;*crow::Tower::get_gateway(int&nbsp;no)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::gateway&nbsp;*g;<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry(g,&nbsp;&amp;_gateway_list,&nbsp;lnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(g-&gt;id&nbsp;==&nbsp;no)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;g;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
}<br>
<br>
crow_gateway&nbsp;*crow::Tower::get_c_gateway(int&nbsp;no)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow_gateway&nbsp;*g;<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry(g,&nbsp;&amp;_c_gateway_list,&nbsp;lnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(g-&gt;id&nbsp;==&nbsp;no)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;g;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
}<br>
<br>
int&nbsp;crow::Tower::bind_gateway(gateway&nbsp;*gate,&nbsp;int&nbsp;gateno)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(get_gateway(gateno))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;gate-&gt;id&nbsp;=&nbsp;gateno;<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_add_tail(&amp;gate-&gt;lnk,&nbsp;&amp;_gateway_list);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
int&nbsp;crow::Tower::bind_c_gateway(crow_gateway&nbsp;*gate,&nbsp;int&nbsp;gateno)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(get_c_gateway(gateno))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;gate-&gt;id&nbsp;=&nbsp;gateno;<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_add_tail(&amp;gate-&gt;lnk,&nbsp;&amp;_c_gateway_list);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
