<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/src/tower.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**&nbsp;@file&nbsp;*/<br>
<br>
#include&nbsp;&lt;assert.h&gt;<br>
#include&nbsp;&lt;limits&gt;<br>
#include&nbsp;&lt;stdbool.h&gt;<br>
#include&nbsp;&lt;string.h&gt;<br>
<br>
#include&nbsp;&lt;igris/event/delegate.h&gt;<br>
#include&nbsp;&lt;igris/sync/syslock.h&gt;<br>
#include&nbsp;&lt;igris/time/systime.h&gt;<br>
<br>
#include&nbsp;&lt;crow/gateway.h&gt;<br>
#include&nbsp;&lt;crow/print.h&gt;<br>
#include&nbsp;&lt;crow/proto/node.h&gt;<br>
#include&nbsp;&lt;crow/pubsub/pubsub.h&gt;<br>
#include&nbsp;&lt;crow/tower.h&gt;<br>
#include&nbsp;&lt;crow/warn.h&gt;<br>
<br>
#include&nbsp;&lt;nos/print.h&gt;<br>
<br>
#ifdef&nbsp;CROW_USE_ASYNCIO<br>
#include&nbsp;&lt;crow/asyncio.h&gt;<br>
#endif<br>
<br>
bool&nbsp;crow::diagnostic_noack&nbsp;=&nbsp;false;<br>
uint16_t&nbsp;crow::debug_data_size&nbsp;=&nbsp;60;<br>
unsigned&nbsp;int&nbsp;crow::total_travelled&nbsp;=&nbsp;0;<br>
<br>
bool&nbsp;crow::retransling_allowed&nbsp;=&nbsp;false;<br>
<br>
DLIST_HEAD(crow_travelled);<br>
DLIST_HEAD(crow_incoming);<br>
DLIST_HEAD(crow_outters);<br>
<br>
igris::delegate&lt;void&gt;&nbsp;crow::unsleep_handler;<br>
void&nbsp;(*crow::default_incoming_handler)(crow::packet&nbsp;*pack)&nbsp;=&nbsp;nullptr;<br>
void&nbsp;(*crow::undelivered_handler)(crow::packet&nbsp;*pack)&nbsp;=&nbsp;nullptr;<br>
<br>
static&nbsp;bool&nbsp;__diagnostic_enabled&nbsp;=&nbsp;false;<br>
<br>
bool&nbsp;_in_incoming_handler&nbsp;=&nbsp;false;<br>
bool&nbsp;_in_undelivered_handler&nbsp;=&nbsp;false;<br>
<br>
bool&nbsp;crow::diagnostic_enabled()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;__diagnostic_enabled;<br>
}<br>
void&nbsp;crow::enable_diagnostic()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;__diagnostic_enabled&nbsp;=&nbsp;true;<br>
}<br>
<br>
void&nbsp;crow::diagnostic_setup(bool&nbsp;en)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;__diagnostic_enabled&nbsp;=&nbsp;en;<br>
}<br>
<br>
void&nbsp;crow::utilize(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_del(&amp;pack-&gt;lnk);&nbsp;//&nbsp;Очищается&nbsp;в&nbsp;tower_release((см.&nbsp;tower.c))<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_del(&amp;pack-&gt;ulnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;invalidate();<br>
}<br>
<br>
void&nbsp;crow::release(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;u.f.released_by_tower&nbsp;&amp;&amp;&nbsp;pack-&gt;refs&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.released_by_world&nbsp;=&nbsp;true;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow::tower_release(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//Скорее&nbsp;всего&nbsp;это&nbsp;поле&nbsp;должно&nbsp;освобождаться&nbsp;без&nbsp;инициализации.<br>
&nbsp;&nbsp;&nbsp;&nbsp;//Инициализируем&nbsp;для&nbsp;последуещего&nbsp;освобождения&nbsp;в&nbsp;utilize<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_del_init(&amp;pack-&gt;lnk);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;u.f.released_by_world&nbsp;&amp;&amp;&nbsp;pack-&gt;refs&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.released_by_tower&nbsp;=&nbsp;true;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
static&nbsp;void&nbsp;confirmed_utilize_from_outers(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*it;<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry(it,&nbsp;&amp;crow_outters,&nbsp;lnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it-&gt;seqid()&nbsp;==&nbsp;pack-&gt;seqid()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;addrsize()&nbsp;==&nbsp;it-&gt;addrsize()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;!memcmp(it-&gt;addrptr(),&nbsp;pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize()))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;it-&gt;u.f.confirmed&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::node_protocol.delivered(it);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::tower_release(it);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
static&nbsp;void&nbsp;qos_release_from_incoming(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*it;<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry(it,&nbsp;&amp;crow_incoming,&nbsp;lnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it-&gt;seqid()&nbsp;==&nbsp;pack-&gt;seqid()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;addrsize()&nbsp;==&nbsp;it-&gt;addrsize()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;!memcmp(it-&gt;addrptr(),&nbsp;pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize()))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::tower_release(it);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
bool&nbsp;crow_time_comparator(crow::packet&nbsp;*a,&nbsp;crow::packet&nbsp;*b)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint64_t&nbsp;a_timer&nbsp;=&nbsp;a-&gt;last_request_time&nbsp;+&nbsp;a-&gt;ackquant();<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint64_t&nbsp;b_timer&nbsp;=&nbsp;b-&gt;last_request_time&nbsp;+&nbsp;b-&gt;ackquant();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;a_timer&nbsp;&lt;&nbsp;b_timer;<br>
}<br>
<br>
static&nbsp;void&nbsp;add_to_incoming_list(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;last_request_time&nbsp;=&nbsp;igris::millis();<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_move_sorted(pack,&nbsp;&amp;crow_incoming,&nbsp;lnk,&nbsp;crow_time_comparator);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::unsleep();<br>
}<br>
<br>
static&nbsp;void&nbsp;add_to_outters_list(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;last_request_time&nbsp;=&nbsp;igris::millis();<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_move_sorted(pack,&nbsp;&amp;crow_outters,&nbsp;lnk,&nbsp;crow_time_comparator);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::unsleep();<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::travel(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_add_tail(&amp;pack-&gt;lnk,&nbsp;&amp;crow_travelled);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::unsleep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;crow::packet_ptr(pack);<br>
}<br>
<br>
void&nbsp;crow::unsleep()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(unsleep_handler)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;unsleep_handler();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
#ifdef&nbsp;CROW_USE_ASYNCIO<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::asyncio.unsleep();<br>
#endif<br>
}<br>
<br>
static&nbsp;void&nbsp;crow_incoming_handler(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(CROW_NODE_PROTOCOL&nbsp;==&nbsp;pack-&gt;type())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_incoming_handler&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::node_protocol.incoming(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_incoming_handler&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
#ifdef&nbsp;CROW_PUBSUB_PROTOCOL_SUPPORTED<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(CROW_PUBSUB_PROTOCOL&nbsp;==&nbsp;pack-&gt;type())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_incoming_handler&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::pubsub_protocol.incoming(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_incoming_handler&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
#endif<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(crow::default_incoming_handler)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_incoming_handler&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::default_incoming_handler(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_incoming_handler&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(__diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;wproto&quot;,&nbsp;pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
static&nbsp;void&nbsp;crow_send_ack(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*ack&nbsp;=&nbsp;crow::create_packet(NULL,&nbsp;pack-&gt;addrsize(),&nbsp;0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(ack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_type(pack-&gt;quality()&nbsp;==&nbsp;CROW_BINARY_ACK&nbsp;?&nbsp;G1_ACK21_TYPE<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;G1_ACK_TYPE);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_ack(1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_quality(CROW_WITHOUT_ACK);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_ackquant(pack-&gt;ackquant());<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_seqid(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(ack-&gt;addrptr(),&nbsp;pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;u.f.released_by_world&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::travel(ack);<br>
}<br>
<br>
static&nbsp;void&nbsp;crow_send_ack2(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*ack&nbsp;=&nbsp;crow::create_packet(NULL,&nbsp;pack-&gt;addrsize(),&nbsp;0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(ack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_type(G1_ACK22_TYPE);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_ack(1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_quality(CROW_WITHOUT_ACK);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_ackquant(pack-&gt;ackquant());<br>
&nbsp;&nbsp;&nbsp;&nbsp;ack-&gt;set_seqid(pack-&gt;seqid());<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(ack-&gt;addrptr(),&nbsp;pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::travel(ack);<br>
}<br>
<br>
static&nbsp;void&nbsp;crow_revert_address(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;*first&nbsp;=&nbsp;pack-&gt;addrptr();<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;*last&nbsp;=&nbsp;pack-&gt;addrptr()&nbsp;+&nbsp;pack-&gt;addrsize();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;((first&nbsp;!=&nbsp;last)&nbsp;&amp;&amp;&nbsp;(first&nbsp;!=&nbsp;--last))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;tmp&nbsp;=&nbsp;*last;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*last&nbsp;=&nbsp;*first;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*first++&nbsp;=&nbsp;tmp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
static&nbsp;void&nbsp;crow_tower_send_to_gate_phase(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;gidx&nbsp;=&nbsp;*pack-&gt;stageptr();<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::gateway&nbsp;*gate&nbsp;=&nbsp;crow::get_gateway(gidx);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(gate&nbsp;==&nbsp;NULL)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;second&nbsp;version&nbsp;compatible<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;crow_gateway&nbsp;*gateway&nbsp;=&nbsp;crow_get_gateway(gidx);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(gateway)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ack())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(__diagnostic_enabled&nbsp;&amp;&amp;&nbsp;crow::diagnostic_noack&nbsp;==&nbsp;false)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;track&quot;,&nbsp;pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(__diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;trans&quot;,&nbsp;pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//Здесь&nbsp;пакет&nbsp;штампуется&nbsp;временем&nbsp;отправки&nbsp;и&nbsp;пересылается&nbsp;во&nbsp;врата.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//Врата&nbsp;должны&nbsp;после&nbsp;пересылки&nbsp;отправить&nbsp;его&nbsp;назад&nbsp;в&nbsp;башню<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//с&nbsp;помощью&nbsp;return_to_tower&nbsp;для&nbsp;контроля&nbsp;качества.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assert(pack-&gt;u.f.sended_to_gate&nbsp;==&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.sended_to_gate&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gateway-&gt;ops-&gt;send(gateway,&nbsp;pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(__diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;wgate&quot;,&nbsp;pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ingate&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::warn(&quot;wrong&nbsp;gate&nbsp;in&nbsp;out&nbsp;packet&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ack())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(__diagnostic_enabled&nbsp;&amp;&amp;&nbsp;crow::diagnostic_noack&nbsp;==&nbsp;false)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;track&quot;,&nbsp;pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(__diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;trans&quot;,&nbsp;pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//Здесь&nbsp;пакет&nbsp;штампуется&nbsp;временем&nbsp;отправки&nbsp;и&nbsp;пересылается&nbsp;во&nbsp;врата.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//Врата&nbsp;должны&nbsp;после&nbsp;пересылки&nbsp;отправить&nbsp;его&nbsp;назад&nbsp;в&nbsp;башню<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//с&nbsp;помощью&nbsp;return_to_tower&nbsp;для&nbsp;контроля&nbsp;качества.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assert(pack-&gt;u.f.sended_to_gate&nbsp;==&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.sended_to_gate&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate-&gt;send(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
static&nbsp;void&nbsp;crow_tower_incoming_ack_phase(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(__diagnostic_enabled&nbsp;&amp;&amp;&nbsp;crow::diagnostic_noack&nbsp;==&nbsp;false)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;inack&quot;,&nbsp;pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(pack-&gt;type())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;G1_ACK_TYPE:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;confirmed_utilize_from_outers(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;G1_ACK21_TYPE:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;confirmed_utilize_from_outers(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow_send_ack2(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;G1_ACK22_TYPE:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;qos_release_from_incoming(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
static&nbsp;void&nbsp;crow_do_travel(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::total_travelled++;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;stage()&nbsp;==&nbsp;pack-&gt;addrsize())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//Ветка&nbsp;доставленного&nbsp;пакета.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow_revert_address(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ack())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//Перехватываем&nbsp;ack&nbsp;пакеты.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow_tower_incoming_ack_phase(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(__diagnostic_enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;incom&quot;,&nbsp;pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ingate)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//Если&nbsp;пакет&nbsp;пришел&nbsp;извне,&nbsp;используем&nbsp;логику&nbsp;обеспечения&nbsp;качества.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//Для&nbsp;пакетов&nbsp;с&nbsp;подтверждение&nbsp;посылаем&nbsp;ack&nbsp;первого&nbsp;или&nbsp;второго<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//типов.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;quality()&nbsp;==&nbsp;CROW_TARGET_ACK&nbsp;||<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;quality()&nbsp;==&nbsp;CROW_BINARY_ACK)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow_send_ack(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;quality()&nbsp;==&nbsp;CROW_BINARY_ACK)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//Перед&nbsp;тем&nbsp;как&nbsp;добавить&nbsp;пакет&nbsp;в&nbsp;обработку,&nbsp;проверяем,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//нет&nbsp;ли&nbsp;его&nbsp;в&nbsp;списке&nbsp;принятых.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*inc;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry(inc,&nbsp;&amp;crow_incoming,&nbsp;lnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(inc-&gt;seqid()&nbsp;==&nbsp;pack-&gt;seqid()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inc-&gt;addrsize()&nbsp;==&nbsp;pack-&gt;addrsize()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcmp(inc-&gt;addrptr(),&nbsp;pack-&gt;addrptr(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inc-&gt;addrsize())&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Пакет&nbsp;уже&nbsp;фигурирует&nbsp;как&nbsp;принятый,&nbsp;поэтому<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;отбрасываем&nbsp;его.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Фиксирем&nbsp;пакет&nbsp;как&nbsp;принятый&nbsp;для&nbsp;фильтрации<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;возможных&nbsp;последующих&nbsp;копий.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;add_to_incoming_list(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ingate&nbsp;&amp;&amp;&nbsp;pack-&gt;quality()&nbsp;!=&nbsp;2)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Если&nbsp;пакет&nbsp;отправлен&nbsp;из&nbsp;данного&nbsp;нода,&nbsp;или&nbsp;не&nbsp;требуется<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;подтверждения&nbsp;второго&nbsp;уровня,&nbsp;обслуживание&nbsp;со&nbsp;стороны&nbsp;башни&nbsp;не<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;требуется.&nbsp;Вносим&nbsp;соответствующую&nbsp;пометку,&nbsp;что&nbsp;по&nbsp;crow_release<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;пакет&nbsp;мог&nbsp;быть&nbsp;удалён.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::tower_release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//Решаем,&nbsp;что&nbsp;делать&nbsp;с&nbsp;пришедшим&nbsp;пакетом.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow_incoming_handler(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//Ветка&nbsp;транзитного&nbsp;пакета.&nbsp;Логика&nbsp;поиска&nbsp;врат&nbsp;и&nbsp;пересылки.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ingate&nbsp;&amp;&amp;&nbsp;crow::retransling_allowed&nbsp;==&nbsp;false)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;int&nbsp;warned&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(warned&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;warned&nbsp;=&nbsp;1;<br>
#ifndef&nbsp;MEMORY_ECONOMY<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::warn(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Crow&nbsp;get&nbsp;retransling&nbsp;request&nbsp;but&nbsp;retransling&nbsp;is&nbsp;not&nbsp;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;allowed.\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Set&nbsp;crow::retransling_allowed&nbsp;option&nbsp;for&nbsp;enable&nbsp;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;retransling\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Or&nbsp;use&nbsp;--retransler&nbsp;option&nbsp;if&nbsp;utility&nbsp;allowed&nbsp;it.\n&quot;);<br>
#endif<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow_tower_send_to_gate_phase(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
uint16_t&nbsp;__seqcounter&nbsp;=&nbsp;0;<br>
crow::packet_ptr&nbsp;crow_transport(crow::packet&nbsp;*pack,&nbsp;bool&nbsp;async)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_stage(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ack(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_seqid(__seqcounter++);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet_ptr&nbsp;ptr(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(async)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;crow::travel(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow_do_travel(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Делаем&nbsp;unsleep,&nbsp;чтобы&nbsp;перерасчитать&nbsp;таймауты.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/*&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(crow::unsleep_handler&nbsp;&amp;&amp;&nbsp;pack-&gt;quality()&nbsp;!=&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::unsleep_handler();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#ifdef&nbsp;CROW_USE_ASYNCIO<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::asyncio.unsleep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#endif<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::nocontrol_travel(crow::packet&nbsp;*pack,&nbsp;bool&nbsp;fastsend)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(fastsend)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow_do_travel(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_add_tail(&amp;pack-&gt;lnk,&nbsp;&amp;crow_travelled);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::send(const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;data,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;crow::create_packet(NULL,&nbsp;addr.size(),&nbsp;data.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::warn(&quot;cannot&nbsp;create&nbsp;packet&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(type&nbsp;&amp;&nbsp;0x1F);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(qos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(ackquant);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;addr.data(),&nbsp;addr.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;dataptr(),&nbsp;data.data(),&nbsp;data.size());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;crow_transport(pack,&nbsp;async);<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::send_v(const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;dsize&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*it&nbsp;=&nbsp;vec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*const&nbsp;eit&nbsp;=&nbsp;vec&nbsp;+&nbsp;veclen;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dsize&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;crow::create_packet(NULL,&nbsp;addr.size(),&nbsp;dsize);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(type&nbsp;&amp;&nbsp;0x1F);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(qos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(ackquant);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;addr.data(),&nbsp;addr.size());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;*dst&nbsp;=&nbsp;pack-&gt;dataptr();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(dst,&nbsp;it-&gt;data(),&nbsp;it-&gt;size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;crow_transport(pack,&nbsp;async);<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::send_vv(const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;dsize&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*it;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*eit;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec&nbsp;+&nbsp;veclen;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dsize&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec2&nbsp;+&nbsp;veclen2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dsize&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;crow::create_packet(NULL,&nbsp;addr.size(),&nbsp;dsize);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(type&nbsp;&amp;&nbsp;0x1F);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(qos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(ackquant);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;addr.data(),&nbsp;addr.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;*dst&nbsp;=&nbsp;pack-&gt;dataptr();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec&nbsp;+&nbsp;veclen;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(dst,&nbsp;it-&gt;data(),&nbsp;it-&gt;size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec2&nbsp;+&nbsp;veclen2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(dst,&nbsp;it-&gt;data(),&nbsp;it-&gt;size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;crow_transport(pack,&nbsp;async);<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::send_vvv(const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec3,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen3,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;dsize&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*it;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*eit;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec&nbsp;+&nbsp;veclen;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dsize&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec2&nbsp;+&nbsp;veclen2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dsize&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec3;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec3&nbsp;+&nbsp;veclen3;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dsize&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;crow::create_packet(NULL,&nbsp;addr.size(),&nbsp;dsize);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(type&nbsp;&amp;&nbsp;0x1F);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(qos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(ackquant);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;addr.data(),&nbsp;addr.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;*dst&nbsp;=&nbsp;pack-&gt;dataptr();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec&nbsp;+&nbsp;veclen;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(dst,&nbsp;it-&gt;data(),&nbsp;it-&gt;size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec2&nbsp;+&nbsp;veclen2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(dst,&nbsp;it-&gt;data(),&nbsp;it-&gt;size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;it&nbsp;=&nbsp;vec3;<br>
&nbsp;&nbsp;&nbsp;&nbsp;eit&nbsp;=&nbsp;vec3&nbsp;+&nbsp;veclen3;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(dst,&nbsp;it-&gt;data(),&nbsp;it-&gt;size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst&nbsp;+=&nbsp;it-&gt;size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;crow_transport(pack,&nbsp;async);<br>
}<br>
<br>
void&nbsp;crow::return_to_tower(crow::packet&nbsp;*pack,&nbsp;uint8_t&nbsp;sts)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.sended_to_gate&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;ingate&nbsp;!=&nbsp;NULL)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//Пакет&nbsp;был&nbsp;отправлен,&nbsp;и&nbsp;он&nbsp;нездешний.&nbsp;Уничтожить.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//Пакет&nbsp;здешний.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sts&nbsp;!=&nbsp;CROW_SENDED&nbsp;||&nbsp;pack-&gt;quality()&nbsp;==&nbsp;CROW_WITHOUT_ACK)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::tower_release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;add_to_outters_list(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow_undelivered(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.undelivered&nbsp;=&nbsp;1;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(crow::undelivered_handler)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_undelivered_handler&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::undelivered_handler(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_undelivered_handler&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(CROW_NODE_PROTOCOL&nbsp;==&nbsp;pack-&gt;type())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_undelivered_handler&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::node_protocol.undelivered(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_undelivered_handler&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
#ifdef&nbsp;CROW_PUBSUB_PROTOCOL_SUPPORTED<br>
&nbsp;&nbsp;&nbsp;&nbsp;else&nbsp;if&nbsp;(CROW_PUBSUB_PROTOCOL&nbsp;==&nbsp;pack-&gt;type())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_undelivered_handler&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::pubsub_protocol.undelivered(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_in_undelivered_handler&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
#endif<br>
}<br>
<br>
static&nbsp;inline&nbsp;void&nbsp;crow_onestep_send_stage()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(dlist_empty(&amp;crow_travelled))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack&nbsp;=&nbsp;dlist_first_entry(&amp;crow_travelled,&nbsp;crow::packet,&nbsp;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del_init(&amp;pack-&gt;lnk);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow_do_travel(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow_onestep_outers_stage()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*n;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;curtime&nbsp;=&nbsp;igris::millis();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(dlist_empty(&amp;crow_outters))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry_safe(pack,&nbsp;n,&nbsp;&amp;crow_outters,&nbsp;lnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assert(pack-&gt;u.f.released_by_tower&nbsp;==&nbsp;0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(curtime&nbsp;-&nbsp;pack-&gt;last_request_time&nbsp;&gt;=&nbsp;pack-&gt;ackquant())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del_init(&amp;pack-&gt;lnk);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;_ackcount&nbsp;!=&nbsp;0xFFFF)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--pack-&gt;_ackcount;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;_ackcount&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow_undelivered(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::tower_release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::travel(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow_onestep_incoming_stage()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*n;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;curtime&nbsp;=&nbsp;igris::millis();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(dlist_empty(&amp;crow_incoming))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry_safe(pack,&nbsp;n,&nbsp;&amp;crow_incoming,&nbsp;lnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assert(pack-&gt;u.f.released_by_tower&nbsp;==&nbsp;0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(curtime&nbsp;-&nbsp;pack-&gt;last_request_time&nbsp;&gt;=&nbsp;pack-&gt;ackquant())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del_init(&amp;pack-&gt;lnk);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;_ackcount&nbsp;!=&nbsp;0xFFFF)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--pack-&gt;_ackcount;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;_ackcount&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;u.f.undelivered&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_move_sorted(pack,&nbsp;&amp;crow_incoming,&nbsp;lnk,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow_time_comparator);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;last_request_time&nbsp;=&nbsp;curtime;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow_send_ack(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow_onestep_keepalive_stage()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::keepalive_timer_manager.exec(igris::millis());<br>
}<br>
<br>
void&nbsp;crow::onestep()<br>
{<br>
#ifndef&nbsp;CROW_USE_ASYNCIO<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::gateway&nbsp;*gate;<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry(gate,&nbsp;&amp;crow::gateway_list,&nbsp;lnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate-&gt;nblock_onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
#endif<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow_onestep_send_stage();<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow_onestep_keepalive_stage();<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow_onestep_outers_stage();<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow_onestep_incoming_stage();<br>
}<br>
<br>
int&nbsp;crow::incomming_stage_count()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;dlist_size(&amp;crow_incoming);<br>
}<br>
int&nbsp;crow::outers_stage_count()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;dlist_size(&amp;crow_outters);<br>
}<br>
<br>
bool&nbsp;crow::has_untravelled()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;ret&nbsp;=&nbsp;!(dlist_empty(&amp;crow_travelled)&nbsp;&amp;&amp;&nbsp;dlist_empty(&amp;crow_outters)&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_empty(&amp;crow_incoming));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ret;<br>
}<br>
<br>
bool&nbsp;crow::has_untravelled_now()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;ret&nbsp;=&nbsp;!dlist_empty(&amp;crow_travelled);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ret;<br>
}<br>
<br>
void&nbsp;crow::finish()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::gateway&nbsp;*gate;<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_for_each_entry(gate,&nbsp;&amp;crow::gateway_list,&nbsp;lnk)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate-&gt;finish();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
bool&nbsp;crow::fully_empty()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;ret&nbsp;=&nbsp;dlist_empty(&amp;crow_travelled)&nbsp;&amp;&amp;&nbsp;dlist_empty(&amp;crow_incoming)&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_empty(&amp;crow_outters);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ret;<br>
}<br>
<br>
int64_t&nbsp;crow::get_minimal_timeout()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;TODO&nbsp;:&nbsp;Ошибки&nbsp;в&nbsp;учёте&nbsp;переходов&nbsp;через&nbsp;uint16_t<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;int64_t&nbsp;result;<br>
&nbsp;&nbsp;&nbsp;&nbsp;int64_t&nbsp;mininterval&nbsp;=&nbsp;std::numeric_limits&lt;int64_t&gt;::max();<br>
&nbsp;&nbsp;&nbsp;&nbsp;int64_t&nbsp;curtime&nbsp;=&nbsp;igris::millis();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;update_candidate&nbsp;=&nbsp;[&amp;](int64_t&nbsp;candidate)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(mininterval&nbsp;&gt;&nbsp;candidate)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mininterval&nbsp;=&nbsp;candidate;<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!keepalive_timer_manager.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;update_candidate(keepalive_timer_manager.minimal_interval(curtime));<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!dlist_empty(&amp;crow_incoming))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*i&nbsp;=&nbsp;dlist_first_entry(&amp;crow_incoming,&nbsp;crow::packet,&nbsp;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;update_candidate(i-&gt;last_request_time&nbsp;+&nbsp;i-&gt;ackquant()&nbsp;-&nbsp;curtime);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!dlist_empty(&amp;crow_outters))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*o&nbsp;=&nbsp;dlist_first_entry(&amp;crow_outters,&nbsp;crow::packet,&nbsp;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;update_candidate(o-&gt;last_request_time&nbsp;+&nbsp;o-&gt;ackquant()&nbsp;-&nbsp;curtime);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(mininterval&nbsp;==&nbsp;std::numeric_limits&lt;int64_t&gt;::max())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;else&nbsp;if&nbsp;(mininterval&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;mininterval;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
