<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/integration/large_reply_service.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**<br>
&nbsp;*&nbsp;@file&nbsp;large_reply_service.cpp<br>
&nbsp;*&nbsp;@brief&nbsp;Test&nbsp;service&nbsp;that&nbsp;replies&nbsp;with&nbsp;large&nbsp;messages&nbsp;(chunked)<br>
&nbsp;*<br>
&nbsp;*&nbsp;Usage:&nbsp;large_reply_service&nbsp;[options]<br>
&nbsp;*&nbsp;&nbsp;&nbsp;--udp&nbsp;PORT&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UDP&nbsp;port&nbsp;(default:&nbsp;0&nbsp;=&nbsp;system&nbsp;assigned)<br>
&nbsp;*&nbsp;&nbsp;&nbsp;--chunk&nbsp;SIZE&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Chunk&nbsp;size&nbsp;for&nbsp;replies&nbsp;(default:&nbsp;64)<br>
&nbsp;*&nbsp;&nbsp;&nbsp;--crowker&nbsp;ADDR&nbsp;&nbsp;&nbsp;Crowker&nbsp;address&nbsp;(default:&nbsp;.12.127.0.0.1:10009)<br>
&nbsp;*&nbsp;&nbsp;&nbsp;--theme&nbsp;NAME&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Service&nbsp;theme&nbsp;(default:&nbsp;&quot;test_service&quot;)<br>
&nbsp;*&nbsp;&nbsp;&nbsp;--debug&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Enable&nbsp;debug&nbsp;output<br>
&nbsp;*/<br>
<br>
#include&nbsp;&lt;crow/address.h&gt;<br>
#include&nbsp;&lt;crow/gates/udpgate.h&gt;<br>
#include&nbsp;&lt;crow/nodes/service_node.h&gt;<br>
#include&nbsp;&lt;crow/tower.h&gt;<br>
#include&nbsp;&lt;crow/tower_cls.h&gt;<br>
<br>
#include&nbsp;&lt;getopt.h&gt;<br>
#include&nbsp;&lt;signal.h&gt;<br>
#include&nbsp;&lt;cstdio&gt;<br>
#include&nbsp;&lt;cstdlib&gt;<br>
#include&nbsp;&lt;cstring&gt;<br>
#include&nbsp;&lt;string&gt;<br>
<br>
bool&nbsp;debug_mode&nbsp;=&nbsp;false;<br>
int&nbsp;udpport&nbsp;=&nbsp;0;<br>
size_t&nbsp;chunk_size&nbsp;=&nbsp;64;<br>
std::string&nbsp;crowker_addr_str&nbsp;=&nbsp;&quot;.12.127.0.0.1:10009&quot;;<br>
std::string&nbsp;theme&nbsp;=&nbsp;&quot;test_service&quot;;<br>
<br>
crow::Tower&nbsp;tower;<br>
crow::service_node&nbsp;service;<br>
<br>
//&nbsp;Generate&nbsp;test&nbsp;response&nbsp;of&nbsp;specified&nbsp;size<br>
std::string&nbsp;generate_response(size_t&nbsp;size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;data;<br>
&nbsp;&nbsp;&nbsp;&nbsp;data.reserve(size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(size_t&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;size;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data.push_back(static_cast&lt;char&gt;('A'&nbsp;+&nbsp;(i&nbsp;%&nbsp;26)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;data;<br>
}<br>
<br>
void&nbsp;service_handler(char&nbsp;*data,&nbsp;int&nbsp;len,&nbsp;crow::service_node&nbsp;&amp;srv)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;request(data,&nbsp;len);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(debug_mode)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fprintf(stderr,&nbsp;&quot;[service]&nbsp;received&nbsp;request:&nbsp;'%s'&nbsp;(len=%d)\n&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;request.c_str(),&nbsp;len);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Parse&nbsp;request:&nbsp;expecting&nbsp;&quot;SIZE&quot;&nbsp;or&nbsp;&quot;SIZE:PATTERN&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Trim&nbsp;whitespace/newlines<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(!request.empty()&nbsp;&amp;&amp;&nbsp;(request.back()&nbsp;==&nbsp;'\n'&nbsp;||&nbsp;request.back()&nbsp;==&nbsp;'\r'&nbsp;||&nbsp;request.back()&nbsp;==&nbsp;'&nbsp;'))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;request.pop_back();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;response_size&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;pattern&nbsp;=&nbsp;'A';<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(request.find(':')&nbsp;!=&nbsp;std::string::npos)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;FORMAT:&nbsp;SIZE:PATTERN<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;pos&nbsp;=&nbsp;request.find(':');<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;response_size&nbsp;=&nbsp;std::stoul(request.substr(0,&nbsp;pos));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pos&nbsp;+&nbsp;1&nbsp;&lt;&nbsp;request.size())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pattern&nbsp;=&nbsp;request[pos&nbsp;+&nbsp;1];<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;FORMAT:&nbsp;SIZE<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;response_size&nbsp;=&nbsp;std::stoul(request);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Generate&nbsp;response<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;response;<br>
&nbsp;&nbsp;&nbsp;&nbsp;response.reserve(response_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(size_t&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;response_size;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;response.push_back(static_cast&lt;char&gt;(pattern&nbsp;+&nbsp;(i&nbsp;%&nbsp;26)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(debug_mode)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fprintf(stderr,&nbsp;&quot;[service]&nbsp;sending&nbsp;response:&nbsp;size=%zu,&nbsp;chunk_size=%zu\n&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;response.size(),&nbsp;srv.chunk_size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;srv.reply(response.data(),&nbsp;response.size());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(debug_mode)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fprintf(stderr,&nbsp;&quot;[service]&nbsp;reply&nbsp;sent\n&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;signal_handler(int)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::stop_spin(false);<br>
}<br>
<br>
void&nbsp;print_help()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;printf(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Usage:&nbsp;large_reply_service&nbsp;[OPTIONS]\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Test&nbsp;service&nbsp;that&nbsp;replies&nbsp;with&nbsp;large&nbsp;chunked&nbsp;messages.\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Options:\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-u,&nbsp;--udp&nbsp;PORT&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UDP&nbsp;port&nbsp;(default:&nbsp;0&nbsp;=&nbsp;system&nbsp;assigned)\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-c,&nbsp;--chunk&nbsp;SIZE&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Chunk&nbsp;size&nbsp;for&nbsp;replies&nbsp;(default:&nbsp;64)\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-a,&nbsp;--crowker&nbsp;ADDR&nbsp;&nbsp;&nbsp;Crowker&nbsp;address&nbsp;(default:&nbsp;.12.127.0.0.1:10009)\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-t,&nbsp;--theme&nbsp;NAME&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Service&nbsp;theme&nbsp;(default:&nbsp;test_service)\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-d,&nbsp;--debug&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Enable&nbsp;debug&nbsp;output\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-h,&nbsp;--help&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Show&nbsp;this&nbsp;help\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Request&nbsp;format:\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;SIZE&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;respond&nbsp;with&nbsp;SIZE&nbsp;bytes&nbsp;(pattern&nbsp;A-Z&nbsp;repeating)\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;SIZE:CHAR&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;respond&nbsp;with&nbsp;SIZE&nbsp;bytes&nbsp;starting&nbsp;from&nbsp;CHAR\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Example:\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;large_reply_service&nbsp;--chunk&nbsp;100&nbsp;--theme&nbsp;myservice\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;#&nbsp;Then&nbsp;from&nbsp;ctrans:\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;echo&nbsp;'500'&nbsp;|&nbsp;ctrans&nbsp;--request&nbsp;myservice\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;);<br>
}<br>
<br>
int&nbsp;main(int&nbsp;argc,&nbsp;char&nbsp;*argv[])<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;struct&nbsp;option&nbsp;long_options[]&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;help&quot;,&nbsp;no_argument,&nbsp;NULL,&nbsp;'h'},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;udp&quot;,&nbsp;required_argument,&nbsp;NULL,&nbsp;'u'},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;chunk&quot;,&nbsp;required_argument,&nbsp;NULL,&nbsp;'c'},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;crowker&quot;,&nbsp;required_argument,&nbsp;NULL,&nbsp;'a'},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;theme&quot;,&nbsp;required_argument,&nbsp;NULL,&nbsp;'t'},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;debug&quot;,&nbsp;no_argument,&nbsp;NULL,&nbsp;'d'},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{NULL,&nbsp;0,&nbsp;NULL,&nbsp;0}<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;opt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;((opt&nbsp;=&nbsp;getopt_long(argc,&nbsp;argv,&nbsp;&quot;hu:c:a:t:d&quot;,&nbsp;long_options,&nbsp;NULL))&nbsp;!=&nbsp;-1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(opt)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;'h':<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print_help();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;'u':<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;udpport&nbsp;=&nbsp;atoi(optarg);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;'c':<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chunk_size&nbsp;=&nbsp;std::stoul(optarg);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;'a':<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crowker_addr_str&nbsp;=&nbsp;optarg;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;'t':<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;theme&nbsp;=&nbsp;optarg;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;'d':<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;debug_mode&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.enable_diagnostic();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.set_diagnostic_label(&quot;service:&quot;&nbsp;+&nbsp;std::to_string(getpid()));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Create&nbsp;UDP&nbsp;gate<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;udpgate&nbsp;=&nbsp;crow::create_udpgate_safe(12,&nbsp;udpport);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!udpgate&nbsp;||&nbsp;!udpgate-&gt;opened())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;udpgate&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;udpgate-&gt;bind(tower,&nbsp;12);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Parse&nbsp;crowker&nbsp;address<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;crowker_addr&nbsp;=&nbsp;crow::address(crowker_addr_str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(crowker_addr.size()&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fprintf(stderr,&nbsp;&quot;Invalid&nbsp;crowker&nbsp;address:&nbsp;%s\n&quot;,&nbsp;crowker_addr_str.c_str());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Setup&nbsp;service&nbsp;node<br>
&nbsp;&nbsp;&nbsp;&nbsp;service.bind(tower,&nbsp;50);&nbsp;&nbsp;//&nbsp;arbitrary&nbsp;node&nbsp;id<br>
&nbsp;&nbsp;&nbsp;&nbsp;service.set_chunk_size(chunk_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;service.set_handle(service_handler);<br>
&nbsp;&nbsp;&nbsp;&nbsp;service.init_subscribe(crowker_addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CROWKER_SERVICE_BROCKER_NODE_NO,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;theme.c_str(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2,&nbsp;&nbsp;&nbsp;//&nbsp;qos<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;50,&nbsp;&nbsp;//&nbsp;ackquant<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2,&nbsp;&nbsp;&nbsp;//&nbsp;rqos<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;50);&nbsp;//&nbsp;rackquant<br>
&nbsp;&nbsp;&nbsp;&nbsp;service.install_keepalive(60000);&nbsp;&nbsp;//&nbsp;very&nbsp;long&nbsp;keepalive&nbsp;to&nbsp;avoid&nbsp;re-subscribe&nbsp;during&nbsp;tests<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(debug_mode)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fprintf(stderr,&nbsp;&quot;[service]&nbsp;started:&nbsp;theme='%s',&nbsp;chunk_size=%zu,&nbsp;crowker='%s'\n&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;theme.c_str(),&nbsp;chunk_size,&nbsp;crowker_addr_str.c_str());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(&quot;Service&nbsp;ready:&nbsp;theme='%s',&nbsp;chunk_size=%zu\n&quot;,&nbsp;theme.c_str(),&nbsp;chunk_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;signal(SIGINT,&nbsp;signal_handler);<br>
&nbsp;&nbsp;&nbsp;&nbsp;signal(SIGTERM,&nbsp;signal_handler);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::spin_with_select(tower);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
