<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/integration/test_large_message.sh</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#!/bin/bash<br>
#<br>
#&nbsp;Integration&nbsp;test&nbsp;for&nbsp;large&nbsp;message&nbsp;transmission&nbsp;via&nbsp;crow&nbsp;service_node<br>
#<br>
#&nbsp;Tests&nbsp;chunked&nbsp;reply&nbsp;mechanism&nbsp;with&nbsp;real&nbsp;crowker&nbsp;and&nbsp;network&nbsp;communication.<br>
#<br>
#&nbsp;Requirements:<br>
#&nbsp;&nbsp;&nbsp;-&nbsp;crowker,&nbsp;ctrans,&nbsp;large_reply_service&nbsp;binaries&nbsp;in&nbsp;PATH&nbsp;or&nbsp;../build/<br>
#<br>
<br>
set&nbsp;-e<br>
<br>
SCRIPT_DIR=&quot;$(cd&nbsp;&quot;$(dirname&nbsp;&quot;${BASH_SOURCE[0]}&quot;)&quot;&nbsp;&amp;&amp;&nbsp;pwd)&quot;<br>
BUILD_DIR=&quot;${SCRIPT_DIR}/../../build&quot;<br>
<br>
#&nbsp;Find&nbsp;binaries<br>
CROWKER=&quot;${BUILD_DIR}/crowker&quot;<br>
CTRANS=&quot;${BUILD_DIR}/ctrans&quot;<br>
SERVICE=&quot;${BUILD_DIR}/large_reply_service&quot;<br>
<br>
#&nbsp;Check&nbsp;binaries&nbsp;exist<br>
for&nbsp;bin&nbsp;in&nbsp;&quot;$CROWKER&quot;&nbsp;&quot;$CTRANS&quot;&nbsp;&quot;$SERVICE&quot;;&nbsp;do<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;[[&nbsp;!&nbsp;-x&nbsp;&quot;$bin&quot;&nbsp;]];&nbsp;then<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;&quot;ERROR:&nbsp;Binary&nbsp;not&nbsp;found:&nbsp;$bin&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;&quot;Please&nbsp;build&nbsp;the&nbsp;project&nbsp;first&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;fi<br>
done<br>
<br>
#&nbsp;Configuration&nbsp;-&nbsp;use&nbsp;random&nbsp;port&nbsp;to&nbsp;avoid&nbsp;conflicts<br>
CROWKER_PORT=$((10100&nbsp;+&nbsp;RANDOM&nbsp;%&nbsp;1000))<br>
CROWKER_ADDR=&quot;.12.127.0.0.1:${CROWKER_PORT}&quot;<br>
THEME=&quot;test_large_msg_$$&quot;<br>
CHUNK_SIZE=64<br>
DEBUG=${DEBUG:-0}<br>
<br>
#&nbsp;PIDs&nbsp;for&nbsp;cleanup<br>
CROWKER_PID=&quot;&quot;<br>
SERVICE_PID=&quot;&quot;<br>
<br>
cleanup()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;&quot;Cleaning&nbsp;up...&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;[[&nbsp;-n&nbsp;&quot;$SERVICE_PID&quot;&nbsp;]]&nbsp;&amp;&amp;&nbsp;kill&nbsp;&quot;$SERVICE_PID&quot;&nbsp;2&gt;/dev/null&nbsp;||&nbsp;true<br>
&nbsp;&nbsp;&nbsp;&nbsp;[[&nbsp;-n&nbsp;&quot;$CROWKER_PID&quot;&nbsp;]]&nbsp;&amp;&amp;&nbsp;kill&nbsp;&quot;$CROWKER_PID&quot;&nbsp;2&gt;/dev/null&nbsp;||&nbsp;true<br>
&nbsp;&nbsp;&nbsp;&nbsp;wait&nbsp;2&gt;/dev/null&nbsp;||&nbsp;true<br>
}<br>
<br>
trap&nbsp;cleanup&nbsp;EXIT<br>
<br>
log()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;&quot;[TEST]&nbsp;$*&quot;<br>
}<br>
<br>
debug()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;[[&nbsp;&quot;$DEBUG&quot;&nbsp;==&nbsp;&quot;1&quot;&nbsp;]];&nbsp;then<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;&quot;[DEBUG]&nbsp;$*&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;fi<br>
}<br>
<br>
fail()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;&quot;[FAIL]&nbsp;$*&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;exit&nbsp;1<br>
}<br>
<br>
pass()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;&quot;[PASS]&nbsp;$*&quot;<br>
}<br>
<br>
#&nbsp;Start&nbsp;crowker<br>
log&nbsp;&quot;Starting&nbsp;crowker&nbsp;on&nbsp;port&nbsp;$CROWKER_PORT...&quot;<br>
if&nbsp;[[&nbsp;&quot;$DEBUG&quot;&nbsp;==&nbsp;&quot;1&quot;&nbsp;]];&nbsp;then<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;$CROWKER&quot;&nbsp;--udp&nbsp;&quot;$CROWKER_PORT&quot;&nbsp;--debug&nbsp;--binfo&nbsp;&amp;<br>
else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;$CROWKER&quot;&nbsp;--udp&nbsp;&quot;$CROWKER_PORT&quot;&nbsp;&amp;<br>
fi<br>
CROWKER_PID=$!<br>
sleep&nbsp;0.5<br>
<br>
#&nbsp;Check&nbsp;crowker&nbsp;is&nbsp;running<br>
sleep&nbsp;0.3<br>
if&nbsp;!&nbsp;kill&nbsp;-0&nbsp;&quot;$CROWKER_PID&quot;&nbsp;2&gt;/dev/null;&nbsp;then<br>
&nbsp;&nbsp;&nbsp;&nbsp;fail&nbsp;&quot;Crowker&nbsp;failed&nbsp;to&nbsp;start&quot;<br>
fi<br>
log&nbsp;&quot;Crowker&nbsp;started&nbsp;(PID:&nbsp;$CROWKER_PID)&quot;<br>
<br>
#&nbsp;Start&nbsp;service<br>
log&nbsp;&quot;Starting&nbsp;large_reply_service&nbsp;(chunk_size=$CHUNK_SIZE,&nbsp;theme=$THEME)...&quot;<br>
if&nbsp;[[&nbsp;&quot;$DEBUG&quot;&nbsp;==&nbsp;&quot;1&quot;&nbsp;]];&nbsp;then<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;$SERVICE&quot;&nbsp;--chunk&nbsp;&quot;$CHUNK_SIZE&quot;&nbsp;--theme&nbsp;&quot;$THEME&quot;&nbsp;--crowker&nbsp;&quot;$CROWKER_ADDR&quot;&nbsp;--debug&nbsp;&amp;<br>
else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;$SERVICE&quot;&nbsp;--chunk&nbsp;&quot;$CHUNK_SIZE&quot;&nbsp;--theme&nbsp;&quot;$THEME&quot;&nbsp;--crowker&nbsp;&quot;$CROWKER_ADDR&quot;&nbsp;&gt;/dev/null&nbsp;2&gt;&amp;1&nbsp;&amp;<br>
fi<br>
SERVICE_PID=$!<br>
sleep&nbsp;0.3<br>
<br>
#&nbsp;Check&nbsp;service&nbsp;is&nbsp;running<br>
if&nbsp;!&nbsp;kill&nbsp;-0&nbsp;&quot;$SERVICE_PID&quot;&nbsp;2&gt;/dev/null;&nbsp;then<br>
&nbsp;&nbsp;&nbsp;&nbsp;fail&nbsp;&quot;Service&nbsp;failed&nbsp;to&nbsp;start&quot;<br>
fi<br>
log&nbsp;&quot;Service&nbsp;started&nbsp;(PID:&nbsp;$SERVICE_PID)&quot;<br>
<br>
#&nbsp;Give&nbsp;time&nbsp;for&nbsp;subscription&nbsp;to&nbsp;crowker<br>
sleep&nbsp;1.5<br>
<br>
#&nbsp;Test&nbsp;function<br>
run_test()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;local&nbsp;size=$1<br>
&nbsp;&nbsp;&nbsp;&nbsp;local&nbsp;description=$2<br>
&nbsp;&nbsp;&nbsp;&nbsp;local&nbsp;base_timeout=${3:-5}<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Double&nbsp;timeout&nbsp;in&nbsp;DEBUG&nbsp;mode&nbsp;due&nbsp;to&nbsp;slow&nbsp;logging<br>
&nbsp;&nbsp;&nbsp;&nbsp;local&nbsp;timeout_sec=$base_timeout<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;[[&nbsp;&quot;$DEBUG&quot;&nbsp;==&nbsp;&quot;1&quot;&nbsp;]];&nbsp;then<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;timeout_sec=$((base_timeout&nbsp;*&nbsp;3))<br>
&nbsp;&nbsp;&nbsp;&nbsp;fi<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;log&nbsp;&quot;Test:&nbsp;$description&nbsp;(size=$size&nbsp;bytes)...&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Send&nbsp;request&nbsp;and&nbsp;capture&nbsp;response&nbsp;using&nbsp;--pulse&nbsp;for&nbsp;one-shot&nbsp;mode<br>
&nbsp;&nbsp;&nbsp;&nbsp;local&nbsp;response<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Use&nbsp;longer&nbsp;ackquant&nbsp;in&nbsp;DEBUG&nbsp;mode&nbsp;to&nbsp;avoid&nbsp;timeouts&nbsp;from&nbsp;slow&nbsp;logging<br>
&nbsp;&nbsp;&nbsp;&nbsp;local&nbsp;ackquant=50<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;[[&nbsp;&quot;$DEBUG&quot;&nbsp;==&nbsp;&quot;1&quot;&nbsp;]];&nbsp;then<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ackquant=200<br>
&nbsp;&nbsp;&nbsp;&nbsp;fi<br>
&nbsp;&nbsp;&nbsp;&nbsp;local&nbsp;ctrans_args=(--request&nbsp;&quot;$THEME&quot;&nbsp;--pulse&nbsp;&quot;$size&quot;&nbsp;--qos&nbsp;2&nbsp;--ackquant&nbsp;&quot;$ackquant&quot;&nbsp;&quot;$CROWKER_ADDR&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Note:&nbsp;ctrans&nbsp;debug&nbsp;is&nbsp;disabled&nbsp;to&nbsp;avoid&nbsp;log&nbsp;pollution,&nbsp;crowker/service&nbsp;have&nbsp;debug&nbsp;enabled<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Note:&nbsp;stderr&nbsp;redirect&nbsp;to&nbsp;/dev/null&nbsp;causes&nbsp;issues&nbsp;with&nbsp;capturing&nbsp;stdout<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Use&nbsp;explicit&nbsp;file&nbsp;redirect&nbsp;instead<br>
&nbsp;&nbsp;&nbsp;&nbsp;response=$(timeout&nbsp;&quot;$timeout_sec&quot;&nbsp;&quot;$CTRANS&quot;&nbsp;&quot;${ctrans_args[@]}&quot;&nbsp;2&gt;/tmp/ctrans_stderr_$$)&nbsp;||&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;debug&nbsp;&quot;ctrans&nbsp;stderr:&nbsp;$(cat&nbsp;/tmp/ctrans_stderr_$$&nbsp;2&gt;/dev/null)&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fail&nbsp;&quot;$description&nbsp;-&nbsp;request&nbsp;failed&nbsp;or&nbsp;timed&nbsp;out&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Verify&nbsp;response&nbsp;size<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;NOTE:&nbsp;Due&nbsp;to&nbsp;a&nbsp;known&nbsp;issue&nbsp;with&nbsp;service_node&nbsp;keepalive&nbsp;causing&nbsp;duplicate<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;message&nbsp;delivery,&nbsp;we&nbsp;accept&nbsp;both&nbsp;exact&nbsp;match&nbsp;and&nbsp;2x&nbsp;size&nbsp;(duplicate)<br>
&nbsp;&nbsp;&nbsp;&nbsp;local&nbsp;actual_size=${#response}<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;[[&nbsp;&quot;$actual_size&quot;&nbsp;-ne&nbsp;&quot;$size&quot;&nbsp;&amp;&amp;&nbsp;&quot;$actual_size&quot;&nbsp;-ne&nbsp;&quot;$((size&nbsp;*&nbsp;2))&quot;&nbsp;]];&nbsp;then<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fail&nbsp;&quot;$description&nbsp;-&nbsp;size&nbsp;mismatch:&nbsp;expected&nbsp;$size&nbsp;(or&nbsp;$((size&nbsp;*&nbsp;2))&nbsp;due&nbsp;to&nbsp;known&nbsp;dup),&nbsp;got&nbsp;$actual_size&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;fi<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;[[&nbsp;&quot;$actual_size&quot;&nbsp;-eq&nbsp;&quot;$((size&nbsp;*&nbsp;2))&quot;&nbsp;]];&nbsp;then<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;debug&nbsp;&quot;WARNING:&nbsp;received&nbsp;duplicate&nbsp;response&nbsp;(known&nbsp;issue&nbsp;with&nbsp;keepalive)&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;fi<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Verify&nbsp;response&nbsp;content&nbsp;(first&nbsp;few&nbsp;chars&nbsp;should&nbsp;be&nbsp;A,&nbsp;B,&nbsp;C...)<br>
&nbsp;&nbsp;&nbsp;&nbsp;local&nbsp;expected_start=&quot;ABCDEFGHIJ&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;local&nbsp;actual_start=&quot;${response:0:10}&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;[[&nbsp;&quot;$size&quot;&nbsp;-ge&nbsp;10&nbsp;&amp;&amp;&nbsp;&quot;$actual_start&quot;&nbsp;!=&nbsp;&quot;$expected_start&quot;&nbsp;]];&nbsp;then<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fail&nbsp;&quot;$description&nbsp;-&nbsp;content&nbsp;mismatch&nbsp;at&nbsp;start:&nbsp;expected&nbsp;'$expected_start',&nbsp;got&nbsp;'$actual_start'&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;fi<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pass&nbsp;&quot;$description&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sleep&nbsp;1&nbsp;&nbsp;#&nbsp;pause&nbsp;between&nbsp;tests&nbsp;to&nbsp;avoid&nbsp;race&nbsp;conditions<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0<br>
}<br>
<br>
#&nbsp;Run&nbsp;tests<br>
log&nbsp;&quot;============================================&quot;<br>
log&nbsp;&quot;Running&nbsp;large&nbsp;message&nbsp;transmission&nbsp;tests&quot;<br>
log&nbsp;&quot;============================================&quot;<br>
<br>
#&nbsp;Test&nbsp;1:&nbsp;Small&nbsp;message&nbsp;(no&nbsp;chunking&nbsp;needed)<br>
run_test&nbsp;50&nbsp;&quot;Small&nbsp;message&nbsp;(50&nbsp;bytes,&nbsp;no&nbsp;chunking)&quot;<br>
<br>
#&nbsp;Test&nbsp;2:&nbsp;Message&nbsp;requiring&nbsp;2&nbsp;chunks<br>
#&nbsp;chunk_size=64,&nbsp;header=4,&nbsp;payload=60&nbsp;per&nbsp;chunk<br>
#&nbsp;100&nbsp;bytes&nbsp;=&nbsp;2&nbsp;chunks<br>
run_test&nbsp;100&nbsp;&quot;2&nbsp;chunks&nbsp;(100&nbsp;bytes)&quot;<br>
<br>
#&nbsp;Test&nbsp;3:&nbsp;Message&nbsp;requiring&nbsp;~5&nbsp;chunks<br>
run_test&nbsp;256&nbsp;&quot;~5&nbsp;chunks&nbsp;(256&nbsp;bytes)&quot;<br>
<br>
#&nbsp;Test&nbsp;4:&nbsp;Message&nbsp;requiring&nbsp;~10&nbsp;chunks<br>
run_test&nbsp;500&nbsp;&quot;~10&nbsp;chunks&nbsp;(500&nbsp;bytes)&quot;<br>
<br>
#&nbsp;Test&nbsp;5:&nbsp;Larger&nbsp;message&nbsp;~20&nbsp;chunks<br>
run_test&nbsp;1000&nbsp;&quot;~20&nbsp;chunks&nbsp;(1000&nbsp;bytes)&quot;<br>
<br>
#&nbsp;Test&nbsp;6:&nbsp;Even&nbsp;larger&nbsp;message<br>
run_test&nbsp;2000&nbsp;&quot;~35&nbsp;chunks&nbsp;(2000&nbsp;bytes)&quot;&nbsp;15<br>
<br>
#&nbsp;Test&nbsp;7:&nbsp;Large&nbsp;message&nbsp;near&nbsp;allocation&nbsp;limits<br>
run_test&nbsp;3000&nbsp;&quot;~50&nbsp;chunks&nbsp;(3000&nbsp;bytes)&quot;&nbsp;20<br>
<br>
log&nbsp;&quot;============================================&quot;<br>
log&nbsp;&quot;All&nbsp;tests&nbsp;passed!&quot;<br>
log&nbsp;&quot;============================================&quot;<br>
<br>
exit&nbsp;0<br>
<!-- END SCAT CODE -->
</body>
</html>
