/**
	@file
*/

#ifndef CROW_DEFS_H
#define CROW_DEFS_H

#define G1_UDPGATE 12
#define CROW_UDPGATE_NO 12
#define CROW_UDPGATE 12

#define G1_ACK_TYPE 0
#define G1_ACK21_TYPE 1
#define G1_ACK22_TYPE 2

#define CROW_NODE_PROTOCOL 3
#define CROW_PUBSUB_PROTOCOL 4
#define CROW_QUERY_PROTOCOL 5
#define CROW_NETKEEP_PROTOCOL 6

//#define DEFAULT_ACKQUANT 200

#endif