<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/gates/serial_gstuff.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/asyncio.h&gt;<br>
#include&nbsp;&lt;crow/gates/serial_gstuff.h&gt;<br>
#include&nbsp;&lt;crow/gateway.h&gt;<br>
#include&nbsp;&lt;crow/tower.h&gt;<br>
#include&nbsp;&lt;crow/warn.h&gt;<br>
#include&nbsp;&lt;fcntl.h&gt;<br>
#include&nbsp;&lt;igris/protocols/gstuff.h&gt;<br>
#include&nbsp;&lt;igris/util/bug.h&gt;<br>
#include&nbsp;&lt;nos/io/serial_port.h&gt;<br>
#include&nbsp;&lt;stdbool.h&gt;<br>
#include&nbsp;&lt;stdint.h&gt;<br>
#include&nbsp;&lt;stdio.h&gt;<br>
#include&nbsp;&lt;sys/cdefs.h&gt;<br>
#include&nbsp;&lt;termios.h&gt;<br>
#include&nbsp;&lt;unistd.h&gt;<br>
<br>
crow::serial_gstuff::serial_gstuff(gstuff_context&nbsp;gctx)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;gctx(gctx),&nbsp;recver(gctx)<br>
{<br>
}<br>
<br>
void&nbsp;crow::serial_gstuff::newline_handler()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*block&nbsp;=&nbsp;rpack;<br>
&nbsp;&nbsp;&nbsp;&nbsp;rpack&nbsp;=&nbsp;NULL;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;block-&gt;revert_gate(id);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet_initialization(block,&nbsp;this);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::nocontrol_travel(block,&nbsp;false);<br>
}<br>
<br>
void&nbsp;crow::serial_gstuff::send(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;buffer[512];<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;header_v1&nbsp;header&nbsp;=&nbsp;pack-&gt;extract_header_v1();<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;iovec&nbsp;iov[]&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&amp;header,&nbsp;sizeof(header)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize()},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{pack-&gt;dataptr(),&nbsp;pack-&gt;datasize()},<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;size&nbsp;=&nbsp;gstuffing_v(iov,&nbsp;3,&nbsp;buffer,&nbsp;gctx);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;_&nbsp;=&nbsp;write(fd,&nbsp;buffer,&nbsp;size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)_;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::return_to_tower(pack,&nbsp;CROW_SENDED);<br>
}<br>
<br>
void&nbsp;crow::serial_gstuff::read_handler(int)<br>
{<br>
#define&nbsp;GSTUFF_MAXPACK_SIZE&nbsp;512<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;buf[1024];<br>
&nbsp;&nbsp;&nbsp;&nbsp;ssize_t&nbsp;len&nbsp;=&nbsp;read(fd,&nbsp;(uint8_t&nbsp;*)buf,&nbsp;1024);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;len;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;c&nbsp;=&nbsp;buf[i];<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;debug_printhex_uint8(c);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;debug_putchar('\t');<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;debug_putchar(c);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;debug_print_newline();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(rpack&nbsp;==&nbsp;NULL)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rpack&nbsp;=&nbsp;allocate_packet&lt;crow::header_v1&gt;(GSTUFF_MAXPACK_SIZE);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;recver.setbuf(rpack-&gt;header_addr(),&nbsp;GSTUFF_MAXPACK_SIZE);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;ret&nbsp;=&nbsp;recver.newchar(c);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(ret)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;GSTUFF_CRC_ERROR:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::warn(&quot;warn:&nbsp;gstuff&nbsp;crc&nbsp;error&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;GSTUFF_NEWPACKAGE:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;newline_handler();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::serial_gstuff::setup_serial_port(int&nbsp;baud,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;parity,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;databits,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;stopbits)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::serial_port&nbsp;port(fd);<br>
&nbsp;&nbsp;&nbsp;&nbsp;port.setup(baud,&nbsp;parity,&nbsp;databits,&nbsp;stopbits);<br>
}<br>
<br>
void&nbsp;crow::serial_gstuff::finish()&nbsp;{}<br>
<br>
//&nbsp;template&nbsp;&lt;class&nbsp;Header&gt;<br>
crow::serial_gstuff&nbsp;*crow::create_serial_gstuff(const&nbsp;char&nbsp;*path,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;baudrate,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;id,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;debug,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;gstuff_context&amp;&nbsp;gctx)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)baudrate;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*g&nbsp;=&nbsp;new&nbsp;crow::serial_gstuff(gctx);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;g-&gt;debug&nbsp;=&nbsp;debug;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;g-&gt;fd&nbsp;=&nbsp;open(path,&nbsp;O_RDWR&nbsp;|&nbsp;O_NOCTTY);<br>
&nbsp;&nbsp;&nbsp;&nbsp;fcntl(g-&gt;fd,&nbsp;F_SETFL,&nbsp;fcntl(g-&gt;fd,&nbsp;F_GETFL)&nbsp;|&nbsp;O_NONBLOCK);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(g-&gt;fd&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;serial::open&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;g-&gt;rpack&nbsp;=&nbsp;NULL;<br>
&nbsp;&nbsp;&nbsp;&nbsp;g-&gt;bind(id);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::asyncio.add_iotask(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;g-&gt;fd,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SelectType::READ,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris::make_delegate(&amp;serial_gstuff::read_handler,&nbsp;g));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;g;<br>
}<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
crow::serial_gstuff_v0::serial_gstuff_v0(gstuff_context&nbsp;gctx)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;gctx(gctx),&nbsp;recver(gctx)<br>
{<br>
}<br>
<br>
void&nbsp;crow::serial_gstuff_v0::newline_handler()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*block&nbsp;=&nbsp;rpack;<br>
&nbsp;&nbsp;&nbsp;&nbsp;rpack&nbsp;=&nbsp;NULL;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;block-&gt;revert_gate(id);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet_initialization(block,&nbsp;this);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::nocontrol_travel(block,&nbsp;false);<br>
}<br>
<br>
void&nbsp;crow::serial_gstuff_v0::send(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;buffer[512];<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;header_v0&nbsp;header&nbsp;=&nbsp;pack-&gt;extract_header_v0();<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;iovec&nbsp;iov[]&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&amp;header,&nbsp;sizeof(header)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize()},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{pack-&gt;dataptr(),&nbsp;pack-&gt;datasize()},<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;size&nbsp;=&nbsp;gstuffing_v(iov,&nbsp;3,&nbsp;buffer,&nbsp;gctx);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;_&nbsp;=&nbsp;write(fd,&nbsp;buffer,&nbsp;size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)_;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::return_to_tower(pack,&nbsp;CROW_SENDED);<br>
}<br>
<br>
void&nbsp;crow::serial_gstuff_v0::read_handler(int)<br>
{<br>
#define&nbsp;GSTUFF_MAXPACK_SIZE&nbsp;512<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;buf[1024];<br>
&nbsp;&nbsp;&nbsp;&nbsp;ssize_t&nbsp;len&nbsp;=&nbsp;read(fd,&nbsp;(uint8_t&nbsp;*)buf,&nbsp;1024);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;len;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;c&nbsp;=&nbsp;buf[i];<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;debug_printhex_uint8(c);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;debug_putchar('\t');<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;debug_putchar(c);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;debug_print_newline();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(rpack&nbsp;==&nbsp;NULL)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rpack&nbsp;=&nbsp;allocate_packet&lt;crow::header_v0&gt;(GSTUFF_MAXPACK_SIZE);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;recver.setbuf(rpack-&gt;header_addr(),&nbsp;GSTUFF_MAXPACK_SIZE);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;ret&nbsp;=&nbsp;recver.newchar(c);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(ret)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;GSTUFF_CRC_ERROR:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::warn(&quot;warn:&nbsp;gstuff&nbsp;crc&nbsp;error&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;GSTUFF_NEWPACKAGE:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;newline_handler();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::serial_gstuff_v0::setup_serial_port(int&nbsp;baud,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;parity,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;databits,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;stopbits)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::serial_port&nbsp;port(fd);<br>
&nbsp;&nbsp;&nbsp;&nbsp;port.setup(baud,&nbsp;parity,&nbsp;databits,&nbsp;stopbits);<br>
}<br>
<br>
void&nbsp;crow::serial_gstuff_v0::finish()&nbsp;{}<br>
<br>
//&nbsp;template&nbsp;&lt;class&nbsp;Header&gt;<br>
crow::serial_gstuff_v0&nbsp;*crow::create_serial_gstuff_v0(const&nbsp;char&nbsp;*path,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;baudrate,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;id,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;debug,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;gstuff_context&amp;&nbsp;gctx)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)baudrate;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*g&nbsp;=&nbsp;new&nbsp;crow::serial_gstuff_v0(gctx);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;g-&gt;debug&nbsp;=&nbsp;debug;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;g-&gt;fd&nbsp;=&nbsp;open(path,&nbsp;O_RDWR&nbsp;|&nbsp;O_NOCTTY);<br>
&nbsp;&nbsp;&nbsp;&nbsp;fcntl(g-&gt;fd,&nbsp;F_SETFL,&nbsp;fcntl(g-&gt;fd,&nbsp;F_GETFL)&nbsp;|&nbsp;O_NONBLOCK);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(g-&gt;fd&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;serial::open&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;g-&gt;rpack&nbsp;=&nbsp;NULL;<br>
&nbsp;&nbsp;&nbsp;&nbsp;g-&gt;bind(id);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::asyncio.add_iotask(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;g-&gt;fd,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SelectType::READ,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris::make_delegate(&amp;serial_gstuff_v0::read_handler,&nbsp;g));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;g;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
