<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/gates/tcpgate.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#ifndef&nbsp;CROW_GATES_TCPGATE_H<br>
#define&nbsp;CROW_GATES_TCPGATE_H<br>
<br>
#include&nbsp;&lt;crow/gateway.h&gt;<br>
#include&nbsp;&lt;igris/container/unbounded_array.h&gt;<br>
#include&nbsp;&lt;map&gt;<br>
#include&nbsp;&lt;memory&gt;<br>
<br>
#ifdef&nbsp;__WIN32__<br>
#include&nbsp;&lt;winsock2.h&gt;<br>
#else<br>
#include&nbsp;&lt;netinet/in.h&gt;<br>
#include&nbsp;&lt;sys/socket.h&gt;<br>
#endif<br>
<br>
#define&nbsp;CROW_TCPGATE_NO&nbsp;13<br>
<br>
namespace&nbsp;crow<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;/**<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;TCP&nbsp;gate&nbsp;for&nbsp;crow&nbsp;transport.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;Protocol&nbsp;framing:&nbsp;each&nbsp;crow&nbsp;packet&nbsp;is&nbsp;prefixed&nbsp;with&nbsp;4-byte&nbsp;length<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;(network&nbsp;byte&nbsp;order,&nbsp;big-endian).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;Address&nbsp;format&nbsp;in&nbsp;crow&nbsp;packet&nbsp;stage&nbsp;area:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;&nbsp;&nbsp;[1&nbsp;byte:&nbsp;gate_id=13][4&nbsp;bytes:&nbsp;IPv4&nbsp;addr][2&nbsp;bytes:&nbsp;port&nbsp;(network&nbsp;order)]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;class&nbsp;tcpgate&nbsp;:&nbsp;public&nbsp;gateway<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Connection&nbsp;state&nbsp;for&nbsp;each&nbsp;remote&nbsp;peer<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;connection<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;fd&nbsp;=&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris::unbounded_array&lt;uint8_t&gt;&nbsp;recv_buffer&nbsp;=&nbsp;{};<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;expected_size&nbsp;=&nbsp;0;&nbsp;//&nbsp;0&nbsp;=&nbsp;waiting&nbsp;for&nbsp;header<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;server_fd&nbsp;=&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;listen_port&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::map&lt;uint64_t,&nbsp;connection&gt;&nbsp;connections&nbsp;=&nbsp;{};&nbsp;//&nbsp;key&nbsp;=&nbsp;(ip&nbsp;&lt;&lt;&nbsp;16)&nbsp;|&nbsp;port<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris::unbounded_array&lt;uint8_t&gt;&nbsp;send_buffer&nbsp;=&nbsp;{};<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;_debug&nbsp;=&nbsp;false;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Make&nbsp;key&nbsp;from&nbsp;IP&nbsp;and&nbsp;port<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;uint64_t&nbsp;make_key(uint32_t&nbsp;ip,&nbsp;uint16_t&nbsp;port)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;((uint64_t)ip&nbsp;&lt;&lt;&nbsp;16)&nbsp;|&nbsp;port;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Extract&nbsp;IP&nbsp;and&nbsp;port&nbsp;from&nbsp;stage&nbsp;pointer<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;void&nbsp;parse_stage(const&nbsp;uint8_t&nbsp;*stage,&nbsp;uint32_t&nbsp;&amp;ip,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;&amp;port)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ip&nbsp;=&nbsp;*(uint32_t&nbsp;*)(stage&nbsp;+&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;port&nbsp;=&nbsp;*(uint16_t&nbsp;*)(stage&nbsp;+&nbsp;5);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tcpgate()&nbsp;{}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tcpgate(uint16_t&nbsp;port)&nbsp;{&nbsp;open(port);&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;send(crow::packet&nbsp;*)&nbsp;override;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;opened()&nbsp;{&nbsp;return&nbsp;server_fd&nbsp;&gt;&nbsp;0;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;open(uint16_t&nbsp;port&nbsp;=&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;close();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;finish()&nbsp;override&nbsp;{&nbsp;close();&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;bind(Tower&nbsp;&amp;tower,&nbsp;int&nbsp;gate_no&nbsp;=&nbsp;CROW_TCPGATE_NO)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;gateway::bind(tower,&nbsp;gate_no);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;debug(bool&nbsp;val)&nbsp;{&nbsp;_debug&nbsp;=&nbsp;val;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Asyncio&nbsp;handlers<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;accept_handler(int&nbsp;fd);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;read_handler(int&nbsp;fd);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Find&nbsp;or&nbsp;create&nbsp;connection&nbsp;to&nbsp;remote&nbsp;peer<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;get_or_create_connection(uint32_t&nbsp;ip,&nbsp;uint16_t&nbsp;port);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Close&nbsp;specific&nbsp;connection<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;close_connection(uint64_t&nbsp;key);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~tcpgate()&nbsp;override&nbsp;{&nbsp;close();&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::shared_ptr&lt;crow::tcpgate&gt;&nbsp;create_tcpgate_safe(uint8_t&nbsp;id&nbsp;=&nbsp;CROW_TCPGATE_NO,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;port&nbsp;=&nbsp;0);<br>
}<br>
<br>
#endif<br>
<!-- END SCAT CODE -->
</body>
</html>
