<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/gates/tcpgate.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/gates/tcpgate.h&gt;<br>
#include&nbsp;&lt;nos/inet/tcp_client.h&gt;<br>
<br>
std::shared_ptr&lt;crow::tcpgate&gt;&nbsp;crow::create_tcpgate_safe(uint8_t&nbsp;id,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;port)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;sts;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;g&nbsp;=&nbsp;std::make_shared&lt;crow::tcpgate&gt;();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;((sts&nbsp;=&nbsp;g-&gt;open(port)))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;g;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;((sts&nbsp;=&nbsp;g-&gt;bind(id)))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;g-&gt;close();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;g;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;g;<br>
}<br>
<br>
int&nbsp;crow::tcpgate::open(uint16_t&nbsp;port)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;server.init();<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;sts&nbsp;=&nbsp;server.bind(&quot;0.0.0.0&quot;,&nbsp;port);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sts)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sts;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sts&nbsp;=&nbsp;server.listen();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sts)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sts;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;server.nonblock(true);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sts;<br>
}<br>
<br>
void&nbsp;crow::tcpgate::close()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;server.close();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;s&nbsp;:&nbsp;sockets)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;s.second.close();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::tcpgate::send(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;*addr&nbsp;=&nbsp;(uint32_t&nbsp;*)(pack-&gt;stageptr()&nbsp;+&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;*port&nbsp;=&nbsp;(uint16_t&nbsp;*)(pack-&gt;stageptr()&nbsp;+&nbsp;5);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::inet::tcp_client&nbsp;sock;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sock.connect(*addr,&nbsp;*port);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::println(&quot;connect&nbsp;success&quot;);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
