<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/gates/tcpgate.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**&nbsp;@file&nbsp;*/<br>
<br>
#include&nbsp;&lt;crow/defs.h&gt;<br>
#include&nbsp;&lt;crow/gates/tcpgate.h&gt;<br>
#include&nbsp;&lt;crow/tower_cls.h&gt;<br>
<br>
#include&nbsp;&lt;fcntl.h&gt;<br>
#include&nbsp;&lt;unistd.h&gt;<br>
<br>
#ifdef&nbsp;__WIN32__<br>
#include&nbsp;&lt;winsock2.h&gt;<br>
#define&nbsp;SHUT_RDWR&nbsp;2<br>
#else<br>
#include&nbsp;&lt;arpa/inet.h&gt;<br>
#include&nbsp;&lt;netinet/in.h&gt;<br>
#include&nbsp;&lt;netinet/tcp.h&gt;<br>
#include&nbsp;&lt;sys/socket.h&gt;<br>
#endif<br>
<br>
#include&nbsp;&lt;cstring&gt;<br>
#include&nbsp;&lt;memory&gt;<br>
#include&nbsp;&lt;nos/io/stdfile.h&gt;<br>
#include&nbsp;&lt;nos/print.h&gt;<br>
#include&nbsp;&lt;nos/util/osutil.h&gt;<br>
<br>
#ifdef&nbsp;CROW_USE_ASYNCIO<br>
#include&nbsp;&lt;crow/asyncio.h&gt;<br>
#endif<br>
<br>
//&nbsp;Frame&nbsp;header&nbsp;size:&nbsp;4&nbsp;bytes&nbsp;for&nbsp;packet&nbsp;length<br>
static&nbsp;constexpr&nbsp;size_t&nbsp;FRAME_HEADER_SIZE&nbsp;=&nbsp;4;<br>
<br>
std::shared_ptr&lt;crow::tcpgate&gt;&nbsp;crow::create_tcpgate_safe(uint8_t&nbsp;id,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;port)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)id;&nbsp;//&nbsp;gate&nbsp;id&nbsp;is&nbsp;set&nbsp;when&nbsp;binding&nbsp;to&nbsp;tower<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;g&nbsp;=&nbsp;std::make_shared&lt;crow::tcpgate&gt;();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(g-&gt;open(port)&nbsp;!=&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;g;<br>
}<br>
<br>
int&nbsp;crow::tcpgate::open(uint16_t&nbsp;port)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;listen_port&nbsp;=&nbsp;port;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;server_fd&nbsp;=&nbsp;socket(AF_INET,&nbsp;SOCK_STREAM,&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(server_fd&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;tcpgate&nbsp;socket&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Allow&nbsp;address&nbsp;reuse<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;opt&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;setsockopt(server_fd,&nbsp;SOL_SOCKET,&nbsp;SO_REUSEADDR,&nbsp;&amp;opt,&nbsp;sizeof(opt));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;sockaddr_in&nbsp;addr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;memset(&amp;addr,&nbsp;0,&nbsp;sizeof(addr));<br>
&nbsp;&nbsp;&nbsp;&nbsp;addr.sin_family&nbsp;=&nbsp;AF_INET;<br>
&nbsp;&nbsp;&nbsp;&nbsp;addr.sin_addr.s_addr&nbsp;=&nbsp;INADDR_ANY;<br>
&nbsp;&nbsp;&nbsp;&nbsp;addr.sin_port&nbsp;=&nbsp;htons(port);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(port&nbsp;!=&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(::bind(server_fd,&nbsp;(struct&nbsp;sockaddr&nbsp;*)&amp;addr,&nbsp;sizeof(addr))&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;tcpgate&nbsp;bind&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;::close(server_fd);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;server_fd&nbsp;=&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(listen(server_fd,&nbsp;10)&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;tcpgate&nbsp;listen&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;::close(server_fd);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;server_fd&nbsp;=&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::osutil::nonblock(server_fd,&nbsp;true);<br>
<br>
#ifdef&nbsp;CROW_USE_ASYNCIO<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::asyncio.add_iotask(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;server_fd,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SelectType::READ,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris::make_delegate(&amp;tcpgate::accept_handler,&nbsp;this));<br>
#endif<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate:&nbsp;listening&nbsp;on&nbsp;port&nbsp;&quot;,&nbsp;port);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
void&nbsp;crow::tcpgate::accept_handler(int&nbsp;fd)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)fd;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;sockaddr_in&nbsp;client_addr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;socklen_t&nbsp;client_len&nbsp;=&nbsp;sizeof(client_addr);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;client_fd&nbsp;=&nbsp;accept(server_fd,&nbsp;(struct&nbsp;sockaddr&nbsp;*)&amp;client_addr,&nbsp;&amp;client_len);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(client_fd&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(errno&nbsp;!=&nbsp;EAGAIN&nbsp;&amp;&amp;&nbsp;errno&nbsp;!=&nbsp;EWOULDBLOCK)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;tcpgate&nbsp;accept&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Set&nbsp;non-blocking<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::osutil::nonblock(client_fd,&nbsp;true);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Disable&nbsp;Nagle's&nbsp;algorithm&nbsp;for&nbsp;low&nbsp;latency<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;flag&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;setsockopt(client_fd,&nbsp;IPPROTO_TCP,&nbsp;TCP_NODELAY,&nbsp;&amp;flag,&nbsp;sizeof(flag));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;ip&nbsp;=&nbsp;client_addr.sin_addr.s_addr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;port&nbsp;=&nbsp;client_addr.sin_port;<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint64_t&nbsp;key&nbsp;=&nbsp;make_key(ip,&nbsp;port);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;ip_str[INET_ADDRSTRLEN];<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inet_ntop(AF_INET,&nbsp;&amp;ip,&nbsp;ip_str,&nbsp;sizeof(ip_str));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate:&nbsp;accepted&nbsp;connection&nbsp;from&nbsp;&quot;,&nbsp;ip_str,&nbsp;&quot;:&quot;,&nbsp;ntohs(port));<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Store&nbsp;connection<br>
&nbsp;&nbsp;&nbsp;&nbsp;connection&nbsp;conn;<br>
&nbsp;&nbsp;&nbsp;&nbsp;conn.fd&nbsp;=&nbsp;client_fd;<br>
&nbsp;&nbsp;&nbsp;&nbsp;conn.expected_size&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;connections[key]&nbsp;=&nbsp;std::move(conn);<br>
<br>
#ifdef&nbsp;CROW_USE_ASYNCIO<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::asyncio.add_iotask(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;client_fd,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SelectType::READ,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris::make_delegate(&amp;tcpgate::read_handler,&nbsp;this));<br>
#endif<br>
}<br>
<br>
void&nbsp;crow::tcpgate::read_handler(int&nbsp;fd)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate:&nbsp;read_handler&nbsp;called&nbsp;for&nbsp;fd=&quot;,&nbsp;fd);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Find&nbsp;connection&nbsp;by&nbsp;fd<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint64_t&nbsp;conn_key&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;connection&nbsp;*conn&nbsp;=&nbsp;nullptr;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;kv&nbsp;:&nbsp;connections)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(kv.second.fd&nbsp;==&nbsp;fd)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;conn_key&nbsp;=&nbsp;kv.first;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;conn&nbsp;=&nbsp;&amp;kv.second;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!conn)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate:&nbsp;unknown&nbsp;fd,&nbsp;discarding&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Unknown&nbsp;fd,&nbsp;just&nbsp;read&nbsp;and&nbsp;discard<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;buf[1024];<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;read(fd,&nbsp;buf,&nbsp;sizeof(buf));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Read&nbsp;available&nbsp;data<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;buf[4096];<br>
&nbsp;&nbsp;&nbsp;&nbsp;ssize_t&nbsp;len&nbsp;=&nbsp;read(fd,&nbsp;buf,&nbsp;sizeof(buf));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate:&nbsp;read&nbsp;&quot;,&nbsp;len,&nbsp;&quot;&nbsp;bytes&nbsp;from&nbsp;fd=&quot;,&nbsp;fd);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(len&nbsp;&lt;=&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(len&nbsp;==&nbsp;0&nbsp;||&nbsp;(errno&nbsp;!=&nbsp;EAGAIN&nbsp;&amp;&amp;&nbsp;errno&nbsp;!=&nbsp;EWOULDBLOCK))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate:&nbsp;connection&nbsp;closed,&nbsp;fd=&quot;,&nbsp;fd);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;close_connection(conn_key);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Append&nbsp;to&nbsp;receive&nbsp;buffer<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;old_size&nbsp;=&nbsp;conn-&gt;recv_buffer.size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;conn-&gt;recv_buffer.resize(old_size&nbsp;+&nbsp;len);<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(conn-&gt;recv_buffer.data()&nbsp;+&nbsp;old_size,&nbsp;buf,&nbsp;len);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Process&nbsp;complete&nbsp;frames<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(true)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;buf_size&nbsp;=&nbsp;conn-&gt;recv_buffer.size();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Need&nbsp;frame&nbsp;header&nbsp;first<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(conn-&gt;expected_size&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(buf_size&nbsp;&lt;&nbsp;FRAME_HEADER_SIZE)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Read&nbsp;4-byte&nbsp;length&nbsp;(network&nbsp;byte&nbsp;order)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;frame_len;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(&amp;frame_len,&nbsp;conn-&gt;recv_buffer.data(),&nbsp;4);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;conn-&gt;expected_size&nbsp;=&nbsp;ntohl(frame_len);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate:&nbsp;frame&nbsp;header&nbsp;raw&nbsp;bytes:&nbsp;&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(int)(unsigned&nbsp;char)conn-&gt;recv_buffer[0],&nbsp;&quot;&nbsp;&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(int)(unsigned&nbsp;char)conn-&gt;recv_buffer[1],&nbsp;&quot;&nbsp;&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(int)(unsigned&nbsp;char)conn-&gt;recv_buffer[2],&nbsp;&quot;&nbsp;&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(int)(unsigned&nbsp;char)conn-&gt;recv_buffer[3]);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate:&nbsp;frame&nbsp;header,&nbsp;size=&quot;,&nbsp;conn-&gt;expected_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Check&nbsp;if&nbsp;we&nbsp;have&nbsp;complete&nbsp;frame<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;total_needed&nbsp;=&nbsp;FRAME_HEADER_SIZE&nbsp;+&nbsp;conn-&gt;expected_size;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(buf_size&nbsp;&lt;&nbsp;total_needed)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Extract&nbsp;crow&nbsp;packet&nbsp;data&nbsp;(after&nbsp;frame&nbsp;header)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;*frame_data&nbsp;=&nbsp;conn-&gt;recv_buffer.data()&nbsp;+&nbsp;FRAME_HEADER_SIZE;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;frame_size&nbsp;=&nbsp;conn-&gt;expected_size;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Parse&nbsp;crow&nbsp;header&nbsp;to&nbsp;allocate&nbsp;packet<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::header_v1&nbsp;header;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(frame_size&nbsp;&lt;&nbsp;sizeof(header))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate:&nbsp;frame&nbsp;too&nbsp;small&nbsp;for&nbsp;header&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Remove&nbsp;bad&nbsp;frame&nbsp;and&nbsp;continue<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;conn-&gt;recv_buffer.resize(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;conn-&gt;expected_size&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(&amp;header,&nbsp;frame_data,&nbsp;sizeof(header));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Allocate&nbsp;packet<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;allocate_packet&lt;crow::header_v1&gt;(header.addrsize(),&nbsp;header.datasize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;parse_header(header);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Copy&nbsp;full&nbsp;packet&nbsp;data<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;header_addr(),&nbsp;frame_data,&nbsp;frame_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet_initialization(pack,&nbsp;this);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Add&nbsp;sender&nbsp;address&nbsp;to&nbsp;packet&nbsp;(revert&nbsp;stage)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;sender_ip&nbsp;=&nbsp;(uint32_t)(conn_key&nbsp;&gt;&gt;&nbsp;16);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;sender_port&nbsp;=&nbsp;(uint16_t)(conn_key&nbsp;&amp;&nbsp;0xFFFF);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::buffer&nbsp;vec[3]&nbsp;=&nbsp;{{(char&nbsp;*)&amp;id,&nbsp;1},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(char&nbsp;*)&amp;sender_ip,&nbsp;4},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(char&nbsp;*)&amp;sender_port,&nbsp;2}};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;revert(vec,&nbsp;3);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate:&nbsp;received&nbsp;packet,&nbsp;size=&quot;,&nbsp;frame_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Pass&nbsp;to&nbsp;tower<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_tower-&gt;nocontrol_travel(pack,&nbsp;true);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Remove&nbsp;processed&nbsp;frame&nbsp;from&nbsp;buffer<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;remaining&nbsp;=&nbsp;buf_size&nbsp;-&nbsp;total_needed;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(remaining&nbsp;&gt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memmove(conn-&gt;recv_buffer.data(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;conn-&gt;recv_buffer.data()&nbsp;+&nbsp;total_needed,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;remaining);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;conn-&gt;recv_buffer.resize(remaining);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;conn-&gt;expected_size&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
int&nbsp;crow::tcpgate::get_or_create_connection(uint32_t&nbsp;ip,&nbsp;uint16_t&nbsp;port)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint64_t&nbsp;key&nbsp;=&nbsp;make_key(ip,&nbsp;port);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;it&nbsp;=&nbsp;connections.find(key);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it&nbsp;!=&nbsp;connections.end()&nbsp;&amp;&amp;&nbsp;it-&gt;second.fd&nbsp;&gt;=&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;it-&gt;second.fd;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Create&nbsp;new&nbsp;connection<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;sock&nbsp;=&nbsp;socket(AF_INET,&nbsp;SOCK_STREAM,&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sock&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;tcpgate&nbsp;socket&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;sockaddr_in&nbsp;addr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;memset(&amp;addr,&nbsp;0,&nbsp;sizeof(addr));<br>
&nbsp;&nbsp;&nbsp;&nbsp;addr.sin_family&nbsp;=&nbsp;AF_INET;<br>
&nbsp;&nbsp;&nbsp;&nbsp;addr.sin_addr.s_addr&nbsp;=&nbsp;ip;<br>
&nbsp;&nbsp;&nbsp;&nbsp;addr.sin_port&nbsp;=&nbsp;port;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;ip_str[INET_ADDRSTRLEN];<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inet_ntop(AF_INET,&nbsp;&amp;ip,&nbsp;ip_str,&nbsp;sizeof(ip_str));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate:&nbsp;connecting&nbsp;to&nbsp;&quot;,&nbsp;ip_str,&nbsp;&quot;:&quot;,&nbsp;ntohs(port));<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(connect(sock,&nbsp;(struct&nbsp;sockaddr&nbsp;*)&amp;addr,&nbsp;sizeof(addr))&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;tcpgate&nbsp;connect&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;::close(sock);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Set&nbsp;non-blocking&nbsp;after&nbsp;connect<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::osutil::nonblock(sock,&nbsp;true);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Disable&nbsp;Nagle<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;flag&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;setsockopt(sock,&nbsp;IPPROTO_TCP,&nbsp;TCP_NODELAY,&nbsp;&amp;flag,&nbsp;sizeof(flag));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Store&nbsp;connection<br>
&nbsp;&nbsp;&nbsp;&nbsp;connection&nbsp;conn;<br>
&nbsp;&nbsp;&nbsp;&nbsp;conn.fd&nbsp;=&nbsp;sock;<br>
&nbsp;&nbsp;&nbsp;&nbsp;conn.expected_size&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;connections[key]&nbsp;=&nbsp;std::move(conn);<br>
<br>
#ifdef&nbsp;CROW_USE_ASYNCIO<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::asyncio.add_iotask(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sock,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SelectType::READ,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris::make_delegate(&amp;tcpgate::read_handler,&nbsp;this));<br>
#endif<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate:&nbsp;connected,&nbsp;fd=&quot;,&nbsp;sock);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sock;<br>
}<br>
<br>
void&nbsp;crow::tcpgate::send(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;ip;<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;port;<br>
&nbsp;&nbsp;&nbsp;&nbsp;parse_stage((uint8_t&nbsp;*)pack-&gt;stageptr(),&nbsp;ip,&nbsp;port);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;ip_str[INET_ADDRSTRLEN];<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inet_ntop(AF_INET,&nbsp;&amp;ip,&nbsp;ip_str,&nbsp;sizeof(ip_str));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate::send:&nbsp;to&nbsp;&quot;,&nbsp;ip_str,&nbsp;&quot;:&quot;,&nbsp;ntohs(port));<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;sock&nbsp;=&nbsp;get_or_create_connection(ip,&nbsp;port);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sock&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate::send:&nbsp;failed&nbsp;to&nbsp;get&nbsp;connection&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_tower-&gt;return_to_tower(pack,&nbsp;CROW_WRONG_ADDRESS);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Build&nbsp;frame:&nbsp;4-byte&nbsp;length&nbsp;+&nbsp;crow&nbsp;packet<br>
&nbsp;&nbsp;&nbsp;&nbsp;header_v1&nbsp;header&nbsp;=&nbsp;pack-&gt;extract_header_v1();<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;packet_size&nbsp;=&nbsp;header.flen;<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;frame_len&nbsp;=&nbsp;htonl(packet_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Resize&nbsp;send&nbsp;buffer<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(send_buffer.size()&nbsp;&lt;&nbsp;FRAME_HEADER_SIZE&nbsp;+&nbsp;packet_size)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;send_buffer.resize(FRAME_HEADER_SIZE&nbsp;+&nbsp;packet_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Write&nbsp;frame&nbsp;header<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(send_buffer.data(),&nbsp;&amp;frame_len,&nbsp;4);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Write&nbsp;crow&nbsp;packet<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(send_buffer.data()&nbsp;+&nbsp;FRAME_HEADER_SIZE,&nbsp;&amp;header,&nbsp;sizeof(header));<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(send_buffer.data()&nbsp;+&nbsp;FRAME_HEADER_SIZE&nbsp;+&nbsp;sizeof(header),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;addrptr(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;addrsize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(send_buffer.data()&nbsp;+&nbsp;FRAME_HEADER_SIZE&nbsp;+&nbsp;sizeof(header)&nbsp;+&nbsp;pack-&gt;addrsize(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;dataptr(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;datasize());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Send&nbsp;with&nbsp;retry&nbsp;for&nbsp;partial&nbsp;writes<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;total&nbsp;=&nbsp;FRAME_HEADER_SIZE&nbsp;+&nbsp;packet_size;<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;sent&nbsp;=&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(sent&nbsp;&lt;&nbsp;total)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ssize_t&nbsp;n&nbsp;=&nbsp;::send(sock,&nbsp;(char&nbsp;*)send_buffer.data()&nbsp;+&nbsp;sent,&nbsp;total&nbsp;-&nbsp;sent,&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(n&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(errno&nbsp;==&nbsp;EAGAIN&nbsp;||&nbsp;errno&nbsp;==&nbsp;EWOULDBLOCK)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Would&nbsp;block,&nbsp;try&nbsp;again<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;usleep(1000);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;tcpgate&nbsp;send&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_tower-&gt;return_to_tower(pack,&nbsp;CROW_WRONG_ADDRESS);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sent&nbsp;+=&nbsp;n;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(nos::cerr,&nbsp;&quot;tcpgate:&nbsp;sent&nbsp;frame,&nbsp;size=&quot;,&nbsp;packet_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;_tower-&gt;return_to_tower(pack,&nbsp;CROW_SENDED);<br>
}<br>
<br>
void&nbsp;crow::tcpgate::close_connection(uint64_t&nbsp;key)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;it&nbsp;=&nbsp;connections.find(key);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it&nbsp;!=&nbsp;connections.end())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it-&gt;second.fd&nbsp;&gt;=&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
#ifdef&nbsp;CROW_USE_ASYNCIO<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::asyncio.remove_iotask(it-&gt;second.fd);<br>
#endif<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;shutdown(it-&gt;second.fd,&nbsp;SHUT_RDWR);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;::close(it-&gt;second.fd);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;connections.erase(it);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::tcpgate::close()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Close&nbsp;all&nbsp;client&nbsp;connections<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;kv&nbsp;:&nbsp;connections)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(kv.second.fd&nbsp;&gt;=&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
#ifdef&nbsp;CROW_USE_ASYNCIO<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::asyncio.remove_iotask(kv.second.fd);<br>
#endif<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;shutdown(kv.second.fd,&nbsp;SHUT_RDWR);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;::close(kv.second.fd);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;connections.clear();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Close&nbsp;server&nbsp;socket<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(server_fd&nbsp;&gt;=&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
#ifdef&nbsp;CROW_USE_ASYNCIO<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::asyncio.remove_iotask(server_fd);<br>
#endif<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;shutdown(server_fd,&nbsp;SHUT_RDWR);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;::close(server_fd);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;server_fd&nbsp;=&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
