<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/gates/udpgate.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**&nbsp;@file&nbsp;*/<br>
<br>
#include&nbsp;&lt;crow/gates/udpgate.h&gt;<br>
#include&nbsp;&lt;crow/tower.h&gt;<br>
<br>
#include&nbsp;&lt;fcntl.h&gt;<br>
#include&nbsp;&lt;unistd.h&gt;<br>
<br>
#ifdef&nbsp;__WIN32__<br>
//#include&nbsp;&lt;winsock.h&gt;<br>
#include&nbsp;&lt;winsock2.h&gt;<br>
#define&nbsp;SHUT_RDWR&nbsp;2<br>
#else<br>
#include&nbsp;&lt;netinet/in.h&gt;<br>
#include&nbsp;&lt;netinet/ip.h&gt;<br>
#include&nbsp;&lt;sys/socket.h&gt;<br>
#include&nbsp;&lt;sys/uio.h&gt;<br>
#endif<br>
<br>
#include&nbsp;&lt;memory&gt;<br>
#include&nbsp;&lt;nos/print.h&gt;<br>
#include&nbsp;&lt;nos/util/osutil.h&gt;<br>
#include&nbsp;&lt;stdio.h&gt;<br>
#include&nbsp;&lt;string.h&gt;<br>
#include&nbsp;&lt;sys/types.h&gt;<br>
<br>
#ifdef&nbsp;CROW_USE_ASYNCIO<br>
#include&nbsp;&lt;crow/asyncio.h&gt;<br>
#endif<br>
<br>
void&nbsp;crow::udpgate::read_handler(int&nbsp;fd)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)fd;&nbsp;//&nbsp;only&nbsp;one<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::header_v1&nbsp;header;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;sockaddr_in&nbsp;sender;<br>
&nbsp;&nbsp;&nbsp;&nbsp;socklen_t&nbsp;sender_socksize&nbsp;=&nbsp;sizeof(sender);<br>
&nbsp;&nbsp;&nbsp;&nbsp;memset(&amp;sender,&nbsp;0,&nbsp;sizeof(sender));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;ssize_t&nbsp;len&nbsp;=&nbsp;recvfrom(sock,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(char&nbsp;*)&amp;header,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::header_v1),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MSG_PEEK,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(struct&nbsp;sockaddr&nbsp;*)&amp;sender,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&amp;sender_socksize);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(len&nbsp;&lt;=&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println(&quot;udpgate:&nbsp;recvfrom:&nbsp;&quot;,&nbsp;len);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*block&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;allocate_packet&lt;crow::header_v1&gt;(header.addrsize(),&nbsp;header.datasize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;block-&gt;parse_header(header);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;len&nbsp;=&nbsp;recvfrom(sock,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(char&nbsp;*)block-&gt;header_addr(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;block-&gt;fullsize(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(struct&nbsp;sockaddr&nbsp;*)&amp;sender,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&amp;sender_socksize);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(len&nbsp;&lt;=&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(block);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;block&nbsp;=&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet_initialization(block,&nbsp;this);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::buffer&nbsp;vec[3]&nbsp;=&nbsp;{{(char&nbsp;*)&amp;id,&nbsp;1},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(char&nbsp;*)&amp;sender.sin_addr.s_addr,&nbsp;4},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(char&nbsp;*)&amp;sender.sin_port,&nbsp;2}};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;block-&gt;revert(vec,&nbsp;3);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;block;<br>
&nbsp;&nbsp;&nbsp;&nbsp;block&nbsp;=&nbsp;NULL;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::nocontrol_travel(pack,&nbsp;true);<br>
}<br>
<br>
int&nbsp;crow::udpgate::open(uint16_t&nbsp;port)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;ret;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sock&nbsp;=&nbsp;socket(AF_INET,&nbsp;SOCK_DGRAM,&nbsp;0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sock&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;udp&nbsp;socket&nbsp;open:&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(&quot;code&nbsp;%d&quot;,&nbsp;sock);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;sockaddr_in&nbsp;ipaddr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;socklen_t&nbsp;iplen&nbsp;=&nbsp;sizeof(struct&nbsp;sockaddr_in);<br>
&nbsp;&nbsp;&nbsp;&nbsp;memset(&amp;ipaddr,&nbsp;0,&nbsp;iplen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ipaddr.sin_port&nbsp;=&nbsp;htons(port);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ipaddr.sin_family&nbsp;=&nbsp;PF_INET;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(port&nbsp;!=&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ret&nbsp;=&nbsp;::bind(sock,&nbsp;(struct&nbsp;sockaddr&nbsp;*)&amp;ipaddr,&nbsp;iplen);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(ret&nbsp;!=&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;crow::udpgate::bind&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit(-1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;dynamic&nbsp;port&nbsp;assign<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ret&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::osutil::nonblock(sock,&nbsp;true);<br>
<br>
#ifdef&nbsp;CROW_USE_ASYNCIO<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::asyncio.add_iotask(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sock,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SelectType::READ,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris::make_delegate(&amp;udpgate::read_handler,&nbsp;this));<br>
#endif<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ret;<br>
}<br>
<br>
void&nbsp;crow::udpgate::close()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sock&nbsp;&gt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;::shutdown(sock,&nbsp;SHUT_RDWR);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;::close(sock);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sock&nbsp;=&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::udpgate::send(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;*addr&nbsp;=&nbsp;(uint32_t&nbsp;*)(pack-&gt;stageptr()&nbsp;+&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;*port&nbsp;=&nbsp;(uint16_t&nbsp;*)(pack-&gt;stageptr()&nbsp;+&nbsp;5);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;sockaddr_in&nbsp;ipaddr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;socklen_t&nbsp;iplen&nbsp;=&nbsp;sizeof(struct&nbsp;sockaddr_in);<br>
&nbsp;&nbsp;&nbsp;&nbsp;memset(&amp;ipaddr,&nbsp;0,&nbsp;iplen);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//Конвертация&nbsp;не&nbsp;требуется,&nbsp;т.к.&nbsp;crow&nbsp;использует&nbsp;сетевой&nbsp;порядок&nbsp;записи<br>
&nbsp;&nbsp;&nbsp;&nbsp;//адреса.<br>
&nbsp;&nbsp;&nbsp;&nbsp;ipaddr.sin_port&nbsp;=&nbsp;*port;<br>
&nbsp;&nbsp;&nbsp;&nbsp;ipaddr.sin_addr.s_addr&nbsp;=&nbsp;*addr;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;header_v1&nbsp;header&nbsp;=&nbsp;pack-&gt;extract_header_v1();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(send_buffer.size()&nbsp;&lt;&nbsp;header.flen)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;send_buffer.resize(header.flen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(send_buffer.data(),&nbsp;&amp;header,&nbsp;sizeof(header));<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;send_buffer.data()&nbsp;+&nbsp;sizeof(header),&nbsp;pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(send_buffer.data()&nbsp;+&nbsp;sizeof(header)&nbsp;+&nbsp;pack-&gt;addrsize(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;dataptr(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;datasize());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sendto(sock,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(char&nbsp;*)send_buffer.data(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header.flen,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(struct&nbsp;sockaddr&nbsp;*)&amp;ipaddr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iplen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::return_to_tower(pack,&nbsp;CROW_SENDED);<br>
}<br>
<br>
int&nbsp;crow::create_udpgate(uint8_t&nbsp;id,&nbsp;uint16_t&nbsp;port)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;sts;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::udpgate&nbsp;*g&nbsp;=&nbsp;new&nbsp;crow::udpgate;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;((sts&nbsp;=&nbsp;g-&gt;open(port)))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sts;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;((sts&nbsp;=&nbsp;g-&gt;bind(id)))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;g-&gt;close();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sts;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
std::shared_ptr&lt;crow::udpgate&gt;&nbsp;crow::create_udpgate_safe(uint8_t&nbsp;id,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;port)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;sts;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;g&nbsp;=&nbsp;std::make_shared&lt;crow::udpgate&gt;();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;((sts&nbsp;=&nbsp;g-&gt;open(port)))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;g;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;((sts&nbsp;=&nbsp;g-&gt;bind(id)))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;g-&gt;close();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;g;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;g;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
