<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>apps/ctrans/HIDE/binout.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;binout.h&quot;<br>
#include&nbsp;&quot;bincommon.h&quot;<br>
<br>
#include&nbsp;&lt;crow/print.h&gt;<br>
#include&nbsp;&lt;map&gt;<br>
#include&nbsp;&lt;vector&gt;<br>
<br>
#include&nbsp;&lt;string.h&gt;<br>
<br>
#include&nbsp;&lt;nos/fprint.h&gt;<br>
<br>
#include&nbsp;&lt;igris/util/string.h&gt;<br>
<br>
std::string&nbsp;flt32_output(void&nbsp;*tgt)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;arg;<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(&amp;arg,&nbsp;tgt,&nbsp;4);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nos::format(&quot;{}&quot;,&nbsp;arg);<br>
}<br>
<br>
std::string&nbsp;int64_output(void&nbsp;*tgt)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int64_t&nbsp;arg;<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(&amp;arg,&nbsp;tgt,&nbsp;8);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nos::format(&quot;{}&quot;,&nbsp;arg);<br>
}<br>
<br>
std::string&nbsp;int32_output(void&nbsp;*tgt)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int32_t&nbsp;arg;<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(&amp;arg,&nbsp;tgt,&nbsp;4);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nos::format(&quot;{}&quot;,&nbsp;arg);<br>
}<br>
<br>
std::string&nbsp;int16_output(void&nbsp;*tgt)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int16_t&nbsp;arg;<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(&amp;arg,&nbsp;tgt,&nbsp;2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nos::format(&quot;{}&quot;,&nbsp;arg);<br>
}<br>
<br>
std::string&nbsp;int8_output(void&nbsp;*tgt)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int8_t&nbsp;arg;<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(&amp;arg,&nbsp;tgt,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nos::format(&quot;{}&quot;,&nbsp;arg);<br>
}<br>
<br>
size_t&nbsp;binout_size&nbsp;=&nbsp;0;<br>
std::vector&lt;size_t&gt;&nbsp;binout_sizes;<br>
std::vector&lt;std::string&nbsp;(*)(void&nbsp;*)&gt;&nbsp;binout_restores;<br>
<br>
std::vector&lt;std::string&gt;&nbsp;binout_format;<br>
<br>
std::map&lt;std::string,&nbsp;std::string&nbsp;(*)(void&nbsp;*tgt)&gt;&nbsp;visitor_restore&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;f32&quot;,&nbsp;flt32_output},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;i64&quot;,&nbsp;int64_output},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;i32&quot;,&nbsp;int32_output},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;i16&quot;,&nbsp;int16_output},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;i8&quot;,&nbsp;int8_output}};<br>
<br>
void&nbsp;binout_mode_prepare(const&nbsp;std::string&nbsp;&amp;fmt)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;binout_format&nbsp;=&nbsp;igris::split(fmt,&nbsp;',');<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;str&nbsp;:&nbsp;binout_format)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;binout_size&nbsp;+=&nbsp;visitor_size.at(str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;binout_sizes.push_back(visitor_size.at(str));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;binout_restores.push_back(visitor_restore.at(str));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(std::out_of_range&nbsp;&amp;ex)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpr(str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dprln(&quot;&nbsp;is&nbsp;not&nbsp;in&nbsp;format&nbsp;list&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit(-1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;output_binary(nos::buffer&nbsp;data,&nbsp;crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;igris::strvec&nbsp;result;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(data.size()&nbsp;!=&nbsp;binout_size)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println(&quot;WARN:&nbsp;wrong_size&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::print_dump(data);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::diagnostic(&quot;binmode&quot;,&nbsp;pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;*ptr&nbsp;=&nbsp;data.data();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(unsigned&nbsp;int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;binout_format.size();&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;str&nbsp;=&nbsp;binout_restores[i](ptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;fstr&nbsp;=&nbsp;binout_format[i];<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ptr&nbsp;+=&nbsp;binout_sizes[i];<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.push_back(str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::println(result);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;fflush(stdout);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
