<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/src/variants/allocation_malloc.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**<br>
&nbsp;*&nbsp;@file<br>
&nbsp;*&nbsp;@author&nbsp;mirmik<br>
&nbsp;*&nbsp;@brief&nbsp;Управление&nbsp;памятью&nbsp;пакетов&nbsp;через&nbsp;libc&nbsp;malloc<br>
&nbsp;*/<br>
<br>
#include&nbsp;&lt;crow/packet.h&gt;<br>
#include&nbsp;&lt;igris/dtrace.h&gt;<br>
#include&nbsp;&lt;igris/sync/syslock.h&gt;<br>
#include&nbsp;&lt;stdlib.h&gt;<br>
<br>
int&nbsp;_crow_allocated_count&nbsp;=&nbsp;0;<br>
<br>
int&nbsp;crow_allocated_count_inc()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;_crow_allocated_count++;<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(_crow_allocated_count&nbsp;&lt;&nbsp;64);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_crow_allocated_count;<br>
}<br>
<br>
int&nbsp;crow_allocated_count_dec()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;_crow_allocated_count--;<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_crow_allocated_count;<br>
}<br>
<br>
void&nbsp;crow::deallocate_packet(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow_allocated_count_dec();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;free((void&nbsp;*)pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(_crow_allocated_count&nbsp;&gt;=&nbsp;0);<br>
}<br>
<br>
int&nbsp;crow::allocated_count()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_crow_allocated_count;<br>
}<br>
<br>
crow::packet&nbsp;*crow::allocate_packet_header_v0(int&nbsp;alen,&nbsp;int&nbsp;dlen)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;allocate_packet_header_v0(alen&nbsp;+&nbsp;dlen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_addrsize(alen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_datasize(dlen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;pack;<br>
}<br>
<br>
crow::packet&nbsp;*crow::allocate_packet_header_v1(int&nbsp;alen,&nbsp;int&nbsp;dlen)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;allocate_packet_header_v1(alen&nbsp;+&nbsp;dlen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_addrsize(alen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_datasize(dlen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;pack;<br>
}<br>
<br>
crow::packet&nbsp;*crow::allocate_packet_header_v0(int&nbsp;adlen)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow_allocated_count_inc();<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;*buffer&nbsp;=&nbsp;(uint8_t&nbsp;*)malloc(sizeof(crow::packet)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::header_v0)&nbsp;+&nbsp;adlen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;memset(buffer,&nbsp;0,&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v0)&nbsp;+&nbsp;adlen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;new&nbsp;(buffer)&nbsp;crow::packet(crow::deallocate_packet);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;attach_header((crow::header_v0&nbsp;*)(buffer&nbsp;+&nbsp;sizeof(crow::packet)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;attach_addrdata(buffer&nbsp;+&nbsp;sizeof(crow::packet)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::header_v0));<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;pack;<br>
}<br>
<br>
crow::packet&nbsp;*crow::allocate_packet_header_v1(int&nbsp;adlen)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow_allocated_count_inc();<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;*buffer&nbsp;=&nbsp;(uint8_t&nbsp;*)malloc(sizeof(crow::packet)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::header_v1)&nbsp;+&nbsp;adlen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;memset(buffer,&nbsp;0,&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v1)&nbsp;+&nbsp;adlen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;new&nbsp;(buffer)&nbsp;crow::packet(crow::deallocate_packet);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;attach_header((crow::header_v1&nbsp;*)(buffer&nbsp;+&nbsp;sizeof(crow::packet)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;attach_addrdata(buffer&nbsp;+&nbsp;sizeof(crow::packet)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::header_v1));<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;pack;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
