/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crow_Crow */

#ifndef _Included_crow_Crow
#define _Included_crow_Crow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crow_Crow
 * Method:    diagnostic_enable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_crow_Crow_diagnostic_1enable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     crow_Crow
 * Method:    start_spin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crow_Crow_start_1spin
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
