<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/proto/channel.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/proto/acceptor.h&gt;<br>
#include&nbsp;&lt;crow/proto/channel.h&gt;<br>
#include&nbsp;&lt;crow/tower.h&gt;<br>
#include&nbsp;&lt;crow/warn.h&gt;<br>
<br>
#include&nbsp;&lt;igris/util/bug.h&gt;<br>
#include&nbsp;&lt;nos/print.h&gt;<br>
<br>
void&nbsp;crow::channel::incoming_packet(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::node_subheader&nbsp;*sh_node&nbsp;=&nbsp;(node_subheader&nbsp;*)pack-&gt;dataptr();<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::subheader_channel&nbsp;*sh_channel&nbsp;=&nbsp;crow::get_subheader_channel(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(sh_channel-&gt;ftype)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;crow::Frame::HANDSHAKE_REQUEST:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Кто-то&nbsp;пытается&nbsp;установить&nbsp;с&nbsp;нами&nbsp;связь.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(u.f.naive_listener&nbsp;||<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;u.f._state&nbsp;==&nbsp;CROW_CHANNEL_WAIT_HANDSHAKE_REQUEST)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::subheader_handshake&nbsp;*sh_handshake&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::get_subheader_handshake(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;TODO:&nbsp;перенести&nbsp;аллокацию&nbsp;под&nbsp;адрес&nbsp;в&nbsp;другое&nbsp;место<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;raddr_ptr&nbsp;=&nbsp;malloc(pack-&gt;addrsize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;addrsize()&nbsp;&gt;&nbsp;raddr_cap)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(raddr_ptr,&nbsp;pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raddr_len&nbsp;=&nbsp;pack-&gt;addrsize();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rid&nbsp;=&nbsp;sh_node-&gt;sid;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;qos&nbsp;=&nbsp;sh_handshake-&gt;qos;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;ackquant&nbsp;=&nbsp;sh_handshake-&gt;ackquant;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;send_handshake_answer();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;u.f._state&nbsp;=&nbsp;CROW_CHANNEL_CONNECTED;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::warn(&quot;WARN:&nbsp;HANDSHAKE_REQUEST&nbsp;on&nbsp;another&nbsp;state&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;crow::Frame::HANDSHAKE_ANSWER:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Кто-то&nbsp;ответил&nbsp;на&nbsp;зов.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(u.f._state&nbsp;==&nbsp;CROW_CHANNEL_WAIT_HANDSHAKE_ANSWER)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Если&nbsp;мы&nbsp;еще&nbsp;ни&nbsp;с&nbsp;кем&nbsp;и&nbsp;никогда.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::subheader_handshake&nbsp;*sh_handshake&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::get_subheader_handshake(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;TODO:&nbsp;перенести&nbsp;аллокацию&nbsp;под&nbsp;адрес&nbsp;в&nbsp;другое&nbsp;место<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;raddr_ptr&nbsp;=&nbsp;malloc(pack-&gt;addrsize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pack-&gt;addrsize()&nbsp;&gt;&nbsp;raddr_cap)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(raddr_ptr,&nbsp;pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raddr_len&nbsp;=&nbsp;pack-&gt;addrsize();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rid&nbsp;=&nbsp;sh_node-&gt;sid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;qos&nbsp;=&nbsp;sh_handshake-&gt;qos;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ackquant&nbsp;=&nbsp;sh_handshake-&gt;ackquant;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;u.f._state&nbsp;=&nbsp;CROW_CHANNEL_CONNECTED;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;notify_one(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::warn(&quot;WARN:&nbsp;HANDSHAKE_ANSWER&nbsp;on&nbsp;another&nbsp;state&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;crow::Frame::DATA:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;incoming_data_packet(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;crow::Frame::REFUSE:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;u.f._state&nbsp;=&nbsp;CROW_CHANNEL_DISCONNECTED;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BUG();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::release(pack);<br>
}<br>
<br>
void&nbsp;crow::channel::incoming_data_packet(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;incoming_handler(this,&nbsp;pack);<br>
}<br>
<br>
void&nbsp;crow::channel::undelivered_packet(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;notify_one(-1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;u.f._state&nbsp;=&nbsp;CROW_CHANNEL_DISCONNECTED;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::release(pack);<br>
}<br>
<br>
void&nbsp;crow::channel::handshake(const&nbsp;uint8_t&nbsp;*raddr_ptr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;raddr_len,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nodeid_t&nbsp;rid,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::node_subheader&nbsp;sh_node;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::subheader_channel&nbsp;sh_channel;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::subheader_handshake&nbsp;sh_handshake;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_node.sid&nbsp;=&nbsp;id;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_node.rid&nbsp;=&nbsp;this-&gt;rid&nbsp;=&nbsp;rid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_node.u.f.type&nbsp;=&nbsp;CROW_NODEPACK_COMMON;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_channel.frame_id&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_channel.ftype&nbsp;=&nbsp;crow::Frame::HANDSHAKE_REQUEST;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_handshake.qos&nbsp;=&nbsp;this-&gt;qos&nbsp;=&nbsp;qos;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_handshake.ackquant&nbsp;=&nbsp;this-&gt;ackquant&nbsp;=&nbsp;ackquant;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::buffer&nbsp;vec[]&nbsp;=&nbsp;{{(char&nbsp;*)&amp;sh_node,&nbsp;sizeof(sh_node)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(char&nbsp;*)&amp;sh_channel,&nbsp;sizeof(sh_channel)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(char&nbsp;*)&amp;sh_handshake,&nbsp;sizeof(sh_handshake)}};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;u.f._state&nbsp;=&nbsp;CROW_CHANNEL_WAIT_HANDSHAKE_ANSWER;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//_state&nbsp;=&nbsp;crow::State::CONNECTED;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::send_v({raddr_ptr,&nbsp;raddr_len},&nbsp;vec,&nbsp;sizeof(vec)&nbsp;/&nbsp;sizeof(nos::buffer),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CROW_NODE_PROTOCOL,&nbsp;2,&nbsp;ackquant);<br>
}<br>
<br>
void&nbsp;crow::channel::send_handshake_answer()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::node_subheader&nbsp;sh_node;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::subheader_channel&nbsp;sh_channel;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::subheader_handshake&nbsp;sh_handshake;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_node.sid&nbsp;=&nbsp;id;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_node.rid&nbsp;=&nbsp;rid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_node.u.f.type&nbsp;=&nbsp;CROW_NODEPACK_COMMON;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_channel.frame_id&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_channel.ftype&nbsp;=&nbsp;crow::Frame::HANDSHAKE_ANSWER;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_handshake.qos&nbsp;=&nbsp;this-&gt;qos;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_handshake.ackquant&nbsp;=&nbsp;this-&gt;ackquant;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::buffer&nbsp;vec[]&nbsp;=&nbsp;{{(char&nbsp;*)&amp;sh_node,&nbsp;sizeof(sh_node)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(char&nbsp;*)&amp;sh_channel,&nbsp;sizeof(sh_channel)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(char&nbsp;*)&amp;sh_handshake,&nbsp;sizeof(sh_handshake)}};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//_state&nbsp;=&nbsp;crow::State::CONNECTED;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::send_v({raddr_ptr,&nbsp;raddr_len},&nbsp;vec,&nbsp;sizeof(vec)&nbsp;/&nbsp;sizeof(nos::buffer),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CROW_NODE_PROTOCOL,&nbsp;2,&nbsp;ackquant);<br>
}<br>
<br>
int&nbsp;crow::channel::send(const&nbsp;char&nbsp;*data,&nbsp;size_t&nbsp;size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(u.f._state&nbsp;!=&nbsp;CROW_CHANNEL_CONNECTED)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;CROW_CHANNEL_ERR_NOCONNECT;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::node_subheader&nbsp;sh_node;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::subheader_channel&nbsp;sh_channel;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_node.sid&nbsp;=&nbsp;this-&gt;id;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_node.rid&nbsp;=&nbsp;this-&gt;rid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_node.u.f.type&nbsp;=&nbsp;CROW_NODEPACK_COMMON;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_channel.frame_id&nbsp;=&nbsp;this-&gt;fid++;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh_channel.ftype&nbsp;=&nbsp;crow::Frame::DATA;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::buffer&nbsp;vec[]&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(char&nbsp;*)&amp;sh_node,&nbsp;sizeof(sh_node)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(char&nbsp;*)&amp;sh_channel,&nbsp;sizeof(sh_channel)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(char&nbsp;*)data,&nbsp;size},<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::send_v({this-&gt;raddr_ptr,&nbsp;this-&gt;raddr_len},&nbsp;vec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(vec)&nbsp;/&nbsp;sizeof(nos::buffer),&nbsp;CROW_NODE_PROTOCOL,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;qos,&nbsp;this-&gt;ackquant);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
nos::buffer&nbsp;crow::channel::getdata(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nos::buffer(pack-&gt;dataptr()&nbsp;+&nbsp;sizeof(crow::node_subheader)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::subheader_channel),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;datasize()&nbsp;-&nbsp;sizeof(crow::node_subheader)&nbsp;-<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::subheader_channel));<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
