<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/proto/msgbox.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/proto/msgbox.h&gt;<br>
<br>
crow::msgbox::msgbox()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;igris_sem_init(&amp;message_lock,&nbsp;0,&nbsp;1);<br>
}<br>
<br>
crow::node_packet_ptr&nbsp;crow::msgbox::query(nodeid_t&nbsp;rid,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;data,&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(dlist_empty(&amp;messages));<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;ptr&nbsp;=&nbsp;send(rid,&nbsp;addr,&nbsp;data,&nbsp;qos,&nbsp;ackquant);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;receive();<br>
}<br>
<br>
crow::node_packet_ptr&nbsp;crow::msgbox::receive()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;igris_sem_wait(&amp;message_lock);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(dlist_empty(&amp;messages))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris_sem_post(&amp;message_lock);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Тут&nbsp;должна&nbsp;быть&nbsp;проверка&nbsp;на&nbsp;то&nbsp;что&nbsp;сообщение&nbsp;не&nbsp;пришло,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;пока&nbsp;мы&nbsp;были&nbsp;между&nbsp;отпущенным&nbsp;семафором&nbsp;и&nbsp;waitevent<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;тоесть,&nbsp;нужен&nbsp;специальный&nbsp;вариант&nbsp;waitevent<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;sts&nbsp;=&nbsp;waitevent();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sts&nbsp;==&nbsp;-1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris_sem_wait(&amp;message_lock);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;dlist_first_entry(&amp;messages,&nbsp;crow::packet,&nbsp;ulnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_del_init(&amp;pack-&gt;ulnk);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;igris_sem_post(&amp;message_lock);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;crow::node_packet_ptr(pack,&nbsp;this);<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::msgbox::reply(crow::node_packet_ptr&nbsp;msg,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::buffer&nbsp;data,&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;send(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;msg.rid(),&nbsp;{msg-&gt;addrptr(),&nbsp;msg-&gt;addrsize()},&nbsp;data,&nbsp;qos,&nbsp;ackquant);<br>
}<br>
<br>
void&nbsp;crow::msgbox::incoming_packet(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;igris_sem_wait(&amp;message_lock);<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlist_add_tail(&amp;pack-&gt;ulnk,&nbsp;&amp;messages);<br>
&nbsp;&nbsp;&nbsp;&nbsp;igris_sem_post(&amp;message_lock);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;notify_one(0);<br>
}<br>
<br>
void&nbsp;crow::msgbox::undelivered_packet(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)pack;<br>
&nbsp;&nbsp;&nbsp;&nbsp;notify_one(-1);<br>
}<br>
<br>
crow::msgbox::~msgbox()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;igris_sem_wait(&amp;message_lock);<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(!dlist_empty(&amp;messages))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;dlist_first_entry(&amp;messages,&nbsp;crow::packet,&nbsp;ulnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del_init(&amp;pack-&gt;ulnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;igris_sem_post(&amp;message_lock);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
