<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/proto/node_protocol.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#ifndef&nbsp;CROW_NODE_PROTOCOL_H<br>
#define&nbsp;CROW_NODE_PROTOCOL_H<br>
<br>
#include&nbsp;&lt;crow/proto/protocol.h&gt;<br>
#include&nbsp;&lt;igris/container/dlist.h&gt;<br>
#include&nbsp;&lt;unordered_map&gt;<br>
#include&nbsp;&lt;vector&gt;<br>
#include&nbsp;&lt;cstdint&gt;<br>
<br>
namespace&nbsp;crow<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;class&nbsp;Tower;&nbsp;//&nbsp;Forward&nbsp;declaration<br>
&nbsp;&nbsp;&nbsp;&nbsp;using&nbsp;nodeid_t&nbsp;=&nbsp;uint16_t;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;node_subheader<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nodeid_t&nbsp;sid&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nodeid_t&nbsp;rid&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;union&nbsp;_u<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;flags;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;_f<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;has_more&nbsp;:&nbsp;1;&nbsp;&nbsp;//&nbsp;more&nbsp;chunks&nbsp;follow<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;chunked&nbsp;:&nbsp;1;&nbsp;&nbsp;&nbsp;//&nbsp;this&nbsp;is&nbsp;a&nbsp;chunked&nbsp;message<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;reserved&nbsp;:&nbsp;2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;type&nbsp;:&nbsp;4;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;f;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;u&nbsp;=&nbsp;{};<br>
&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;__attribute__((packed));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Chunk&nbsp;header&nbsp;follows&nbsp;node_subheader&nbsp;when&nbsp;chunked=1<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Format:&nbsp;[chunk_id:2&nbsp;bytes&nbsp;LE]<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;node_chunk_header<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;chunk_id&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;__attribute__((packed));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Constants&nbsp;for&nbsp;chunked&nbsp;protocol<br>
&nbsp;&nbsp;&nbsp;&nbsp;inline&nbsp;constexpr&nbsp;size_t&nbsp;NODE_CHUNK_HEADER_SIZE&nbsp;=&nbsp;sizeof(node_chunk_header);<br>
&nbsp;&nbsp;&nbsp;&nbsp;inline&nbsp;constexpr&nbsp;size_t&nbsp;NODE_DEFAULT_MAX_MESSAGE_SIZE&nbsp;=&nbsp;64&nbsp;*&nbsp;1024;&nbsp;&nbsp;//&nbsp;64&nbsp;KiB<br>
&nbsp;&nbsp;&nbsp;&nbsp;inline&nbsp;constexpr&nbsp;uint32_t&nbsp;NODE_DEFAULT_REASSEMBLY_TIMEOUT_MS&nbsp;=&nbsp;5000;&nbsp;&nbsp;//&nbsp;5&nbsp;seconds<br>
&nbsp;&nbsp;&nbsp;&nbsp;inline&nbsp;constexpr&nbsp;uint16_t&nbsp;NODE_MAX_CHUNKS&nbsp;=&nbsp;1024;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Get&nbsp;data&nbsp;portion&nbsp;of&nbsp;a&nbsp;node&nbsp;packet&nbsp;(excluding&nbsp;headers)<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;inline&nbsp;nos::buffer&nbsp;node_data(crow::packet&nbsp;*pack)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*sh&nbsp;=&nbsp;(node_subheader&nbsp;*)pack-&gt;dataptr();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;header_size&nbsp;=&nbsp;sizeof(node_subheader);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sh-&gt;u.f.chunked)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header_size&nbsp;+=&nbsp;NODE_CHUNK_HEADER_SIZE;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nos::buffer(pack-&gt;dataptr()&nbsp;+&nbsp;header_size,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;datasize()&nbsp;-&nbsp;header_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Key&nbsp;for&nbsp;identifying&nbsp;a&nbsp;reassembly&nbsp;session<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;reassembly_key<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nodeid_t&nbsp;rid;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;destination&nbsp;node<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nodeid_t&nbsp;sid;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;source&nbsp;node<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint64_t&nbsp;addr_hash;&nbsp;&nbsp;//&nbsp;hash&nbsp;of&nbsp;source&nbsp;address<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;operator==(const&nbsp;reassembly_key&nbsp;&amp;o)&nbsp;const<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;rid&nbsp;==&nbsp;o.rid&nbsp;&amp;&amp;&nbsp;sid&nbsp;==&nbsp;o.sid&nbsp;&amp;&amp;&nbsp;addr_hash&nbsp;==&nbsp;o.addr_hash;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
}<br>
<br>
//&nbsp;Hash&nbsp;specialization&nbsp;for&nbsp;reassembly_key<br>
namespace&nbsp;std<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;template&nbsp;&lt;&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;hash&lt;crow::reassembly_key&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;operator()(const&nbsp;crow::reassembly_key&nbsp;&amp;k)&nbsp;const<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;FNV-1a&nbsp;constants&nbsp;depend&nbsp;on&nbsp;platform&nbsp;word&nbsp;size<br>
#if&nbsp;SIZE_MAX&nbsp;==&nbsp;0xFFFFFFFFFFFFFFFFULL<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;64-bit&nbsp;platform<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;constexpr&nbsp;size_t&nbsp;fnv_offset&nbsp;=&nbsp;14695981039346656037ULL;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;constexpr&nbsp;size_t&nbsp;fnv_prime&nbsp;=&nbsp;1099511628211ULL;<br>
#else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;32-bit&nbsp;platform<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;constexpr&nbsp;size_t&nbsp;fnv_offset&nbsp;=&nbsp;2166136261U;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;constexpr&nbsp;size_t&nbsp;fnv_prime&nbsp;=&nbsp;16777619U;<br>
#endif<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;h&nbsp;=&nbsp;fnv_offset;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;h&nbsp;^=&nbsp;k.rid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;h&nbsp;*=&nbsp;fnv_prime;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;h&nbsp;^=&nbsp;k.sid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;h&nbsp;*=&nbsp;fnv_prime;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;h&nbsp;^=&nbsp;static_cast&lt;size_t&gt;(k.addr_hash);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;h&nbsp;*=&nbsp;fnv_prime;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;h;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
}<br>
<br>
namespace&nbsp;crow<br>
{<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Buffer&nbsp;for&nbsp;reassembling&nbsp;chunked&nbsp;messages<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;reassembly_buffer<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::unordered_map&lt;uint16_t,&nbsp;crow::packet&nbsp;*&gt;&nbsp;chunks;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;expected_chunks&nbsp;=&nbsp;0;&nbsp;&nbsp;//&nbsp;0&nbsp;=&nbsp;unknown&nbsp;(last&nbsp;chunk&nbsp;not&nbsp;yet&nbsp;received)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint64_t&nbsp;start_time_ms&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;total_payload_size&nbsp;=&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;is_complete()&nbsp;const<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(expected_chunks&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;chunks.size()&nbsp;==&nbsp;expected_chunks;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Assemble&nbsp;all&nbsp;chunks&nbsp;into&nbsp;a&nbsp;new&nbsp;packet<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Returns&nbsp;nullptr&nbsp;on&nbsp;failure<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*assemble(Tower&nbsp;&amp;tower);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Release&nbsp;all&nbsp;held&nbsp;packets<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;release_all();<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;class&nbsp;node_protocol_cls&nbsp;:&nbsp;public&nbsp;crow::protocol<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;private:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::unordered_map&lt;reassembly_key,&nbsp;reassembly_buffer&gt;&nbsp;_reassembly;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;_max_message_size&nbsp;=&nbsp;NODE_DEFAULT_MAX_MESSAGE_SIZE;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;_reassembly_timeout_ms&nbsp;=&nbsp;NODE_DEFAULT_REASSEMBLY_TIMEOUT_MS;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;_debug&nbsp;=&nbsp;false;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;send_node_error(crow::packet&nbsp;*pack,&nbsp;int&nbsp;errcode,&nbsp;Tower&nbsp;&amp;tower);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;deliver_to_node(crow::packet&nbsp;*pack,&nbsp;Tower&nbsp;&amp;tower);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;handle_chunk(crow::packet&nbsp;*pack,&nbsp;Tower&nbsp;&amp;tower);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;cleanup_stale_buffers(uint64_t&nbsp;now_ms);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;uint64_t&nbsp;hash_address(const&nbsp;uint8_t&nbsp;*addr,&nbsp;size_t&nbsp;len);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;incoming(crow::packet&nbsp;*pack,&nbsp;Tower&nbsp;&amp;tower)&nbsp;override;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;undelivered(crow::packet&nbsp;*pack,&nbsp;Tower&nbsp;&amp;tower)&nbsp;override;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;delivered(crow::packet&nbsp;*pack,&nbsp;Tower&nbsp;&amp;tower);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node_protocol_cls()&nbsp;{}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Configuration<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;set_max_message_size(size_t&nbsp;size)&nbsp;{&nbsp;_max_message_size&nbsp;=&nbsp;size;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;max_message_size()&nbsp;const&nbsp;{&nbsp;return&nbsp;_max_message_size;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;set_reassembly_timeout(uint32_t&nbsp;ms)&nbsp;{&nbsp;_reassembly_timeout_ms&nbsp;=&nbsp;ms;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;reassembly_timeout()&nbsp;const&nbsp;{&nbsp;return&nbsp;_reassembly_timeout_ms;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;set_debug(bool&nbsp;debug)&nbsp;{&nbsp;_debug&nbsp;=&nbsp;debug;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;debug()&nbsp;const&nbsp;{&nbsp;return&nbsp;_debug;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Statistics<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;reassembly_sessions_count()&nbsp;const&nbsp;{&nbsp;return&nbsp;_reassembly.size();&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;auto&nbsp;sid(crow::packet&nbsp;*pack)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;((node_subheader&nbsp;*)(pack-&gt;dataptr()))-&gt;sid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;auto&nbsp;rid(crow::packet&nbsp;*pack)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;((node_subheader&nbsp;*)(pack-&gt;dataptr()))-&gt;rid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;auto&nbsp;get_error_code(crow::packet&nbsp;*pack)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*(int&nbsp;*)(node_data(pack).data());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
&nbsp;&nbsp;&nbsp;&nbsp;extern&nbsp;node_protocol_cls&nbsp;node_protocol;<br>
}<br>
<br>
#endif<br>
<!-- END SCAT CODE -->
</body>
</html>
