<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/proto/node.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/defs.h&gt;<br>
#include&nbsp;&lt;crow/proto/node.h&gt;<br>
#include&nbsp;&lt;crow/tower.h&gt;<br>
<br>
#include&nbsp;&lt;crow/print.h&gt;<br>
#include&nbsp;&lt;igris/sync/syslock.h&gt;<br>
#include&nbsp;&lt;igris/util/numconvert.h&gt;<br>
<br>
#include&nbsp;&lt;nos/print.h&gt;<br>
<br>
igris::dlist&lt;crow::node,&nbsp;&amp;crow::node::lnk&gt;&nbsp;crow::nodes_list;<br>
crow::node_protocol_cls&nbsp;crow::node_protocol;<br>
<br>
crow::packet_ptr&nbsp;crow::node::send(nodeid_t&nbsp;sid,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nodeid_t&nbsp;rid,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;data,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::node_subheader&nbsp;sh;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.sid&nbsp;=&nbsp;sid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.rid&nbsp;=&nbsp;rid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.u.f.type&nbsp;=&nbsp;CROW_NODEPACK_COMMON;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;iov[2]&nbsp;=&nbsp;{{(char&nbsp;*)&amp;sh,&nbsp;sizeof(sh)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(char&nbsp;*)data.data(),&nbsp;data.size()}};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;crow::send_v(addr,&nbsp;iov,&nbsp;2,&nbsp;CROW_NODE_PROTOCOL,&nbsp;qos,&nbsp;ackquant,&nbsp;async);<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::node::send_v(nodeid_t&nbsp;sid,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nodeid_t&nbsp;rid,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::node_subheader&nbsp;sh;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.sid&nbsp;=&nbsp;sid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.rid&nbsp;=&nbsp;rid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.u.f.type&nbsp;=&nbsp;CROW_NODEPACK_COMMON;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;iov[1]&nbsp;=&nbsp;{{(char&nbsp;*)&amp;sh,&nbsp;sizeof(sh)}};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;crow::send_vv(addr,&nbsp;iov,&nbsp;1,&nbsp;vec,&nbsp;veclen,&nbsp;CROW_NODE_PROTOCOL,&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ackquant,&nbsp;async);<br>
}<br>
<br>
crow::packet_ptr&nbsp;crow::node::send_vv(nodeid_t&nbsp;sid,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nodeid_t&nbsp;rid,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec1,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen1,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::node_subheader&nbsp;sh;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.sid&nbsp;=&nbsp;sid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.rid&nbsp;=&nbsp;rid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.u.f.type&nbsp;=&nbsp;CROW_NODEPACK_COMMON;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;iov[1]&nbsp;=&nbsp;{{(char&nbsp;*)&amp;sh,&nbsp;sizeof(sh)}};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;crow::send_vvv(addr,&nbsp;iov,&nbsp;1,&nbsp;vec1,&nbsp;veclen1,&nbsp;vec2,&nbsp;veclen2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CROW_NODE_PROTOCOL,&nbsp;qos,&nbsp;ackquant,&nbsp;async);<br>
}<br>
<br>
void&nbsp;crow::__link_node(crow::node&nbsp;*srv,&nbsp;uint16_t&nbsp;id)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;srv-&gt;id&nbsp;=&nbsp;id;<br>
&nbsp;&nbsp;&nbsp;&nbsp;nodes_list.move_back(*srv);<br>
}<br>
<br>
crow::node&nbsp;*crow::find_node(size_t&nbsp;id)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;TODO:&nbsp;переделать&nbsp;на&nbsp;хештаблицу<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;node&nbsp;:&nbsp;nodes_list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(node.id&nbsp;==&nbsp;id)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&amp;node;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
}<br>
<br>
void&nbsp;crow::bind_node_dynamic(crow::node&nbsp;*srv)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Динамические&nbsp;порты&nbsp;располагаются&nbsp;в&nbsp;верхнем&nbsp;полупространстве.<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;nodeid_t&nbsp;counter&nbsp;=&nbsp;1&nbsp;&lt;&lt;&nbsp;(sizeof(nodeid_t)&nbsp;*&nbsp;8&nbsp;-&nbsp;1);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;do<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;counter++;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(counter&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;counter&nbsp;=&nbsp;(1&nbsp;&lt;&lt;&nbsp;(sizeof(nodeid_t)&nbsp;*&nbsp;8&nbsp;-&nbsp;1));<br>
&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;while&nbsp;(crow::find_node(counter)&nbsp;!=&nbsp;nullptr);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;__link_node(srv,&nbsp;counter);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
crow::node::~node()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!waitlnk.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;notify_all(-1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;lnk.unlink();<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
crow::alived_object::~alived_object()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;keepalive_timer.unplan();<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;crow::node_keepalive_timer::execute()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;alived_object&nbsp;&amp;n&nbsp;=&nbsp;*mcast_out(this,&nbsp;alived_object,&nbsp;keepalive_timer);<br>
&nbsp;&nbsp;&nbsp;&nbsp;n.keepalive_handle();<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
