<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/proto/node_protocol.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/proto/node.h&gt;<br>
#include&nbsp;&lt;crow/proto/node_protocol.h&gt;<br>
#include&nbsp;&lt;crow/tower_cls.h&gt;<br>
#include&nbsp;&lt;crow/warn.h&gt;<br>
#include&nbsp;&lt;igris/time/systime.h&gt;<br>
#include&nbsp;&lt;nos/fprint.h&gt;<br>
#include&nbsp;&lt;vector&gt;<br>
<br>
//&nbsp;============================================================================<br>
//&nbsp;reassembly_buffer&nbsp;implementation<br>
//&nbsp;============================================================================<br>
<br>
void&nbsp;crow::reassembly_buffer::release_all()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;pair&nbsp;:&nbsp;chunks)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pair.second)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::Tower::release(pair.second);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;chunks.clear();<br>
&nbsp;&nbsp;&nbsp;&nbsp;expected_chunks&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;total_payload_size&nbsp;=&nbsp;0;<br>
}<br>
<br>
crow::packet&nbsp;*crow::reassembly_buffer::assemble(Tower&nbsp;&amp;tower)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_complete())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Calculate&nbsp;total&nbsp;data&nbsp;size<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;total_size&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;pair&nbsp;:&nbsp;chunks)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;total_size&nbsp;+=&nbsp;node_data(pair.second).size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Get&nbsp;first&nbsp;chunk&nbsp;for&nbsp;header&nbsp;info<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*first_chunk&nbsp;=&nbsp;chunks[0];<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;first_sh&nbsp;=&nbsp;first_chunk-&gt;subheader&lt;node_subheader&gt;();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Create&nbsp;new&nbsp;packet&nbsp;with&nbsp;assembled&nbsp;data<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Use&nbsp;same&nbsp;address&nbsp;as&nbsp;first&nbsp;chunk<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*assembled&nbsp;=&nbsp;crow::allocate_packet&lt;crow::header_v1&gt;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;first_chunk-&gt;addrsize(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(node_subheader)&nbsp;+&nbsp;total_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!assembled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::warn(&quot;Failed&nbsp;to&nbsp;allocate&nbsp;assembled&nbsp;packet&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Copy&nbsp;address&nbsp;from&nbsp;first&nbsp;chunk<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(assembled-&gt;addrptr(),&nbsp;first_chunk-&gt;addrptr(),&nbsp;first_chunk-&gt;addrsize());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Copy&nbsp;header&nbsp;from&nbsp;first&nbsp;chunk&nbsp;(without&nbsp;chunked&nbsp;flags)<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;new_sh&nbsp;=&nbsp;assembled-&gt;subheader&lt;node_subheader&gt;();<br>
&nbsp;&nbsp;&nbsp;&nbsp;new_sh.sid&nbsp;=&nbsp;first_sh.sid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;new_sh.rid&nbsp;=&nbsp;first_sh.rid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;new_sh.u.f.type&nbsp;=&nbsp;first_sh.u.f.type;<br>
&nbsp;&nbsp;&nbsp;&nbsp;new_sh.u.f.chunked&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;new_sh.u.f.has_more&nbsp;=&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Copy&nbsp;QoS&nbsp;and&nbsp;other&nbsp;settings&nbsp;from&nbsp;first&nbsp;chunk<br>
&nbsp;&nbsp;&nbsp;&nbsp;assembled-&gt;set_quality(first_chunk-&gt;quality());<br>
&nbsp;&nbsp;&nbsp;&nbsp;assembled-&gt;set_ackquant(first_chunk-&gt;ackquant());<br>
&nbsp;&nbsp;&nbsp;&nbsp;assembled-&gt;ingate&nbsp;=&nbsp;first_chunk-&gt;ingate;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Assemble&nbsp;payload&nbsp;in&nbsp;order<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;*dest&nbsp;=&nbsp;assembled-&gt;dataptr()&nbsp;+&nbsp;sizeof(node_subheader);<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(uint16_t&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;expected_chunks;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;payload&nbsp;=&nbsp;node_data(chunks[i]);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(dest,&nbsp;payload.data(),&nbsp;payload.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dest&nbsp;+=&nbsp;payload.size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Release&nbsp;all&nbsp;chunk&nbsp;packets<br>
&nbsp;&nbsp;&nbsp;&nbsp;release_all();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;assembled;<br>
}<br>
<br>
//&nbsp;============================================================================<br>
//&nbsp;node_protocol_cls&nbsp;implementation<br>
//&nbsp;============================================================================<br>
<br>
uint64_t&nbsp;crow::node_protocol_cls::hash_address(const&nbsp;uint8_t&nbsp;*addr,&nbsp;size_t&nbsp;len)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Simple&nbsp;FNV-1a&nbsp;hash<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint64_t&nbsp;hash&nbsp;=&nbsp;14695981039346656037ULL;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(size_t&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;len;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hash&nbsp;^=&nbsp;addr[i];<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hash&nbsp;*=&nbsp;1099511628211ULL;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;hash;<br>
}<br>
<br>
void&nbsp;crow::node_protocol_cls::cleanup_stale_buffers(uint64_t&nbsp;now_ms)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Collect&nbsp;keys&nbsp;to&nbsp;erase&nbsp;to&nbsp;avoid&nbsp;iterator&nbsp;ABI&nbsp;issues<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;reassembly_key&gt;&nbsp;to_erase;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;pair&nbsp;:&nbsp;_reassembly)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(now_ms&nbsp;-&nbsp;pair.second.start_time_ms&nbsp;&gt;&nbsp;_reassembly_timeout_ms)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;node_protocol:&nbsp;reassembly&nbsp;timeout&nbsp;for&nbsp;sid={}&nbsp;rid={}&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pair.first.sid,&nbsp;pair.first.rid);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pair.second.release_all();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_erase.push_back(pair.first);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;auto&nbsp;&amp;key&nbsp;:&nbsp;to_erase)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_reassembly.erase(key);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::node_protocol_cls::handle_chunk(crow::packet&nbsp;*pack,&nbsp;Tower&nbsp;&amp;tower)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;sh&nbsp;=&nbsp;pack-&gt;subheader&lt;node_subheader&gt;();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*chunk_hdr&nbsp;=&nbsp;(node_chunk_header&nbsp;*)(pack-&gt;dataptr()&nbsp;+&nbsp;sizeof(node_subheader));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;chunk_id&nbsp;=&nbsp;chunk_hdr-&gt;chunk_id;<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;has_more&nbsp;=&nbsp;sh.u.f.has_more;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;node_protocol:&nbsp;handle_chunk&nbsp;chunk_id={}&nbsp;has_more={}&nbsp;payload_size={}&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chunk_id,&nbsp;has_more,&nbsp;node_data(pack).size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Validate&nbsp;chunk_id<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(chunk_id&nbsp;&gt;=&nbsp;NODE_MAX_CHUNKS)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;node_protocol:&nbsp;chunk_id&nbsp;{}&nbsp;exceeds&nbsp;limit&quot;,&nbsp;chunk_id);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tower::release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Build&nbsp;reassembly&nbsp;key<br>
&nbsp;&nbsp;&nbsp;&nbsp;reassembly_key&nbsp;key;<br>
&nbsp;&nbsp;&nbsp;&nbsp;key.rid&nbsp;=&nbsp;sh.rid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;key.sid&nbsp;=&nbsp;sh.sid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;key.addr_hash&nbsp;=&nbsp;hash_address(pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint64_t&nbsp;now_ms&nbsp;=&nbsp;igris::millis();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Cleanup&nbsp;stale&nbsp;buffers&nbsp;periodically<br>
&nbsp;&nbsp;&nbsp;&nbsp;cleanup_stale_buffers(now_ms);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Get&nbsp;or&nbsp;create&nbsp;reassembly&nbsp;buffer<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;buffer&nbsp;=&nbsp;_reassembly[key];<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(buffer.chunks.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buffer.start_time_ms&nbsp;=&nbsp;now_ms;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Check&nbsp;for&nbsp;duplicate&nbsp;chunk<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(buffer.chunks.count(chunk_id))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Duplicate&nbsp;-&nbsp;release&nbsp;old,&nbsp;keep&nbsp;new&nbsp;(in&nbsp;case&nbsp;of&nbsp;retransmit)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tower::release(buffer.chunks[chunk_id]);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Store&nbsp;chunk<br>
&nbsp;&nbsp;&nbsp;&nbsp;buffer.chunks[chunk_id]&nbsp;=&nbsp;pack;<br>
&nbsp;&nbsp;&nbsp;&nbsp;buffer.total_payload_size&nbsp;+=&nbsp;node_data(pack).size();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;node_protocol:&nbsp;stored&nbsp;chunk&nbsp;{},&nbsp;have&nbsp;{}&nbsp;chunks,&nbsp;expected={}&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chunk_id,&nbsp;buffer.chunks.size(),&nbsp;buffer.expected_chunks);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Check&nbsp;max&nbsp;message&nbsp;size<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(buffer.total_payload_size&nbsp;&gt;&nbsp;_max_message_size)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;node_protocol:&nbsp;message&nbsp;size&nbsp;{}&nbsp;exceeds&nbsp;limit&nbsp;{}&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buffer.total_payload_size,&nbsp;_max_message_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buffer.release_all();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_reassembly.erase(key);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;If&nbsp;this&nbsp;is&nbsp;the&nbsp;last&nbsp;chunk,&nbsp;we&nbsp;now&nbsp;know&nbsp;total&nbsp;count<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!has_more)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buffer.expected_chunks&nbsp;=&nbsp;chunk_id&nbsp;+&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Try&nbsp;to&nbsp;assemble<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(buffer.is_complete())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;node_protocol:&nbsp;assembling&nbsp;{}&nbsp;chunks,&nbsp;total_payload={}&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buffer.expected_chunks,&nbsp;buffer.total_payload_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*assembled&nbsp;=&nbsp;buffer.assemble(tower);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_reassembly.erase(key);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(assembled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;node_protocol:&nbsp;assembled&nbsp;packet&nbsp;datasize={}&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assembled-&gt;datasize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;deliver_to_node(assembled,&nbsp;tower);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::node_protocol_cls::deliver_to_node(crow::packet&nbsp;*pack,&nbsp;Tower&nbsp;&amp;tower)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;sh&nbsp;=&nbsp;pack-&gt;subheader&lt;node_subheader&gt;();<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::node&nbsp;*srv&nbsp;=&nbsp;nullptr;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(crow::node&nbsp;&amp;srvs&nbsp;:&nbsp;crow::nodes_list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(srvs.id&nbsp;==&nbsp;sh.rid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;srv&nbsp;=&nbsp;&amp;srvs;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(srv&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;node_protocol:&nbsp;no&nbsp;node&nbsp;for&nbsp;rid={}&quot;,&nbsp;sh.rid);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;send_node_error(pack,&nbsp;CROW_ERRNO_UNREGISTRED_RID,&nbsp;tower);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tower::release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;node_protocol:&nbsp;deliver_to_node&nbsp;rid={}&nbsp;type={}&nbsp;datasize={}&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sh.rid,&nbsp;sh.u.f.type,&nbsp;pack-&gt;datasize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(sh.u.f.type)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;CROW_NODEPACK_COMMON:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;srv-&gt;incoming_packet(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;CROW_NODEPACK_ERROR:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;srv-&gt;notify_one(get_error_code(pack));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tower::release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::node_protocol_cls::send_node_error(crow::packet&nbsp;*pack,&nbsp;int&nbsp;errcode,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tower&nbsp;&amp;tower)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::node_subheader&nbsp;sh;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.sid&nbsp;=&nbsp;crow::node_protocol.rid(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.rid&nbsp;=&nbsp;crow::node_protocol.sid(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.u.f.type&nbsp;=&nbsp;CROW_NODEPACK_ERROR;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.u.f.chunked&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.u.f.has_more&nbsp;=&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;iov[2]&nbsp;=&nbsp;{{(char&nbsp;*)&amp;sh,&nbsp;sizeof(sh)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(char&nbsp;*)&amp;errcode,&nbsp;sizeof(errcode)}};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;tower.send_v({pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize()},&nbsp;iov,&nbsp;2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CROW_NODE_PROTOCOL,&nbsp;0,&nbsp;pack-&gt;ackquant(),&nbsp;true);<br>
}<br>
<br>
void&nbsp;crow::node_protocol_cls::incoming(crow::packet&nbsp;*pack,&nbsp;Tower&nbsp;&amp;tower)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;sh&nbsp;=&nbsp;pack-&gt;subheader&lt;node_subheader&gt;();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_debug)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;node_protocol:&nbsp;incoming&nbsp;sid={}&nbsp;rid={}&nbsp;chunked={}&nbsp;has_more={}&nbsp;datasize={}&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sh.sid,&nbsp;sh.rid,&nbsp;sh.u.f.chunked,&nbsp;sh.u.f.has_more,&nbsp;pack-&gt;datasize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Handle&nbsp;chunked&nbsp;messages<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sh.u.f.chunked)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;handle_chunk(pack,&nbsp;tower);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Non-chunked&nbsp;message&nbsp;-&nbsp;deliver&nbsp;directly<br>
&nbsp;&nbsp;&nbsp;&nbsp;deliver_to_node(pack,&nbsp;tower);<br>
}<br>
<br>
void&nbsp;crow::node_protocol_cls::undelivered(crow::packet&nbsp;*pack,&nbsp;Tower&nbsp;&amp;tower)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)tower;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::node_subheader&nbsp;*sh&nbsp;=&nbsp;(crow::node_subheader&nbsp;*)pack-&gt;dataptr();<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(crow::node&nbsp;&amp;srvs&nbsp;:&nbsp;crow::nodes_list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(srvs.id&nbsp;==&nbsp;sh-&gt;sid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;srvs.undelivered_packet(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;Tower::release(pack);<br>
}<br>
<br>
void&nbsp;crow::node_protocol_cls::delivered(crow::packet&nbsp;*pack,&nbsp;Tower&nbsp;&amp;tower)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)tower;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::node_subheader&nbsp;*sh&nbsp;=&nbsp;(crow::node_subheader&nbsp;*)pack-&gt;dataptr();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;srvs&nbsp;:&nbsp;crow::nodes_list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(srvs.id&nbsp;==&nbsp;sh-&gt;sid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;srvs.delivered_packet(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Tower::release(pack);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
