<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/gateway.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**&nbsp;@file&nbsp;*/<br>
<br>
#ifndef&nbsp;CROW_GATEWAY_H<br>
#define&nbsp;CROW_GATEWAY_H<br>
<br>
#include&nbsp;&lt;crow/packet.h&gt;<br>
#include&nbsp;&lt;igris/datastruct/dlist.h&gt;<br>
#include&nbsp;&lt;igris/sync/syslock.h&gt;<br>
<br>
struct&nbsp;crow_gateway;<br>
<br>
struct&nbsp;crow_gateway_operations<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;(*send)(struct&nbsp;crow_gateway&nbsp;*,&nbsp;crow::packet&nbsp;*);<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;(*deinit)(struct&nbsp;crow_gateway&nbsp;*);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;selector&nbsp;support&nbsp;operations<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;(*get_fds)(struct&nbsp;crow_gateway&nbsp;*,&nbsp;int&nbsp;*fds);<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;(*onestep)(struct&nbsp;crow_gateway&nbsp;*);<br>
};<br>
<br>
struct&nbsp;crow_gateway<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;dlist_head&nbsp;lnk;&nbsp;///&lt;&nbsp;встроенное&nbsp;поле&nbsp;списка.<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;struct&nbsp;crow_gateway_operations&nbsp;*ops;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;id;&nbsp;///&lt;&nbsp;номер&nbsp;врат.<br>
};<br>
<br>
extern&nbsp;struct&nbsp;dlist_head&nbsp;crow_gateway_list;<br>
<br>
__BEGIN_DECLS<br>
<br>
void&nbsp;crow_gateway_init(struct&nbsp;crow_gateway&nbsp;*gate,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;crow_gateway_operations&nbsp;*ops);<br>
<br>
int&nbsp;crow_gateway_bind(struct&nbsp;crow_gateway&nbsp;*gate,&nbsp;int&nbsp;no);<br>
<br>
void&nbsp;crow_gateway_deinit(struct&nbsp;crow_gateway&nbsp;*gate);<br>
<br>
struct&nbsp;crow_gateway&nbsp;*crow_get_gateway(int&nbsp;no);<br>
<br>
__END_DECLS<br>
<br>
/**<br>
&nbsp;&nbsp;&nbsp;&nbsp;@brief&nbsp;Абстрактный&nbsp;класс&nbsp;врат.&nbsp;Врата&nbsp;отвечают&nbsp;за&nbsp;пересылку&nbsp;пакетов<br>
&nbsp;&nbsp;&nbsp;&nbsp;между&nbsp;башнями.<br>
&nbsp;&nbsp;&nbsp;&nbsp;@details&nbsp;Может&nbsp;некоторое&nbsp;время&nbsp;хранить&nbsp;отправляемые&nbsp;пакеты.<br>
*/<br>
<br>
namespace&nbsp;crow<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;class&nbsp;gateway<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;dlist_head&nbsp;lnk&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DLIST_HEAD_INIT(lnk);&nbsp;///&lt;&nbsp;встроенное&nbsp;поле&nbsp;списка.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;id&nbsp;=&nbsp;0;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;///&lt;&nbsp;номер&nbsp;врат.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;virtual&nbsp;void&nbsp;send(crow::packet&nbsp;*)&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;virtual&nbsp;void&nbsp;finish()&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;virtual&nbsp;void&nbsp;nblock_onestep()&nbsp;{}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;bind(int&nbsp;gateno);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gateway()&nbsp;=&nbsp;default;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;virtual&nbsp;~gateway()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dlist_del(&amp;lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;gateway&nbsp;*get_gateway(int&nbsp;no);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;extern&nbsp;struct&nbsp;dlist_head&nbsp;gateway_list;<br>
}<br>
<br>
#endif<br>
<!-- END SCAT CODE -->
</body>
</html>
