<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/hostaddr_view.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**&nbsp;@file&nbsp;*/<br>
<br>
#ifndef&nbsp;CROW_HOSTADDR_VIEW_H<br>
#define&nbsp;CROW_HOSTADDR_VIEW_H<br>
<br>
#include&nbsp;&lt;nos/buffer.h&gt;<br>
<br>
#if&nbsp;__has_include(&lt;vector&gt;)<br>
#include&nbsp;&lt;vector&gt;<br>
#else<br>
namespace&nbsp;std<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;template&nbsp;&lt;class&nbsp;T,&nbsp;class&nbsp;Alloc&gt;&nbsp;class&nbsp;vector;<br>
}<br>
#endif<br>
<br>
namespace&nbsp;crow<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;class&nbsp;hostaddr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;class&nbsp;hostaddr_view<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;uint8_t&nbsp;*addr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;alen;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hostaddr_view()&nbsp;=&nbsp;default;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hostaddr_view(const&nbsp;hostaddr_view&nbsp;&amp;h)&nbsp;=&nbsp;default;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hostaddr_view&nbsp;&amp;operator=(const&nbsp;hostaddr_view&nbsp;&amp;h)&nbsp;=&nbsp;default;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hostaddr_view(const&nbsp;hostaddr&nbsp;&amp;h);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hostaddr_view(const&nbsp;nos::buffer&nbsp;&amp;v);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hostaddr_view(const&nbsp;uint8_t&nbsp;*addr,&nbsp;size_t&nbsp;alen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hostaddr_view(const&nbsp;char&nbsp;*addr,&nbsp;size_t&nbsp;alen);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hostaddr_view(const&nbsp;void&nbsp;*addr,&nbsp;size_t&nbsp;alen);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;template&nbsp;&lt;class&nbsp;Alloc&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hostaddr_view(const&nbsp;std::vector&lt;uint8_t,&nbsp;Alloc&gt;&nbsp;&amp;v);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;uint8_t&nbsp;*data()&nbsp;const;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;size()&nbsp;const;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;uint8_t&nbsp;*begin()&nbsp;const;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;uint8_t&nbsp;*end()&nbsp;const;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;operator==(nos::buffer&nbsp;buf)&nbsp;const;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;operator==(const&nbsp;hostaddr_view&nbsp;&amp;buf)&nbsp;const;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;operator&lt;(const&nbsp;hostaddr_view&nbsp;&amp;buf)&nbsp;const;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;to_string()&nbsp;const;<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
}<br>
<br>
template&nbsp;&lt;class&nbsp;Alloc&gt;<br>
crow::hostaddr_view::hostaddr_view(const&nbsp;std::vector&lt;uint8_t,&nbsp;Alloc&gt;&nbsp;&amp;v)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;addr(v.data()),&nbsp;alen(v.size())<br>
{<br>
}<br>
<br>
#endif<br>
<!-- END SCAT CODE -->
</body>
</html>
