<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/tower.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**&nbsp;@file&nbsp;*/<br>
<br>
#ifndef&nbsp;CROW_TOWER_H<br>
#define&nbsp;CROW_TOWER_H<br>
<br>
#include&nbsp;&lt;crow/defs.h&gt;<br>
#include&nbsp;&lt;crow/gateway.h&gt;<br>
#include&nbsp;&lt;crow/packet_ptr.h&gt;<br>
#include&nbsp;&lt;igris/event/delegate.h&gt;<br>
#include&nbsp;&lt;nos/buffer.h&gt;<br>
<br>
#define&nbsp;CROW_SENDED&nbsp;0<br>
#define&nbsp;CROW_WRONG_ADDRESS&nbsp;-1<br>
<br>
namespace&nbsp;crow<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;extern&nbsp;uint16_t&nbsp;debug_data_size;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;extern&nbsp;dlist_head&nbsp;protocols;<br>
&nbsp;&nbsp;&nbsp;&nbsp;extern&nbsp;bool&nbsp;diagnostic_noack;<br>
&nbsp;&nbsp;&nbsp;&nbsp;extern&nbsp;unsigned&nbsp;int&nbsp;total_travelled;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;extern&nbsp;void&nbsp;(*default_incoming_handler)(crow::packet&nbsp;*pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;extern&nbsp;void&nbsp;(*undelivered_handler)(crow::packet&nbsp;*pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;extern&nbsp;igris::delegate&lt;void&gt;&nbsp;unsleep_handler;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;extern&nbsp;bool&nbsp;retransling_allowed;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Передать&nbsp;пакет&nbsp;в&nbsp;обработку.<br>
&nbsp;&nbsp;&nbsp;&nbsp;packet_ptr&nbsp;travel(crow::packet&nbsp;*pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;nocontrol_travel(crow::packet&nbsp;*pack,&nbsp;bool&nbsp;fastsend);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Включить&nbsp;трассировку&nbsp;пакетов.<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;enable_diagnostic();<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;diagnostic_enabled();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Включить&nbsp;диагностику&nbsp;прохождения,&nbsp;жизни&nbsp;пакетов<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;diagnostic_setup(bool&nbsp;en);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Отправить&nbsp;пакет.<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet_ptr&nbsp;send(const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::buffer&nbsp;data,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async&nbsp;=&nbsp;false);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet_ptr&nbsp;send_v(const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async&nbsp;=&nbsp;false);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet_ptr&nbsp;send_vv(const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async&nbsp;=&nbsp;false);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet_ptr&nbsp;send_vvv(const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;*vec3,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;veclen3,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;async&nbsp;=&nbsp;false);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Эта&nbsp;функция&nbsp;вызывается&nbsp;вратами&nbsp;после&nbsp;обработки&nbsp;отсылаемого&nbsp;пакета.<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;return_to_tower(crow::packet&nbsp;*pack,&nbsp;uint8_t&nbsp;sts);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Используется&nbsp;пользовательским&nbsp;кодом&nbsp;для&nbsp;освобождения&nbsp;пакета.<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;release(crow::packet&nbsp;*pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;utilize(crow::packet&nbsp;*pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;onestep_travel_only();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;spin();<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;spin_with_select();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;stop_spin(bool&nbsp;wait&nbsp;=&nbsp;true);<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;start_spin_with_select();<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;start_spin_without_select();<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;start_spin();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;[[deprecated]]&nbsp;void&nbsp;spin_join();<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;join_spin();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;has_untravelled();<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;has_untravelled_now();<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;print_list_counts();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;fully_empty();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;int64_t&nbsp;get_minimal_timeout();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Завершить&nbsp;гейты.<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;finish();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;incomming_stage_count();<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;outers_stage_count();<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;unsleep();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;set_spin_cancel_token();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;spin_with_select_realtime(int&nbsp;abort_on_fault);<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;start_spin_with_select_realtime(int&nbsp;abort_on_fault);<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;start_spin_realtime(int&nbsp;abort_on_fault);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;tower_release(crow::packet&nbsp;*pack);<br>
}<br>
<br>
#endif<br>
<!-- END SCAT CODE -->
</body>
</html>
