<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/nodes/service_node.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/nodes/pubsub_defs.h&gt;<br>
#include&nbsp;&lt;crow/nodes/service_node.h&gt;<br>
#include&nbsp;&lt;crow/warn.h&gt;<br>
#include&nbsp;&lt;nos/print.h&gt;<br>
#include&nbsp;&lt;cstring&gt;<br>
<br>
void&nbsp;crow::service_node::incoming_packet(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;curpack&nbsp;=&nbsp;pack;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;subheader&nbsp;=&nbsp;pack-&gt;subheader&lt;consume_subheader&gt;();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;data&nbsp;=&nbsp;subheader.message();<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;reply_theme_length&nbsp;=&nbsp;data.data()[0];<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;message&nbsp;=&nbsp;nos::buffer{data.data()&nbsp;+&nbsp;1&nbsp;+&nbsp;reply_theme_length,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data.size()&nbsp;-&nbsp;1&nbsp;-&nbsp;reply_theme_length};<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlg(message.data(),&nbsp;message.size(),&nbsp;*this);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;release&nbsp;after&nbsp;reply<br>
&nbsp;&nbsp;&nbsp;&nbsp;_tower-&gt;release(pack);<br>
}<br>
<br>
//&nbsp;Static&nbsp;buffer&nbsp;for&nbsp;assembling&nbsp;chunked&nbsp;reply&nbsp;messages.<br>
//&nbsp;Size:&nbsp;max&nbsp;reply&nbsp;~4KB&nbsp;+&nbsp;headers.&nbsp;Single-threaded&nbsp;use&nbsp;assumed.<br>
static&nbsp;char&nbsp;service_reply_buffer[4096&nbsp;+&nbsp;64];<br>
<br>
void&nbsp;crow::service_node::reply(const&nbsp;char&nbsp;*answ,&nbsp;size_t&nbsp;size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;subheader&nbsp;=&nbsp;curpack-&gt;subheader&lt;consume_subheader&gt;();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;data&nbsp;=&nbsp;subheader.message();<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;reply_theme_length&nbsp;=&nbsp;data.data()[0];<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;reply_theme&nbsp;=&nbsp;nos::buffer(data.data()&nbsp;+&nbsp;1,&nbsp;reply_theme_length);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(reply_theme&nbsp;==&nbsp;&quot;__noanswer__&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Build&nbsp;pubsub&nbsp;header<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::publish_subheader&nbsp;sh;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.type&nbsp;=&nbsp;PubSubTypes::Publish;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.thmsize&nbsp;=&nbsp;reply_theme.size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.datsize&nbsp;=&nbsp;size;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;If&nbsp;chunking&nbsp;is&nbsp;enabled&nbsp;and&nbsp;message&nbsp;is&nbsp;large,&nbsp;use&nbsp;node-level&nbsp;chunking<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_chunk_size&nbsp;&gt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Calculate&nbsp;total&nbsp;message&nbsp;size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;pubsub_header_size&nbsp;=&nbsp;sizeof(sh)&nbsp;-&nbsp;sizeof(node_subheader);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;total_size&nbsp;=&nbsp;pubsub_header_size&nbsp;+&nbsp;reply_theme.size()&nbsp;+&nbsp;size;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Check&nbsp;buffer&nbsp;capacity<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(total_size&nbsp;&gt;&nbsp;sizeof(service_reply_buffer))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::warn(&quot;service_node::reply:&nbsp;message&nbsp;too&nbsp;large,&nbsp;truncating&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size&nbsp;=&nbsp;sizeof(service_reply_buffer)&nbsp;-&nbsp;pubsub_header_size&nbsp;-<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reply_theme.size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;total_size&nbsp;=&nbsp;sizeof(service_reply_buffer);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sh.datsize&nbsp;=&nbsp;size;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Assemble&nbsp;message&nbsp;into&nbsp;static&nbsp;buffer<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;*ptr&nbsp;=&nbsp;service_reply_buffer;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Add&nbsp;pubsub&nbsp;header&nbsp;(excluding&nbsp;node_subheader&nbsp;part)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;header_part&nbsp;=&nbsp;sizeof(sh)&nbsp;-&nbsp;sizeof(node_subheader);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(ptr,&nbsp;reinterpret_cast&lt;char&nbsp;*&gt;(&amp;sh)&nbsp;+&nbsp;sizeof(node_subheader),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header_part);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ptr&nbsp;+=&nbsp;header_part;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Add&nbsp;theme<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(ptr,&nbsp;reply_theme.data(),&nbsp;reply_theme.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ptr&nbsp;+=&nbsp;reply_theme.size();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Add&nbsp;data<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(ptr,&nbsp;answ,&nbsp;size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Send&nbsp;using&nbsp;node-level&nbsp;chunking<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;send_chunked(subheader.sid,&nbsp;curpack-&gt;addr(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{service_reply_buffer,&nbsp;total_size},&nbsp;qos,&nbsp;ackquant);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;No&nbsp;chunking&nbsp;-&nbsp;use&nbsp;standard&nbsp;publish<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;publish(curpack-&gt;addr(),&nbsp;subheader.sid,&nbsp;reply_theme,&nbsp;{answ,&nbsp;size},&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ackquant);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
