<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/nodes/spammer.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/nodes/spammer.h&gt;<br>
<br>
crow::spam_subscriber::spam_subscriber(igris::delegate&lt;void,&nbsp;nos::buffer&gt;&nbsp;dlg)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;dlg(dlg)<br>
{<br>
}<br>
<br>
void&nbsp;crow::spam_subscriber::subscribe(nodeid_t&nbsp;nid,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::hostaddr_view&nbsp;host,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;addr&nbsp;=&nbsp;std::vector&lt;uint8_t&gt;((uint8_t&nbsp;*)host.data(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(uint8_t&nbsp;*)host.data()&nbsp;+&nbsp;host.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;nid&nbsp;=&nbsp;nid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;node::send(nid,&nbsp;host,&nbsp;&quot;&quot;,&nbsp;qos,&nbsp;ackquant);<br>
}<br>
<br>
void&nbsp;crow::spam_subscriber::resubscribe(uint8_t&nbsp;qos,&nbsp;uint16_t&nbsp;ackquant)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;node::send(nid,&nbsp;{addr.data(),&nbsp;addr.size()},&nbsp;&quot;&quot;,&nbsp;qos,&nbsp;ackquant);<br>
}<br>
<br>
void&nbsp;crow::spam_subscriber::incoming_packet(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::node_packet_ptr&nbsp;npack(pack,&nbsp;this);<br>
&nbsp;&nbsp;&nbsp;&nbsp;dlg(npack.message());<br>
}<br>
<br>
void&nbsp;crow::spammer::send(nos::buffer&nbsp;data)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;time&nbsp;=&nbsp;std::chrono::system_clock::now();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::map&lt;nodeaddr,&nbsp;record&gt;::iterator&gt;&nbsp;to_delete;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;eit&nbsp;=&nbsp;targets.end();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;it&nbsp;=&nbsp;targets.begin();<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;it++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(time&nbsp;-&nbsp;it-&gt;second.last_subscribe&nbsp;&gt;&nbsp;timeout)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_delete.push_back(it);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node::send(it-&gt;first.nid,&nbsp;it-&gt;first.hostaddr(),&nbsp;data,&nbsp;qos,&nbsp;ackquant);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;it&nbsp;:&nbsp;to_delete)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;targets.erase(it);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::spammer::send_v(nos::buffer&nbsp;*data,&nbsp;size_t&nbsp;sz)<br>
{<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;time&nbsp;=&nbsp;std::chrono::system_clock::now();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::map&lt;nodeaddr,&nbsp;record&gt;::iterator&gt;&nbsp;to_delete;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;eit&nbsp;=&nbsp;targets.end();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;it&nbsp;=&nbsp;targets.begin();<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;eit;&nbsp;it++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(time&nbsp;-&nbsp;it-&gt;second.last_subscribe&nbsp;&gt;&nbsp;timeout)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_delete.push_back(it);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node::send_v(it-&gt;first.nid,&nbsp;it-&gt;first.hostaddr(),&nbsp;data,&nbsp;sz,&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ackquant);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;it&nbsp;:&nbsp;to_delete)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;targets.erase(it);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::spammer::incoming_packet(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::node_packet_ptr&nbsp;npack(pack,&nbsp;this);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;time&nbsp;=&nbsp;std::chrono::system_clock::now();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;uint8_t&gt;&nbsp;addr(pack-&gt;addrptr(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;addrptr()&nbsp;+&nbsp;pack-&gt;addrsize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;targets[nodeaddr{addr,&nbsp;(nodeid_t)npack.sid()}]&nbsp;=&nbsp;record{time};<br>
}<br>
<br>
int&nbsp;crow::spammer::count_of_subscribers()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;targets.size();<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
