<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/nodes/subscriber_node.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/nodes/pubsub_defs.h&gt;<br>
#include&nbsp;&lt;crow/nodes/subscriber_node.h&gt;<br>
<br>
void&nbsp;crow::subscriber_node::incoming_packet(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;s&nbsp;=&nbsp;pack-&gt;subheader&lt;pubsub_subheader&gt;();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(s.type)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;PubSubTypes::Consume:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;sh&nbsp;=&nbsp;pack-&gt;subheader&lt;consume_subheader&gt;();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;incoming_handler(sh.message());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;};<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::release(pack);<br>
}<br>
<br>
crow::subscriber_node::subscriber_node(function&nbsp;incoming)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;incoming_handler(incoming)<br>
{<br>
}<br>
<br>
void&nbsp;crow::abstract_subscriber_node::init_subscribe(<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::hostaddr_view&nbsp;crowker_addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;crowker_node,<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::buffer&nbsp;theme,<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant,<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;rqos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;rackquant)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;crowker_addr&nbsp;=&nbsp;crowker_addr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;crowker_node&nbsp;=&nbsp;crowker_node;<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;theme&nbsp;=&nbsp;{theme.data(),&nbsp;theme.size()};<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;qos&nbsp;=&nbsp;qos;<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;ackquant&nbsp;=&nbsp;ackquant;<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;rqos&nbsp;=&nbsp;rqos;<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;rackquant&nbsp;=&nbsp;rackquant;<br>
}<br>
<br>
void&nbsp;crow::abstract_subscriber_node::set_brocker_address(<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::hostaddr_view&nbsp;crowker_addr,&nbsp;int&nbsp;crowker_node)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;crowker_addr&nbsp;=&nbsp;crowker_addr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;crowker_node&nbsp;=&nbsp;crowker_node;<br>
}<br>
<br>
void&nbsp;crow::abstract_subscriber_node::subscribe()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::subscribe_subheader&nbsp;sh;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.type&nbsp;=&nbsp;PubSubTypes::Subscribe;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.rqos&nbsp;=&nbsp;rqos;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.rackquant&nbsp;=&nbsp;rackquant;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.thmsize&nbsp;=&nbsp;theme.size();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;iov[]&nbsp;=&nbsp;{{(char&nbsp;*)&amp;sh&nbsp;+&nbsp;sizeof(node_subheader),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(sh)&nbsp;-&nbsp;sizeof(node_subheader)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;theme};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;node::send_v(crowker_node,&nbsp;crowker_addr,&nbsp;iov,&nbsp;std::size(iov),&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ackquant);<br>
}<br>
<br>
void&nbsp;crow::abstract_subscriber_node::unsubscribe()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::subscribe_subheader&nbsp;sh;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.type&nbsp;=&nbsp;PubSubTypes::Unsubscribe;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.rqos&nbsp;=&nbsp;rqos;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.rackquant&nbsp;=&nbsp;rackquant;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.thmsize&nbsp;=&nbsp;theme.size();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;iov[]&nbsp;=&nbsp;{{(char&nbsp;*)&amp;sh&nbsp;+&nbsp;sizeof(node_subheader),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(sh)&nbsp;-&nbsp;sizeof(node_subheader)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;theme};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;node::send_v(crowker_node,&nbsp;crowker_addr,&nbsp;iov,&nbsp;std::size(iov),&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ackquant);<br>
}<br>
<br>
void&nbsp;crow::abstract_subscriber_node::subscribe_v2(bool&nbsp;updates,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;request_latest)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::subscribe_subheader_v2&nbsp;sh;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.type&nbsp;=&nbsp;PubSubTypes::Subscribe_v2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.rqos&nbsp;=&nbsp;rqos;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.rackquant&nbsp;=&nbsp;rackquant;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.thmsize&nbsp;=&nbsp;theme.size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.cmd.f.subscribe_on_updates&nbsp;=&nbsp;updates;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sh.cmd.f.request_latest&nbsp;=&nbsp;request_latest;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;nos::buffer&nbsp;iov[]&nbsp;=&nbsp;{{(char&nbsp;*)&amp;sh&nbsp;+&nbsp;sizeof(node_subheader),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(sh)&nbsp;-&nbsp;sizeof(node_subheader)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;theme};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;node::send_v(crowker_node,&nbsp;crowker_addr,&nbsp;iov,&nbsp;std::size(iov),&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ackquant);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
