/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crow_CrowPublisher */

#ifndef _Included_crow_CrowPublisher
#define _Included_crow_CrowPublisher
#ifdef __cplusplus
extern "C"
{
#endif
    /*
     * Class:     crow_CrowPublisher
     * Method:    nativeNew
     * Signature: ()J
     */
    JNIEXPORT jlong JNICALL Java_crow_CrowPublisher_nativeNew(JNIEnv *,
                                                              jobject);

#ifdef __cplusplus
}
#endif
#endif
