<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/allocator_test_helper.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#ifndef&nbsp;CROW_ALLOCATOR_TEST_HELPER_H<br>
#define&nbsp;CROW_ALLOCATOR_TEST_HELPER_H<br>
<br>
#include&nbsp;&lt;crow/packet.h&gt;<br>
#include&nbsp;&lt;crow/tower.h&gt;<br>
#include&nbsp;&lt;crow/tower_cls.h&gt;<br>
#include&nbsp;&lt;crow/gates/loopgate.h&gt;<br>
#include&nbsp;&lt;crow/gates/udpgate.h&gt;<br>
#include&nbsp;&lt;doctest/doctest.h&gt;<br>
#include&nbsp;&lt;cstdint&gt;<br>
<br>
//&nbsp;Pool&nbsp;buffer&nbsp;for&nbsp;tests&nbsp;(shared&nbsp;across&nbsp;all&nbsp;tests)<br>
inline&nbsp;uint8_t&nbsp;g_test_pool_buffer[512&nbsp;*&nbsp;16];&nbsp;//&nbsp;16&nbsp;packets&nbsp;of&nbsp;512&nbsp;bytes<br>
<br>
struct&nbsp;AllocatorTestGuard<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;use_pool;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;AllocatorTestGuard(bool&nbsp;pool)&nbsp;:&nbsp;use_pool(pool)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pool)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(g_test_pool_buffer,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(g_test_pool_buffer),&nbsp;512);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;~AllocatorTestGuard()<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(use_pool)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::disengage_packet_pool();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
};<br>
<br>
///&nbsp;Guard&nbsp;that&nbsp;creates&nbsp;a&nbsp;local&nbsp;Tower&nbsp;with&nbsp;loopgate&nbsp;for&nbsp;isolated&nbsp;testing.<br>
///&nbsp;Usage:<br>
///&nbsp;&nbsp;&nbsp;TowerTestGuard&nbsp;guard(use_pool);<br>
///&nbsp;&nbsp;&nbsp;crow::Tower&nbsp;&amp;tower&nbsp;=&nbsp;guard.tower;<br>
///&nbsp;&nbsp;&nbsp;//&nbsp;Use&nbsp;tower.send(),&nbsp;tower.onestep(),&nbsp;etc.<br>
struct&nbsp;TowerTestGuard<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;use_pool;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::Tower&nbsp;tower;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::loopgate&nbsp;loopgate;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;TowerTestGuard(bool&nbsp;pool)&nbsp;:&nbsp;use_pool(pool)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.reset_for_test();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pool)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(g_test_pool_buffer,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(g_test_pool_buffer),&nbsp;512);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.set_retransling_allowed(true);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loopgate.bind(tower,&nbsp;99);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;~TowerTestGuard()<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(use_pool)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::disengage_packet_pool();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.reset_for_test();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
};<br>
<br>
///&nbsp;Guard&nbsp;that&nbsp;creates&nbsp;a&nbsp;local&nbsp;Tower&nbsp;with&nbsp;loopgate&nbsp;and&nbsp;udpgate&nbsp;for&nbsp;testing.<br>
///&nbsp;Usage:<br>
///&nbsp;&nbsp;&nbsp;TowerTestGuardWithUdp&nbsp;guard(use_pool,&nbsp;port);<br>
///&nbsp;&nbsp;&nbsp;crow::Tower&nbsp;&amp;tower&nbsp;=&nbsp;guard.tower;<br>
struct&nbsp;TowerTestGuardWithUdp<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;use_pool;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::Tower&nbsp;tower;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::loopgate&nbsp;loopgate;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::udpgate&nbsp;udpgate;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;TowerTestGuardWithUdp(bool&nbsp;pool,&nbsp;uint16_t&nbsp;udp_port&nbsp;=&nbsp;10099)&nbsp;:&nbsp;use_pool(pool)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.reset_for_test();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pool)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(g_test_pool_buffer,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(g_test_pool_buffer),&nbsp;512);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.set_retransling_allowed(true);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loopgate.bind(tower,&nbsp;99);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;udpgate.bind(tower,&nbsp;12);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;udpgate.open(udp_port);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;~TowerTestGuardWithUdp()<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;udpgate.close();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(use_pool)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::disengage_packet_pool();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.reset_for_test();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
};<br>
<br>
//&nbsp;Macro&nbsp;to&nbsp;run&nbsp;test&nbsp;body&nbsp;with&nbsp;both&nbsp;allocators<br>
//&nbsp;Usage:<br>
//&nbsp;&nbsp;&nbsp;TEST_CASE(&quot;my_test&quot;)&nbsp;{<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FOR_EACH_ALLOCATOR&nbsp;{<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;test&nbsp;code&nbsp;runs&nbsp;twice:&nbsp;with&nbsp;malloc&nbsp;and&nbsp;with&nbsp;pool<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
//&nbsp;&nbsp;&nbsp;}<br>
#define&nbsp;FOR_EACH_ALLOCATOR&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(bool&nbsp;_use_pool&nbsp;:&nbsp;{false,&nbsp;true})&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(auto&nbsp;_subcase&nbsp;=&nbsp;doctest::detail::Subcase(&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_use_pool&nbsp;?&nbsp;&quot;pool&quot;&nbsp;:&nbsp;&quot;malloc&quot;,&nbsp;__FILE__,&nbsp;__LINE__))&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(AllocatorTestGuard&nbsp;_guard(_use_pool);&nbsp;true)<br>
<br>
//&nbsp;Macro&nbsp;to&nbsp;run&nbsp;test&nbsp;with&nbsp;local&nbsp;Tower&nbsp;and&nbsp;loopgate&nbsp;for&nbsp;each&nbsp;allocator<br>
//&nbsp;Usage:<br>
//&nbsp;&nbsp;&nbsp;TEST_CASE(&quot;my_test&quot;)&nbsp;{<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FOR_EACH_ALLOCATOR_WITH_TOWER&nbsp;{<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.send(...);<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.onestep();<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
//&nbsp;&nbsp;&nbsp;}<br>
#define&nbsp;FOR_EACH_ALLOCATOR_WITH_TOWER&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(bool&nbsp;_use_pool&nbsp;:&nbsp;{false,&nbsp;true})&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(auto&nbsp;_subcase&nbsp;=&nbsp;doctest::detail::Subcase(&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_use_pool&nbsp;?&nbsp;&quot;pool&quot;&nbsp;:&nbsp;&quot;malloc&quot;,&nbsp;__FILE__,&nbsp;__LINE__))&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(TowerTestGuard&nbsp;_guard(_use_pool);&nbsp;true)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(crow::Tower&nbsp;&amp;tower&nbsp;=&nbsp;_guard.tower;&nbsp;true)<br>
<br>
#endif&nbsp;//&nbsp;CROW_ALLOCATOR_TEST_HELPER_H<br>
<!-- END SCAT CODE -->
</body>
</html>
