<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/keepalive.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;chrono&gt;<br>
#include&nbsp;&lt;crow/proto/node.h&gt;<br>
#include&nbsp;&lt;crow/tower.h&gt;<br>
#include&nbsp;&lt;doctest/doctest.h&gt;<br>
#include&nbsp;&lt;iostream&gt;<br>
#include&nbsp;&lt;thread&gt;<br>
#include&nbsp;&quot;allocator_test_helper.h&quot;<br>
<br>
static&nbsp;int&nbsp;a&nbsp;=&nbsp;0;<br>
static&nbsp;int&nbsp;b&nbsp;=&nbsp;0;<br>
<br>
class&nbsp;test_keepalive_node&nbsp;:&nbsp;public&nbsp;crow::node,&nbsp;public&nbsp;crow::alived_object<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;&amp;ptr;<br>
<br>
public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;test_keepalive_node(int&nbsp;&amp;ptr)&nbsp;:&nbsp;ptr(ptr)&nbsp;{}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;keepalive_handle()&nbsp;override<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ptr++;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;incoming_packet(crow::packet&nbsp;*)&nbsp;override&nbsp;{}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Convenience&nbsp;wrapper&nbsp;that&nbsp;uses&nbsp;the&nbsp;node's&nbsp;tower<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;install_keepalive(int64_t&nbsp;interval,&nbsp;bool&nbsp;immediate_call&nbsp;=&nbsp;true)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;alived_object::install_keepalive(*_tower,&nbsp;interval,&nbsp;immediate_call);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
};<br>
<br>
TEST_CASE(&quot;keepalive&quot;&nbsp;*&nbsp;doctest::timeout(5))<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;FOR_EACH_ALLOCATOR_WITH_TOWER<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b&nbsp;=&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;test_keepalive_node&nbsp;an(a);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;test_keepalive_node&nbsp;bn(b);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;an.bind(tower,&nbsp;100);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bn.bind(tower,&nbsp;101);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Use&nbsp;longer&nbsp;intervals&nbsp;for&nbsp;more&nbsp;reliable&nbsp;timing<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;an.install_keepalive(20);&nbsp;&nbsp;//&nbsp;20ms&nbsp;interval<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bn.install_keepalive(40);&nbsp;&nbsp;//&nbsp;40ms&nbsp;interval<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Run&nbsp;for&nbsp;150ms&nbsp;to&nbsp;ensure&nbsp;enough&nbsp;keepalive&nbsp;callbacks<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Use&nbsp;longer&nbsp;duration&nbsp;for&nbsp;more&nbsp;reliable&nbsp;timing&nbsp;on&nbsp;loaded&nbsp;systems<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int64_t&nbsp;start&nbsp;=&nbsp;igris::millis();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(igris::millis()&nbsp;-&nbsp;start&nbsp;&lt;&nbsp;150)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::this_thread::sleep_for(std::chrono::milliseconds(2));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;install_keepalive&nbsp;with&nbsp;immediate_call=true&nbsp;calls&nbsp;handler&nbsp;once&nbsp;immediately<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Then&nbsp;timer&nbsp;fires&nbsp;periodically.&nbsp;Timer&nbsp;interval&nbsp;is&nbsp;quantized&nbsp;to&nbsp;min&nbsp;4ms.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;a:&nbsp;20ms&nbsp;interval&nbsp;-&gt;&nbsp;1&nbsp;immediate&nbsp;+&nbsp;~7&nbsp;timer&nbsp;calls&nbsp;in&nbsp;150ms&nbsp;=&nbsp;~8&nbsp;total<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;b:&nbsp;40ms&nbsp;interval&nbsp;-&gt;&nbsp;1&nbsp;immediate&nbsp;+&nbsp;~3&nbsp;timer&nbsp;calls&nbsp;in&nbsp;150ms&nbsp;=&nbsp;~4&nbsp;total<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Use&nbsp;very&nbsp;conservative&nbsp;expectations&nbsp;to&nbsp;avoid&nbsp;flaky&nbsp;test<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_UNARY(a&nbsp;&gt;=&nbsp;2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_UNARY(b&nbsp;&gt;=&nbsp;1);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Cleanup:&nbsp;unplan&nbsp;keepalive&nbsp;timers<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;an.keepalive_timer.unplan();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bn.keepalive_timer.unplan();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
