<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/packet_serialization.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/packet.h&gt;<br>
#include&nbsp;&lt;doctest/doctest.h&gt;<br>
#include&nbsp;&lt;igris/protocols/gstuff.h&gt;<br>
#include&nbsp;&lt;sstream&gt;<br>
#include&nbsp;&lt;vector&gt;<br>
<br>
namespace<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;template&nbsp;&lt;class&nbsp;Header&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;packet_to_gstuff_hex(crow::packet&nbsp;*pack,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;gstuff_context&nbsp;&amp;ctx)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Header&nbsp;header&nbsp;=&nbsp;crow::extract_header&lt;Header&gt;(pack);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;iovec&nbsp;iov[]&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&amp;header,&nbsp;sizeof(Header)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize()},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{pack-&gt;dataptr(),&nbsp;pack-&gt;datasize()},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;stuffed&nbsp;=&nbsp;gstuffing_v(iov,&nbsp;3,&nbsp;ctx);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::ostringstream&nbsp;os;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;os.setf(std::ios::uppercase);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;os&nbsp;&lt;&lt;&nbsp;std::hex;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;first&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(uint8_t&nbsp;byte&nbsp;:&nbsp;stuffed)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!first)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;os&nbsp;&lt;&lt;&nbsp;'&nbsp;';<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;first&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(byte&nbsp;&lt;&nbsp;0x10)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;os&nbsp;&lt;&lt;&nbsp;'0';<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;os&nbsp;&lt;&lt;&nbsp;static_cast&lt;int&gt;(byte);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;os.str();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
TEST_CASE(&quot;packet&nbsp;serialization&nbsp;header_v1&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*pack&nbsp;=&nbsp;crow::allocate_packet&lt;crow::header_v1&gt;(2,&nbsp;2);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(200);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_seqid(0x1234);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_stage(0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;addr[]&nbsp;=&nbsp;{0x01,&nbsp;0x02};<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;addr,&nbsp;sizeof(addr));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;data[]&nbsp;=&nbsp;{'h',&nbsp;'i'};<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;dataptr(),&nbsp;data,&nbsp;sizeof(data));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;hex&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;packet_to_gstuff_hex&lt;crow::header_v1&gt;(pack,&nbsp;gstuff_context());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;type&nbsp;occupies&nbsp;the&nbsp;high&nbsp;3&nbsp;bits&nbsp;of&nbsp;pflag,&nbsp;so&nbsp;type=1&nbsp;results&nbsp;in&nbsp;0x20.<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(hex,&nbsp;&quot;A8&nbsp;20&nbsp;0C&nbsp;00&nbsp;02&nbsp;00&nbsp;34&nbsp;12&nbsp;51&nbsp;01&nbsp;02&nbsp;68&nbsp;69&nbsp;C7&nbsp;B2&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(pack);<br>
}<br>
<br>
TEST_CASE(&quot;packet&nbsp;serialization&nbsp;header_v0&nbsp;sample&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;uint8_t&nbsp;addr[]&nbsp;=&nbsp;{0xF4,&nbsp;0x0C,&nbsp;0x7F,&nbsp;0x00,&nbsp;0x00,&nbsp;0x01,&nbsp;0x27,&nbsp;0x19};<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;uint8_t&nbsp;data[]&nbsp;=&nbsp;{0x00,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x0B,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x00,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0xC8,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0x00,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'r',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'e',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'m',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'o',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'t',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'e',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'r',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'_',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'c',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'m',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'d'};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*pack&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::allocate_packet&lt;crow::header_v0&gt;(sizeof(addr),&nbsp;sizeof(data));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(4);&nbsp;//&nbsp;matches&nbsp;pflag&nbsp;0x20&nbsp;in&nbsp;the&nbsp;captured&nbsp;sample<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(200);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_seqid(0x1105);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_stage(0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;addr,&nbsp;sizeof(addr));<br>
&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;dataptr(),&nbsp;data,&nbsp;sizeof(data));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;hex&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;packet_to_gstuff_hex&lt;crow::header_v0&gt;(pack,&nbsp;gstuff_context_v0());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Captured&nbsp;frame&nbsp;from&nbsp;field&nbsp;device;&nbsp;flen=0x22&nbsp;and&nbsp;CRC=0x3F.<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(hex,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;AC&nbsp;20&nbsp;22&nbsp;00&nbsp;08&nbsp;00&nbsp;C8&nbsp;00&nbsp;05&nbsp;11&nbsp;00&nbsp;F4&nbsp;0C&nbsp;7F&nbsp;00&nbsp;00&nbsp;01&nbsp;27&nbsp;19&nbsp;00&nbsp;0B&nbsp;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;00&nbsp;C8&nbsp;00&nbsp;72&nbsp;65&nbsp;6D&nbsp;6F&nbsp;74&nbsp;65&nbsp;72&nbsp;5F&nbsp;63&nbsp;6D&nbsp;64&nbsp;3F&nbsp;AC&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(pack);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
