<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/self_gstuff.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;chrono&gt;<br>
#include&nbsp;&lt;crow/gates/self_driven_gstuff.h&gt;<br>
#include&nbsp;&lt;crow/packet.h&gt;<br>
#include&nbsp;&lt;doctest/doctest.h&gt;<br>
#include&nbsp;&lt;igris/util/dstring.h&gt;<br>
#include&nbsp;&lt;thread&gt;<br>
<br>
static&nbsp;volatile&nbsp;int&nbsp;ccc&nbsp;=&nbsp;0;<br>
<br>
static&nbsp;size_t&nbsp;write_total&nbsp;=&nbsp;0;<br>
std::vector&lt;uint8_t&gt;&nbsp;writed_data&nbsp;=&nbsp;{};<br>
<br>
static&nbsp;int&nbsp;write(void&nbsp;*priv,&nbsp;const&nbsp;char&nbsp;*data,&nbsp;unsigned&nbsp;int&nbsp;size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_total&nbsp;+=&nbsp;size;<br>
&nbsp;&nbsp;&nbsp;&nbsp;writed_data.insert(writed_data.end(),&nbsp;data,&nbsp;data&nbsp;+&nbsp;size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ccc&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;size;<br>
}<br>
<br>
static&nbsp;int&nbsp;room(void&nbsp;*priv)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;100;<br>
}<br>
<br>
TEST_CASE(&quot;self_driven_gstuff.output&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::total_travelled&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::default_incoming_handler&nbsp;=&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::self_driven_gstuff&lt;crow::header_v1&gt;&nbsp;gate;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate.init(write,&nbsp;room,&nbsp;NULL,&nbsp;100);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate.bind(13);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*pack&nbsp;=&nbsp;crow::create_packet(nullptr,&nbsp;1,&nbsp;10);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(0&nbsp;&amp;&nbsp;0x1F);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;&quot;\x01&quot;,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;dataptr(),&nbsp;&quot;helloworld&quot;,&nbsp;10);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::header_v1&nbsp;header&nbsp;=&nbsp;pack-&gt;extract_header_v1();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iovec&nbsp;arr[]&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&amp;header,&nbsp;sizeof(crow::header_v1)},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{pack-&gt;addrptr(),&nbsp;pack-&gt;addrsize()},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{pack-&gt;dataptr(),&nbsp;pack-&gt;datasize()},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;sbuffer&nbsp;=&nbsp;gstuffing_v(arr,&nbsp;sizeof(arr)&nbsp;/&nbsp;sizeof(iovec),&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gstuff_context());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(ccc,&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate.send(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(ccc,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(gate.in_send(),&nbsp;false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_GT(write_total,&nbsp;10);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::this_thread::sleep_for(std::chrono::milliseconds(10));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::release(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(writed_data.size(),&nbsp;sbuffer.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;a&nbsp;=&nbsp;igris::dstring(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string((char&nbsp;*)writed_data.data(),&nbsp;writed_data.size()));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;b&nbsp;=&nbsp;igris::dstring(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string((char&nbsp;*)sbuffer.data(),&nbsp;sbuffer.size()));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(a,&nbsp;b);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::total_travelled,&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::has_untravelled(),&nbsp;false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
}<br>
<br>
/*TEST_CASE(&quot;self_driven_gstuff.input&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::total_travelled&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::default_incoming_handler&nbsp;=&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::has_allocated(),&nbsp;false);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;buf[64];<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;buf2[64];<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::self_driven_gstuff&nbsp;gate;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate.init(buf,&nbsp;write,&nbsp;NULL,&nbsp;100);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate.bind(13);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*&nbsp;pack&nbsp;=&nbsp;crow_create_packet(nullptr,&nbsp;1,&nbsp;10);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(9&nbsp;&amp;&nbsp;0x1F);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;&quot;\x01&quot;,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;dataptr(),&nbsp;&quot;helloworld&quot;,&nbsp;10);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;gsize&nbsp;=&nbsp;gstuffing((const&nbsp;char*)&amp;pack-&gt;header(),&nbsp;pack-&gt;header().flen,<br>
buf2);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;gsize;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate.newdata(buf2[i]);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::utilize(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::total_travelled,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::has_untravelled(),&nbsp;false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
}*/<br>
<!-- END SCAT CODE -->
</body>
</html>
