<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/test0.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/address.h&gt;<br>
#include&nbsp;&lt;crow/tower.h&gt;<br>
#include&nbsp;&lt;crow/tower_cls.h&gt;<br>
#include&nbsp;&lt;doctest/doctest.h&gt;<br>
#include&nbsp;&lt;nos/print.h&gt;<br>
#include&nbsp;&quot;allocator_test_helper.h&quot;<br>
<br>
#include&nbsp;&lt;chrono&gt;<br>
#include&nbsp;&lt;thread&gt;<br>
<br>
using&nbsp;namespace&nbsp;std::chrono_literals;<br>
<br>
static&nbsp;auto&nbsp;addr&nbsp;=&nbsp;crow::address(&quot;.99&quot;);<br>
static&nbsp;auto&nbsp;addr2&nbsp;=&nbsp;crow::address(&quot;.99.99&quot;);<br>
static&nbsp;int&nbsp;count&nbsp;=&nbsp;0;<br>
static&nbsp;crow::Tower&nbsp;*g_tower&nbsp;=&nbsp;nullptr;<br>
<br>
void&nbsp;incoming(crow::packet&nbsp;*ptr)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;count++;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::Tower::release(ptr);<br>
}<br>
<br>
TEST_CASE(&quot;ptr&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;FOR_EACH_ALLOCATOR<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;ptr&nbsp;=&nbsp;crow::create_packet(nullptr,&nbsp;0,&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet_ptr&nbsp;pptr(ptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;tower_release&nbsp;invalidates&nbsp;the&nbsp;packet&nbsp;immediately,&nbsp;regardless&nbsp;of&nbsp;refs<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;pptr&nbsp;destructor&nbsp;will&nbsp;handle&nbsp;the&nbsp;packet_ptr&nbsp;cleanup<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::Tower::tower_release(ptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
TEST_CASE(&quot;get_stage&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;FOR_EACH_ALLOCATOR_WITH_TOWER<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;data&nbsp;=&nbsp;&quot;data&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::create_packet(NULL,&nbsp;addr.size(),&nbsp;data.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(5);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;addr.data(),&nbsp;addr.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;dataptr(),&nbsp;data.data(),&nbsp;data.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_NE(pack,&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(pack-&gt;stage(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(*pack-&gt;stageptr(),&nbsp;99);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;invalidate();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
TEST_CASE(&quot;get_stage_2&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;auto&nbsp;waddr&nbsp;=&nbsp;crow::address(&quot;.12.127.0.0.1:10098&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(bool&nbsp;_use_pool&nbsp;:&nbsp;{false,&nbsp;true})<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;_subcase&nbsp;=&nbsp;doctest::detail::Subcase(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_use_pool&nbsp;?&nbsp;&quot;pool&quot;&nbsp;:&nbsp;&quot;malloc&quot;,&nbsp;__FILE__,&nbsp;__LINE__);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!_subcase)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TowerTestGuardWithUdp&nbsp;_guard(_use_pool,&nbsp;10098);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;data&nbsp;=&nbsp;&quot;data&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::create_packet(NULL,&nbsp;waddr.size(),&nbsp;data.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(5);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;addrptr(),&nbsp;waddr.data(),&nbsp;waddr.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memcpy(pack-&gt;dataptr(),&nbsp;data.data(),&nbsp;data.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_NE(pack,&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(pack-&gt;stage(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(*pack-&gt;stageptr(),&nbsp;12);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;invalidate();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
TEST_CASE(&quot;test0&quot;&nbsp;*&nbsp;doctest::timeout(3.0))<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;FOR_EACH_ALLOCATOR_WITH_TOWER<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.set_default_incoming_handler(incoming);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;SUBCASE(&quot;0&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.send(addr,&nbsp;&quot;data&quot;,&nbsp;0,&nbsp;0,&nbsp;20);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.onestep();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(count,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.get_total_travelled(),&nbsp;2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.has_untravelled(),&nbsp;false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;SUBCASE(&quot;2_safe&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;packptr&nbsp;=&nbsp;tower.send(addr,&nbsp;&quot;data&quot;,&nbsp;0,&nbsp;0,&nbsp;20);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(packptr-&gt;refs,&nbsp;1);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::this_thread::sleep_for(10ms);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(packptr-&gt;refs,&nbsp;1);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(count,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.has_untravelled(),&nbsp;false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;SUBCASE(&quot;3_safe&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;packptr&nbsp;=&nbsp;tower.send(addr,&nbsp;&quot;data0&quot;,&nbsp;0,&nbsp;0,&nbsp;20);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;packptr&nbsp;=&nbsp;tower.send(addr,&nbsp;&quot;data1&quot;,&nbsp;0,&nbsp;0,&nbsp;20);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;packptr&nbsp;=&nbsp;tower.send(addr,&nbsp;&quot;data2&quot;,&nbsp;0,&nbsp;0,&nbsp;20);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(packptr-&gt;refs,&nbsp;1);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::this_thread::sleep_for(10ms);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(packptr-&gt;refs,&nbsp;1);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(count,&nbsp;3);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.has_untravelled(),&nbsp;false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;SUBCASE(&quot;addr2&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.send(addr2,&nbsp;&quot;data&quot;,&nbsp;0,&nbsp;0,&nbsp;20);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::this_thread::sleep_for(10ms);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(count,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.has_untravelled(),&nbsp;false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;SUBCASE(&quot;qos1&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.send(addr,&nbsp;&quot;data&quot;,&nbsp;0,&nbsp;1,&nbsp;20);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.onestep();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(count,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.get_total_travelled(),&nbsp;4);&nbsp;//&nbsp;pack&nbsp;*&nbsp;2&nbsp;+&nbsp;ack&nbsp;*&nbsp;2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.has_untravelled(),&nbsp;false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;SUBCASE(&quot;qos2&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.send(addr,&nbsp;&quot;data&quot;,&nbsp;0,&nbsp;2,&nbsp;20);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::this_thread::sleep_for(10ms);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(count,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.get_total_travelled(),&nbsp;6);&nbsp;//&nbsp;pack&nbsp;*&nbsp;2&nbsp;+&nbsp;ack&nbsp;*&nbsp;2&nbsp;+&nbsp;ack2&nbsp;*&nbsp;2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.has_untravelled(),&nbsp;false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;//&nbsp;FOR_EACH_ALLOCATOR_WITH_TOWER<br>
}<br>
<br>
//&nbsp;Separate&nbsp;test&nbsp;case&nbsp;for&nbsp;undelivered&nbsp;tests&nbsp;that&nbsp;require&nbsp;UDP&nbsp;gate<br>
TEST_CASE(&quot;test0_undelivered&quot;&nbsp;*&nbsp;doctest::timeout(3.0))<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;auto&nbsp;waddr&nbsp;=&nbsp;crow::address(&quot;.12.127.0.0.1:10098&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(bool&nbsp;_use_pool&nbsp;:&nbsp;{false,&nbsp;true})<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;_subcase&nbsp;=&nbsp;doctest::detail::Subcase(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_use_pool&nbsp;?&nbsp;&quot;pool&quot;&nbsp;:&nbsp;&quot;malloc&quot;,&nbsp;__FILE__,&nbsp;__LINE__);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!_subcase)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TowerTestGuardWithUdp&nbsp;_guard(_use_pool,&nbsp;10099);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::Tower&nbsp;&amp;tower&nbsp;=&nbsp;_guard.tower;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.set_default_incoming_handler(incoming);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;SUBCASE(&quot;undelivered_0&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.send(waddr,&nbsp;&quot;data&quot;,&nbsp;0,&nbsp;0,&nbsp;2);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.onestep();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(count,&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.get_total_travelled(),&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.has_untravelled(),&nbsp;false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;SUBCASE(&quot;undelivered_1&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.send(waddr,&nbsp;&quot;data&quot;,&nbsp;0,&nbsp;1,&nbsp;2);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.incomming_stage_count(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.outers_stage_count(),&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.onestep();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.incomming_stage_count(),&nbsp;0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;ackquant=2&nbsp;gets&nbsp;quantized&nbsp;to&nbsp;4ms,&nbsp;need&nbsp;5&nbsp;retries<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Use&nbsp;15ms&nbsp;intervals&nbsp;with&nbsp;more&nbsp;iterations&nbsp;to&nbsp;ensure&nbsp;all&nbsp;retries&nbsp;complete<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;12;&nbsp;i++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::this_thread::sleep_for(std::chrono::milliseconds(15));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.outers_stage_count(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(count,&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.get_total_travelled(),&nbsp;5);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.has_untravelled(),&nbsp;false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;SUBCASE(&quot;undelivered_2&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.send(waddr,&nbsp;&quot;data&quot;,&nbsp;0,&nbsp;2,&nbsp;2);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;ackquant=2&nbsp;gets&nbsp;quantized&nbsp;to&nbsp;4ms,&nbsp;need&nbsp;5&nbsp;retries<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Use&nbsp;15ms&nbsp;intervals&nbsp;with&nbsp;more&nbsp;iterations&nbsp;to&nbsp;ensure&nbsp;all&nbsp;retries&nbsp;complete<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;12;&nbsp;i++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::this_thread::sleep_for(std::chrono::milliseconds(15));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(count,&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.get_total_travelled(),&nbsp;5);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower.has_untravelled(),&nbsp;false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;//&nbsp;for&nbsp;_use_pool<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
