<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/two_towers.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**<br>
&nbsp;*&nbsp;@file&nbsp;two_towers.cpp<br>
&nbsp;*&nbsp;@brief&nbsp;Test&nbsp;for&nbsp;multiple&nbsp;independent&nbsp;Tower&nbsp;instances&nbsp;communicating&nbsp;via&nbsp;UDP<br>
&nbsp;*<br>
&nbsp;*&nbsp;This&nbsp;test&nbsp;verifies&nbsp;that:<br>
&nbsp;*&nbsp;1.&nbsp;Multiple&nbsp;Tower&nbsp;instances&nbsp;can&nbsp;be&nbsp;created<br>
&nbsp;*&nbsp;2.&nbsp;Each&nbsp;Tower&nbsp;can&nbsp;have&nbsp;its&nbsp;own&nbsp;gateway&nbsp;bound&nbsp;to&nbsp;it<br>
&nbsp;*&nbsp;3.&nbsp;Packets&nbsp;can&nbsp;be&nbsp;sent&nbsp;between&nbsp;towers&nbsp;via&nbsp;UDP<br>
&nbsp;*/<br>
<br>
#include&nbsp;&lt;crow/address.h&gt;<br>
#include&nbsp;&lt;crow/gates/udpgate.h&gt;<br>
#include&nbsp;&lt;crow/tower.h&gt;<br>
#include&nbsp;&lt;crow/tower_cls.h&gt;<br>
#include&nbsp;&lt;doctest/doctest.h&gt;<br>
<br>
#include&nbsp;&lt;atomic&gt;<br>
#include&nbsp;&lt;chrono&gt;<br>
#include&nbsp;&lt;thread&gt;<br>
<br>
using&nbsp;namespace&nbsp;std::chrono_literals;<br>
<br>
//&nbsp;Custom&nbsp;udpgate&nbsp;that&nbsp;supports&nbsp;Tower&nbsp;binding<br>
class&nbsp;test_udpgate&nbsp;:&nbsp;public&nbsp;crow::udpgate<br>
{<br>
public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;using&nbsp;crow::udpgate::udpgate;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;bind(crow::Tower&nbsp;&amp;tower,&nbsp;int&nbsp;gate_no&nbsp;=&nbsp;CROW_UDPGATE_NO)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;crow::gateway::bind(tower,&nbsp;gate_no);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
};<br>
<br>
//&nbsp;Global&nbsp;state&nbsp;for&nbsp;handlers&nbsp;(since&nbsp;we&nbsp;can't&nbsp;use&nbsp;capturing&nbsp;lambdas)<br>
static&nbsp;std::atomic&lt;int&gt;&nbsp;g_tower2_received{0};<br>
static&nbsp;std::string&nbsp;g_tower2_data;<br>
static&nbsp;crow::Tower&nbsp;*g_tower2_ptr&nbsp;=&nbsp;nullptr;<br>
<br>
static&nbsp;void&nbsp;tower2_handler(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;g_tower2_data&nbsp;=&nbsp;std::string(pack-&gt;dataptr(),&nbsp;pack-&gt;datasize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;g_tower2_received++;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(g_tower2_ptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;g_tower2_ptr-&gt;release(pack);<br>
}<br>
<br>
static&nbsp;std::atomic&lt;int&gt;&nbsp;g_tower1_received{0};<br>
static&nbsp;std::string&nbsp;g_tower1_data;<br>
static&nbsp;crow::Tower&nbsp;*g_tower1_ptr&nbsp;=&nbsp;nullptr;<br>
<br>
static&nbsp;void&nbsp;tower1_handler(crow::packet&nbsp;*pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;g_tower1_data&nbsp;=&nbsp;std::string(pack-&gt;dataptr(),&nbsp;pack-&gt;datasize());<br>
&nbsp;&nbsp;&nbsp;&nbsp;g_tower1_received++;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(g_tower1_ptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;g_tower1_ptr-&gt;release(pack);<br>
}<br>
<br>
TEST_CASE(&quot;two_towers_udp&quot;&nbsp;*&nbsp;doctest::timeout(5.0))<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Reset&nbsp;global&nbsp;state<br>
&nbsp;&nbsp;&nbsp;&nbsp;g_tower2_received&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;g_tower2_data.clear();<br>
&nbsp;&nbsp;&nbsp;&nbsp;g_tower1_received&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;g_tower1_data.clear();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Create&nbsp;two&nbsp;independent&nbsp;towers<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::Tower&nbsp;tower1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::Tower&nbsp;tower2;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Store&nbsp;pointers&nbsp;for&nbsp;handlers<br>
&nbsp;&nbsp;&nbsp;&nbsp;g_tower1_ptr&nbsp;=&nbsp;&amp;tower1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;g_tower2_ptr&nbsp;=&nbsp;&amp;tower2;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Configure&nbsp;towers<br>
&nbsp;&nbsp;&nbsp;&nbsp;tower1.set_retransling_allowed(true);<br>
&nbsp;&nbsp;&nbsp;&nbsp;tower2.set_retransling_allowed(true);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Create&nbsp;UDP&nbsp;gates&nbsp;for&nbsp;each&nbsp;tower&nbsp;on&nbsp;different&nbsp;ports<br>
&nbsp;&nbsp;&nbsp;&nbsp;test_udpgate&nbsp;gate1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;test_udpgate&nbsp;gate2;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Open&nbsp;UDP&nbsp;ports<br>
&nbsp;&nbsp;&nbsp;&nbsp;REQUIRE(gate1.open(20001)&nbsp;==&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;REQUIRE(gate2.open(20002)&nbsp;==&nbsp;0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Bind&nbsp;gates&nbsp;to&nbsp;their&nbsp;respective&nbsp;towers<br>
&nbsp;&nbsp;&nbsp;&nbsp;gate1.bind(tower1,&nbsp;12);&nbsp;//&nbsp;gate_id&nbsp;=&nbsp;12&nbsp;(CROW_UDPGATE_NO)<br>
&nbsp;&nbsp;&nbsp;&nbsp;gate2.bind(tower2,&nbsp;12);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Set&nbsp;incoming&nbsp;handler&nbsp;for&nbsp;tower2<br>
&nbsp;&nbsp;&nbsp;&nbsp;tower2.set_default_incoming_handler(tower2_handler);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;SUBCASE(&quot;send_qos0&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Address:&nbsp;gate_id=12,&nbsp;IP=127.0.0.1,&nbsp;port=20002<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;addr&nbsp;=&nbsp;crow::address(&quot;.12.127.0.0.1:20002&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Send&nbsp;packet&nbsp;from&nbsp;tower1&nbsp;to&nbsp;tower2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower1.send(addr,&nbsp;&quot;Hello&nbsp;Tower2!&quot;,&nbsp;0,&nbsp;0,&nbsp;50,&nbsp;false);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Process&nbsp;both&nbsp;towers<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;10&nbsp;&amp;&amp;&nbsp;g_tower2_received&nbsp;==&nbsp;0;&nbsp;i++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower1.onestep();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Manually&nbsp;trigger&nbsp;read&nbsp;on&nbsp;gate2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate2.read_handler(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower2.onestep();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::this_thread::sleep_for(10ms);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(g_tower2_received,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(g_tower2_data,&nbsp;&quot;Hello&nbsp;Tower2!&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower1.get_total_travelled(),&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;SUBCASE(&quot;send_qos1&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;addr&nbsp;=&nbsp;crow::address(&quot;.12.127.0.0.1:20002&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Send&nbsp;with&nbsp;QoS&nbsp;1&nbsp;(requires&nbsp;ACK)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower1.send(addr,&nbsp;&quot;QoS1&nbsp;Message&quot;,&nbsp;0,&nbsp;1,&nbsp;50,&nbsp;false);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Process&nbsp;both&nbsp;towers&nbsp;until&nbsp;done&nbsp;or&nbsp;timeout<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;20;&nbsp;i++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower1.onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate2.read_handler(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower2.onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate1.read_handler(0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(g_tower2_received&nbsp;&gt;&nbsp;0&nbsp;&amp;&amp;&nbsp;!tower1.has_untravelled())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::this_thread::sleep_for(10ms);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(g_tower2_received,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(g_tower2_data,&nbsp;&quot;QoS1&nbsp;Message&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;QoS1:&nbsp;original&nbsp;packet&nbsp;+&nbsp;ACK&nbsp;=&nbsp;at&nbsp;least&nbsp;2&nbsp;travels&nbsp;per&nbsp;tower<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_GE(tower1.get_total_travelled(),&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;SUBCASE(&quot;bidirectional&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Set&nbsp;handler&nbsp;for&nbsp;tower1&nbsp;too<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower1.set_default_incoming_handler(tower1_handler);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;addr_to_tower2&nbsp;=&nbsp;crow::address(&quot;.12.127.0.0.1:20002&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;addr_to_tower1&nbsp;=&nbsp;crow::address(&quot;.12.127.0.0.1:20001&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Send&nbsp;from&nbsp;tower1&nbsp;to&nbsp;tower2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower1.send(addr_to_tower2,&nbsp;&quot;To&nbsp;Tower2&quot;,&nbsp;0,&nbsp;0,&nbsp;50,&nbsp;false);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Send&nbsp;from&nbsp;tower2&nbsp;to&nbsp;tower1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower2.send(addr_to_tower1,&nbsp;&quot;To&nbsp;Tower1&quot;,&nbsp;0,&nbsp;0,&nbsp;50,&nbsp;false);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Process&nbsp;both&nbsp;towers<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;20;&nbsp;i++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower1.onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower2.onestep();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate1.read_handler(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gate2.read_handler(0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(g_tower2_received&nbsp;&gt;&nbsp;0&nbsp;&amp;&amp;&nbsp;g_tower1_received&nbsp;&gt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::this_thread::sleep_for(10ms);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(g_tower2_received,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(g_tower2_data,&nbsp;&quot;To&nbsp;Tower2&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(g_tower1_received,&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(g_tower1_data,&nbsp;&quot;To&nbsp;Tower1&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Cleanup<br>
&nbsp;&nbsp;&nbsp;&nbsp;gate1.close();<br>
&nbsp;&nbsp;&nbsp;&nbsp;gate2.close();<br>
&nbsp;&nbsp;&nbsp;&nbsp;g_tower1_ptr&nbsp;=&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;g_tower2_ptr&nbsp;=&nbsp;nullptr;<br>
}<br>
<br>
TEST_CASE(&quot;tower_isolation&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Verify&nbsp;that&nbsp;towers&nbsp;are&nbsp;truly&nbsp;isolated<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::Tower&nbsp;tower1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::Tower&nbsp;tower2;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Each&nbsp;tower&nbsp;should&nbsp;have&nbsp;independent&nbsp;state<br>
&nbsp;&nbsp;&nbsp;&nbsp;tower1.set_retransling_allowed(true);<br>
&nbsp;&nbsp;&nbsp;&nbsp;tower2.set_retransling_allowed(false);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower1.get_retransling_allowed(),&nbsp;true);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower2.get_retransling_allowed(),&nbsp;false);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;tower1.set_debug_data_size(100);<br>
&nbsp;&nbsp;&nbsp;&nbsp;tower2.set_debug_data_size(200);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower1.get_debug_data_size(),&nbsp;100);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower2.get_debug_data_size(),&nbsp;200);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Counters&nbsp;should&nbsp;be&nbsp;independent<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower1.get_total_travelled(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(tower2.get_total_travelled(),&nbsp;0);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
