<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>apps/crowker/control_node.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/brocker/crowker.h&gt;<br>
#include&nbsp;&lt;crow/brocker/crowker_api.h&gt;<br>
#include&nbsp;&lt;crow/nodes/node_delegate.h&gt;<br>
#include&nbsp;&lt;crow/nodes/service_node.h&gt;<br>
#include&nbsp;&lt;igris/shell/rshell_executor.h&gt;<br>
#include&nbsp;&lt;string&gt;<br>
<br>
#include&nbsp;&lt;igris/util/dstring.h&gt;<br>
#include&nbsp;&lt;nos/shell/argv.h&gt;<br>
#include&nbsp;&lt;nos/shell/executor.h&gt;<br>
<br>
static&nbsp;int&nbsp;themes(const&nbsp;nos::argv&nbsp;&amp;,&nbsp;nos::ostream&nbsp;&amp;os)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;themes&nbsp;=&nbsp;crow::crowker::instance()-&gt;themes;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(themes.size()&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(os,&nbsp;&quot;No&nbsp;one&nbsp;theme&nbsp;here&nbsp;yet.&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;[name,&nbsp;theme]&nbsp;:&nbsp;themes)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;s&nbsp;=&nbsp;nos::format(&quot;name:{}&nbsp;count_of_subs:{}\n&quot;,&nbsp;name,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;theme.count_clients());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::print_to(os,&nbsp;s);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
static&nbsp;int&nbsp;theme_names(const&nbsp;nos::argv&nbsp;&amp;,&nbsp;nos::ostream&nbsp;&amp;os)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;themes&nbsp;=&nbsp;crow::crowker::instance()-&gt;themes;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(themes.size()&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(os,&nbsp;&quot;No&nbsp;one&nbsp;theme&nbsp;here&nbsp;yet.&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;a&nbsp;:&nbsp;themes)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;s&nbsp;=&nbsp;nos::format(&quot;{}\n&quot;,&nbsp;a.first);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::print_to(os,&nbsp;s);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
static&nbsp;int&nbsp;clients(const&nbsp;nos::argv&nbsp;&amp;,&nbsp;nos::ostream&nbsp;&amp;os)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;clients&nbsp;=&nbsp;crow::crowker::instance()-&gt;clients();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(clients.size()&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(os,&nbsp;&quot;No&nbsp;one&nbsp;theme&nbsp;here&nbsp;yet.&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;a&nbsp;:&nbsp;clients)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;s&nbsp;=&nbsp;nos::format(&quot;name:{}\n&quot;,&nbsp;a-&gt;name());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::print_to(os,&nbsp;s);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
static&nbsp;int&nbsp;last_messages(const&nbsp;nos::argv&nbsp;&amp;argv,&nbsp;nos::ostream&nbsp;&amp;os)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::shared_ptr&lt;std::string&gt;&gt;&nbsp;messages;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(argv.size()&nbsp;&lt;&nbsp;2)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(os,&nbsp;&quot;Usage:&nbsp;last&nbsp;THEME&nbsp;[SIZE]&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;size&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(argv.size()&nbsp;&gt;=&nbsp;3)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size&nbsp;=&nbsp;(size_t)atoi(argv[2].data());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;name&nbsp;=&nbsp;argv[1];<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;themes&nbsp;=&nbsp;crow::crowker::instance()-&gt;themes;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;theme_pair&nbsp;=&nbsp;themes.find({name.data(),&nbsp;name.size()});<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(theme_pair&nbsp;==&nbsp;themes.end())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;theme&nbsp;=&nbsp;theme_pair-&gt;second;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::lock_guard&lt;std::mutex&gt;&nbsp;lock(theme.local_lock());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(size&nbsp;&gt;&nbsp;theme.queue_size())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size&nbsp;=&nbsp;theme.queue_size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(size_t&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;size;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(theme.queue()[i])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(os,&nbsp;igris::dstring(*theme.queue()[i]));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
static&nbsp;int&nbsp;set_queue_size(const&nbsp;nos::argv&nbsp;&amp;argv,&nbsp;nos::ostream&nbsp;&amp;os)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(argv.size()&nbsp;&lt;&nbsp;3)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println_to(os,&nbsp;&quot;Usage:&nbsp;queue-size&nbsp;THEME&nbsp;[SIZE]&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;size&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(argv.size()&nbsp;&gt;=&nbsp;3)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size&nbsp;=&nbsp;(size_t)atoi(argv[2].data());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;name&nbsp;=&nbsp;argv[1];<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;themes&nbsp;=&nbsp;crow::crowker::instance()-&gt;themes;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;theme_pair&nbsp;=&nbsp;themes.find({name.data(),&nbsp;name.size()});<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(theme_pair&nbsp;==&nbsp;themes.end())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;theme_pair-&gt;second.resize_queue(size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
nos::executor&nbsp;executor(<br>
&nbsp;&nbsp;&nbsp;&nbsp;{nos::command{&quot;clients&quot;,&nbsp;&quot;crowker&nbsp;clients&quot;,&nbsp;clients},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::command{&quot;themes&quot;,&nbsp;&quot;crowker&nbsp;themes&quot;,&nbsp;themes},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::command{&quot;theme-names&quot;,&nbsp;&quot;crowker&nbsp;themes,&nbsp;only&nbsp;names&quot;,&nbsp;theme_names},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::command{&quot;last&quot;,&nbsp;&quot;get&nbsp;latest&nbsp;theme&nbsp;messages&quot;,&nbsp;last_messages},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::command{&quot;queue-size&quot;,&nbsp;&quot;set_queue_size&quot;,&nbsp;set_queue_size}});<br>
<br>
static&nbsp;void&nbsp;incoming(crow::node_packet_ptr&nbsp;pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::string_buffer&nbsp;answer;<br>
&nbsp;&nbsp;&nbsp;&nbsp;executor.execute(nos::tokens(pack.message().data()),&nbsp;answer);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack.reply({answer.str().data(),&nbsp;answer.str().size()});<br>
}<br>
<br>
static&nbsp;void&nbsp;undelivered(crow::node_packet_ptr&nbsp;pack)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)pack;<br>
}<br>
<br>
static&nbsp;void&nbsp;incoming_beam(crow::node_packet_ptr)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//	crowker_api.client_beam(pack-&gt;addr(),&nbsp;pack.sid(),&nbsp;pack.message());<br>
}<br>
<br>
static&nbsp;void&nbsp;control_handler(char&nbsp;*data,&nbsp;int,&nbsp;crow::service_node&nbsp;&amp;node)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::string_buffer&nbsp;answer;<br>
&nbsp;&nbsp;&nbsp;&nbsp;executor.execute(nos::tokens(data),&nbsp;answer);<br>
&nbsp;&nbsp;&nbsp;&nbsp;node.reply({answer.str().data(),&nbsp;answer.str().size()});<br>
}<br>
<br>
crow::node_delegate&nbsp;control(incoming,&nbsp;undelivered);<br>
crow::node_delegate&nbsp;beamsocket(incoming_beam,&nbsp;undelivered);<br>
crow::service_node&nbsp;control_service(control_handler);<br>
<br>
void&nbsp;init_control_node()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;control.bind(CROWKER_CONTROL_BROCKER_NODE_NO);<br>
&nbsp;&nbsp;&nbsp;&nbsp;beamsocket.bind(CROWKER_BEAMSOCKET_BROCKER_NODE_NO);<br>
&nbsp;&nbsp;&nbsp;&nbsp;control_service.init(crow::hostaddr(&quot;&quot;),&nbsp;&quot;crowker/control&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;control_service.subscribe();<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
