<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>apps/crowker/main.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;crow/address.h&gt;<br>
#include&nbsp;&lt;crow/brocker/crowker_api.h&gt;<br>
#include&nbsp;&lt;crow/brocker/crowker_pubsub_node.h&gt;<br>
#include&nbsp;&lt;crow/gates/tcpgate.h&gt;<br>
#include&nbsp;&lt;crow/gates/udpgate.h&gt;<br>
#include&nbsp;&lt;crow/proto/node_protocol.h&gt;<br>
#include&nbsp;&lt;crow/tower.h&gt;<br>
#include&nbsp;&lt;crow/tower_cls.h&gt;<br>
<br>
#include&nbsp;&lt;getopt.h&gt;<br>
#include&nbsp;&lt;stdbool.h&gt;<br>
#include&nbsp;&lt;stdio.h&gt;<br>
#include&nbsp;&lt;unistd.h&gt;<br>
<br>
#include&nbsp;&lt;map&gt;<br>
#include&nbsp;&lt;string&gt;<br>
#include&nbsp;&lt;random&gt;<br>
<br>
#include&nbsp;&quot;control_node.h&quot;<br>
#include&nbsp;&quot;webui.h&quot;<br>
#include&nbsp;&lt;crow/brocker/crowker.h&gt;<br>
#include&nbsp;&lt;crow/pubsub/pubsub.h&gt;<br>
<br>
#include&nbsp;&lt;igris/util/dstring.h&gt;<br>
#include&nbsp;&lt;nos/fprint.h&gt;<br>
#include&nbsp;&lt;nos/print.h&gt;<br>
#include&nbsp;&lt;nos/io/stdfile.h&gt;<br>
<br>
#include&nbsp;&lt;csignal&gt;<br>
<br>
void&nbsp;signal_handler(int&nbsp;signum)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)signum;<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::println(&quot;\nReceived&nbsp;signal,&nbsp;shutting&nbsp;down...&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crowker_webui::stop();<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::set_spin_cancel_token();<br>
}<br>
<br>
bool&nbsp;brocker_info&nbsp;=&nbsp;false;<br>
int&nbsp;udpport&nbsp;=&nbsp;-1;<br>
int&nbsp;tcpport&nbsp;=&nbsp;-1;<br>
int&nbsp;httpport&nbsp;=&nbsp;-1;<br>
bool&nbsp;quite&nbsp;=&nbsp;false;<br>
bool&nbsp;debug_mode&nbsp;=&nbsp;false;<br>
<br>
const&nbsp;std::string&nbsp;VERSION&nbsp;=&nbsp;&quot;2.1.0&quot;;<br>
<br>
crow::Tower&nbsp;tower;<br>
crow::crowker_pubsub_node&nbsp;pubsub_node;<br>
<br>
void&nbsp;print_help()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;printf(&quot;Usage:&nbsp;crowker&nbsp;[OPTION]...\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Common&nbsp;option&nbsp;list:\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-h,&nbsp;--help&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print&nbsp;this&nbsp;page\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-d,&nbsp;--debug&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;enable&nbsp;debug&nbsp;mode\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-b,&nbsp;--binfo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;enable&nbsp;info&nbsp;mode\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Gate`s&nbsp;option&nbsp;list:\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-u,&nbsp;--udp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;set&nbsp;udp&nbsp;port&nbsp;(gate&nbsp;12)\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-t,&nbsp;--tcp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;set&nbsp;tcp&nbsp;port&nbsp;(gate&nbsp;13)\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-w,&nbsp;--http&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;set&nbsp;web&nbsp;UI&nbsp;http&nbsp;port&nbsp;(default:&nbsp;8080)\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-S,&nbsp;--serial&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;make&nbsp;gate&nbsp;on&nbsp;serial&nbsp;device\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;);<br>
}<br>
<br>
int&nbsp;main(int&nbsp;argc,&nbsp;char&nbsp;*argv[])<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Initialize&nbsp;with&nbsp;random&nbsp;seqid&nbsp;to&nbsp;reduce&nbsp;collision&nbsp;probability<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;after&nbsp;restart&nbsp;(TIME_WAIT&nbsp;entries&nbsp;on&nbsp;remote&nbsp;nodes&nbsp;still&nbsp;reference&nbsp;old&nbsp;seqids)<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::random_device&nbsp;rd;<br>
&nbsp;&nbsp;&nbsp;&nbsp;tower.set_initial_seqid(rd()&nbsp;&amp;&nbsp;0xFFFF);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Set&nbsp;diagnostic&nbsp;label&nbsp;with&nbsp;PID&nbsp;for&nbsp;debugging<br>
&nbsp;&nbsp;&nbsp;&nbsp;tower.set_diagnostic_label(nos::format(&quot;crowker:{}&quot;,&nbsp;getpid()));<br>
<br>
#ifdef&nbsp;CROW_PUBSUB_PROTOCOL_SUPPORTED<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::pubsub_protocol.enable_crowker_subsystem();<br>
#endif<br>
&nbsp;&nbsp;&nbsp;&nbsp;pubsub_node.bind(tower,&nbsp;CROWKER_SERVICE_BROCKER_NODE_NO);<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Enable&nbsp;chunking&nbsp;for&nbsp;large&nbsp;messages&nbsp;(UDP&nbsp;MTU&nbsp;is&nbsp;~1400&nbsp;bytes)<br>
&nbsp;&nbsp;&nbsp;&nbsp;pubsub_node.set_chunk_size(1000);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::crowker::instance()-&gt;add_api(&amp;pubsub_node);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;struct&nbsp;option&nbsp;long_options[]&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;help&quot;,&nbsp;no_argument,&nbsp;NULL,&nbsp;'h'},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;udp&quot;,&nbsp;required_argument,&nbsp;NULL,&nbsp;'u'},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;tcp&quot;,&nbsp;required_argument,&nbsp;NULL,&nbsp;'t'},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;http&quot;,&nbsp;required_argument,&nbsp;NULL,&nbsp;'w'},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;debug&quot;,&nbsp;no_argument,&nbsp;NULL,&nbsp;'d'},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;binfo&quot;,&nbsp;no_argument,&nbsp;NULL,&nbsp;'b'},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;version&quot;,&nbsp;no_argument,&nbsp;NULL,&nbsp;'v'},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{NULL,&nbsp;0,&nbsp;NULL,&nbsp;0}};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;long_index&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;opt&nbsp;=&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;((opt&nbsp;=&nbsp;getopt_long(argc,&nbsp;argv,&nbsp;&quot;u:t:w:svdib&quot;,&nbsp;long_options,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&amp;long_index))&nbsp;!=&nbsp;-1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(opt)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;'h':<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print_help();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit(0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;'u':<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;udpport&nbsp;=&nbsp;atoi(optarg);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;'t':<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tcpport&nbsp;=&nbsp;atoi(optarg);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;'w':<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;httpport&nbsp;=&nbsp;atoi(optarg);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;'d':<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;debug_mode&nbsp;=&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tower.enable_diagnostic();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::node_protocol.set_debug(true);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;'b':<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;brocker_info&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::crowker::instance()-&gt;brocker_info&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;'v':<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::println(VERSION);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit(0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(udpport&nbsp;==&nbsp;-1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(debug_mode)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fprintf(stderr,&nbsp;&quot;Use&nbsp;default&nbsp;udp&nbsp;port&nbsp;10009.\n&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;udpport&nbsp;=&nbsp;10009;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;udpgate&nbsp;=&nbsp;crow::create_udpgate_safe(CROW_UDPGATE_NO,&nbsp;udpport);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!udpgate&nbsp;||&nbsp;!udpgate-&gt;opened())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;udpgate&nbsp;open&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit(-1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;udpgate-&gt;bind(tower,&nbsp;CROW_UDPGATE_NO);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Create&nbsp;crow&nbsp;TCP&nbsp;gate&nbsp;if&nbsp;requested<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::shared_ptr&lt;crow::tcpgate&gt;&nbsp;tcpgate;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(tcpport&nbsp;!=&nbsp;-1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tcpgate&nbsp;=&nbsp;crow::create_tcpgate_safe(CROW_TCPGATE_NO,&nbsp;tcpport);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!tcpgate&nbsp;||&nbsp;!tcpgate-&gt;opened())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perror(&quot;tcpgate&nbsp;open&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit(-1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tcpgate-&gt;bind(tower,&nbsp;CROW_TCPGATE_NO);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(debug_mode)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tcpgate-&gt;debug(true);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!quite)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;TCP&nbsp;gate&nbsp;listening&nbsp;on&nbsp;port&nbsp;{}&quot;,&nbsp;tcpport);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Start&nbsp;web&nbsp;UI&nbsp;server<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(httpport&nbsp;!=&nbsp;-1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(crowker_webui::start(httpport,&nbsp;brocker_info))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!quite)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;Web&nbsp;UI&nbsp;started&nbsp;on&nbsp;http://0.0.0.0:{}&quot;,&nbsp;httpport);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln_to(nos::cerr,&nbsp;&quot;Failed&nbsp;to&nbsp;start&nbsp;Web&nbsp;UI&nbsp;on&nbsp;port&nbsp;{}&quot;,&nbsp;httpport);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;init_control_node(tower);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Регистрируем&nbsp;обработчик&nbsp;сигнала&nbsp;для&nbsp;корректного&nbsp;завершения<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::signal(SIGINT,&nbsp;signal_handler);<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::signal(SIGTERM,&nbsp;signal_handler);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::spin_with_select(tower);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::println(&quot;Crowker&nbsp;stopped.&quot;);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
