<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/pool/test_pool_standalone.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**<br>
&nbsp;*&nbsp;@file&nbsp;test_pool_standalone.cpp<br>
&nbsp;*&nbsp;@brief&nbsp;Standalone&nbsp;tests&nbsp;for&nbsp;crow&nbsp;packet&nbsp;pool&nbsp;allocator<br>
&nbsp;*<br>
&nbsp;*&nbsp;Compile&nbsp;with:<br>
&nbsp;*&nbsp;g++&nbsp;-std=c++17&nbsp;-g&nbsp;-I..&nbsp;-I../../igris&nbsp;test_pool_standalone.cpp&nbsp;\<br>
&nbsp;*&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../crow/src/variants/allocation_pool.cpp&nbsp;../crow/src/packet.cpp&nbsp;\<br>
&nbsp;*&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-o&nbsp;test_pool_standalone<br>
&nbsp;*/<br>
<br>
#define&nbsp;DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN<br>
#include&nbsp;&lt;doctest/doctest.h&gt;<br>
#include&nbsp;&lt;crow/packet.h&gt;<br>
#include&nbsp;&lt;cstring&gt;<br>
<br>
//&nbsp;Stubs&nbsp;for&nbsp;system_lock/unlock&nbsp;when&nbsp;testing&nbsp;on&nbsp;host&nbsp;without&nbsp;OS<br>
extern&nbsp;&quot;C&quot;&nbsp;void&nbsp;system_lock()&nbsp;{}<br>
extern&nbsp;&quot;C&quot;&nbsp;void&nbsp;system_unlock()&nbsp;{}<br>
<br>
TEST_CASE(&quot;pool_allocator.init_and_basic&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Size:&nbsp;packet&nbsp;+&nbsp;header_v1&nbsp;+&nbsp;256&nbsp;bytes&nbsp;data<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;size_t&nbsp;elem_size&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v1)&nbsp;+&nbsp;256;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;int&nbsp;num_packets&nbsp;=&nbsp;4;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;uint8_t&nbsp;pool_buffer[elem_size&nbsp;*&nbsp;num_packets];<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(pool_buffer,&nbsp;sizeof(pool_buffer),&nbsp;elem_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::get_package_pool()-&gt;avail(),&nbsp;num_packets);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::get_package_pool()-&gt;size(),&nbsp;num_packets);<br>
}<br>
<br>
TEST_CASE(&quot;pool_allocator.allocate_v1&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;size_t&nbsp;elem_size&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v1)&nbsp;+&nbsp;256;<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;uint8_t&nbsp;pool_buffer[elem_size&nbsp;*&nbsp;4];<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(pool_buffer,&nbsp;sizeof(pool_buffer),&nbsp;elem_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;crow::allocate_packet_header_v1(256);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(pack&nbsp;!=&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(pack-&gt;header_addr()&nbsp;!=&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(pack-&gt;addrptr()&nbsp;!=&nbsp;nullptr);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
}<br>
<br>
TEST_CASE(&quot;pool_allocator.allocate_v0&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;size_t&nbsp;elem_size&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v0)&nbsp;+&nbsp;256;<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;uint8_t&nbsp;pool_buffer[elem_size&nbsp;*&nbsp;4];<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(pool_buffer,&nbsp;sizeof(pool_buffer),&nbsp;elem_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;crow::allocate_packet_header_v0(256);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(pack&nbsp;!=&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;1);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(pack);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
}<br>
<br>
TEST_CASE(&quot;pool_allocator.allocate_with_sizes&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;size_t&nbsp;elem_size&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v1)&nbsp;+&nbsp;256;<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;uint8_t&nbsp;pool_buffer[elem_size&nbsp;*&nbsp;4];<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(pool_buffer,&nbsp;sizeof(pool_buffer),&nbsp;elem_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;crow::allocate_packet_header_v1(10,&nbsp;100);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(pack&nbsp;!=&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(pack-&gt;addrsize(),&nbsp;10);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(pack-&gt;datasize(),&nbsp;100);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(pack);<br>
}<br>
<br>
TEST_CASE(&quot;pool_allocator.exhaust_pool&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;size_t&nbsp;elem_size&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v1)&nbsp;+&nbsp;128;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;int&nbsp;num_packets&nbsp;=&nbsp;3;<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;uint8_t&nbsp;pool_buffer[elem_size&nbsp;*&nbsp;num_packets];<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(pool_buffer,&nbsp;sizeof(pool_buffer),&nbsp;elem_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*p1&nbsp;=&nbsp;crow::allocate_packet_header_v1(128);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*p2&nbsp;=&nbsp;crow::allocate_packet_header_v1(128);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*p3&nbsp;=&nbsp;crow::allocate_packet_header_v1(128);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(p1&nbsp;!=&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(p2&nbsp;!=&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(p3&nbsp;!=&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;3);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Pool&nbsp;exhausted<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*p4&nbsp;=&nbsp;crow::allocate_packet_header_v1(128);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(p4&nbsp;==&nbsp;nullptr);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Free&nbsp;one&nbsp;and&nbsp;try&nbsp;again<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(p1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;2);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*p5&nbsp;=&nbsp;crow::allocate_packet_header_v1(128);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(p5&nbsp;!=&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;3);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Cleanup<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(p2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(p3);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(p5);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
}<br>
<br>
TEST_CASE(&quot;pool_allocator.data_integrity&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;size_t&nbsp;elem_size&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v1)&nbsp;+&nbsp;256;<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;uint8_t&nbsp;pool_buffer[elem_size&nbsp;*&nbsp;2];<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(pool_buffer,&nbsp;sizeof(pool_buffer),&nbsp;elem_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;crow::allocate_packet_header_v1(16,&nbsp;64);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(pack&nbsp;!=&nbsp;nullptr);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Write&nbsp;to&nbsp;address&nbsp;field<br>
&nbsp;&nbsp;&nbsp;&nbsp;memset(pack-&gt;addrptr(),&nbsp;0xAA,&nbsp;16);<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Write&nbsp;to&nbsp;data&nbsp;field<br>
&nbsp;&nbsp;&nbsp;&nbsp;memset(pack-&gt;dataptr(),&nbsp;0xBB,&nbsp;64);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Verify<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;16;&nbsp;i++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(pack-&gt;addrptr()[i],&nbsp;0xAA);<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;64;&nbsp;i++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(pack-&gt;dataptr()[i],&nbsp;(char)0xBB);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(pack);<br>
}<br>
<br>
TEST_CASE(&quot;pool_allocator.packet_fields&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;size_t&nbsp;elem_size&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v1)&nbsp;+&nbsp;256;<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;uint8_t&nbsp;pool_buffer[elem_size&nbsp;*&nbsp;2];<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(pool_buffer,&nbsp;sizeof(pool_buffer),&nbsp;elem_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*pack&nbsp;=&nbsp;crow::allocate_packet_header_v1(8,&nbsp;32);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(pack&nbsp;!=&nbsp;nullptr);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Set&nbsp;packet&nbsp;fields<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_type(3);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_quality(1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_ackquant(504);&nbsp;&nbsp;//&nbsp;quantized&nbsp;to&nbsp;50*10+4=504<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_seqid(0x1234);<br>
&nbsp;&nbsp;&nbsp;&nbsp;pack-&gt;set_stage(2);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Verify&nbsp;fields<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(pack-&gt;type(),&nbsp;3);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(pack-&gt;quality(),&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(pack-&gt;ackquant(),&nbsp;504);&nbsp;&nbsp;//&nbsp;ackquant&nbsp;is&nbsp;quantized<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(pack-&gt;seqid(),&nbsp;0x1234);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(pack-&gt;stage(),&nbsp;2);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(pack);<br>
}<br>
<br>
TEST_CASE(&quot;pool_allocator.has_allocated&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;size_t&nbsp;elem_size&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v1)&nbsp;+&nbsp;128;<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;uint8_t&nbsp;pool_buffer[elem_size&nbsp;*&nbsp;2];<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(pool_buffer,&nbsp;sizeof(pool_buffer),&nbsp;elem_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_FALSE(crow::has_allocated());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*p1&nbsp;=&nbsp;crow::allocate_packet_header_v1(128);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(crow::has_allocated());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*p2&nbsp;=&nbsp;crow::allocate_packet_header_v1(128);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(crow::has_allocated());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(p1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(crow::has_allocated());&nbsp;//&nbsp;p2&nbsp;still&nbsp;allocated<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(p2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_FALSE(crow::has_allocated());<br>
}<br>
<br>
TEST_CASE(&quot;pool_allocator.multiple_pools&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Test&nbsp;reinitializing&nbsp;pool&nbsp;with&nbsp;different&nbsp;buffer<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;size_t&nbsp;elem_size1&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v1)&nbsp;+&nbsp;64;<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;uint8_t&nbsp;pool_buffer1[elem_size1&nbsp;*&nbsp;2];<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(pool_buffer1,&nbsp;sizeof(pool_buffer1),&nbsp;elem_size1);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::get_package_pool()-&gt;size(),&nbsp;2);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*p1&nbsp;=&nbsp;crow::allocate_packet_header_v1(64);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(p1&nbsp;!=&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(p1);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Reinitialize&nbsp;with&nbsp;larger&nbsp;pool<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;size_t&nbsp;elem_size2&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v1)&nbsp;+&nbsp;128;<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;uint8_t&nbsp;pool_buffer2[elem_size2&nbsp;*&nbsp;4];<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(pool_buffer2,&nbsp;sizeof(pool_buffer2),&nbsp;elem_size2);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::get_package_pool()-&gt;size(),&nbsp;4);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::packet&nbsp;*p2&nbsp;=&nbsp;crow::allocate_packet_header_v1(128);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(p2&nbsp;!=&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(p2);<br>
}<br>
<br>
TEST_CASE(&quot;pool_allocator.deallocate_nullptr&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;size_t&nbsp;elem_size&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sizeof(crow::packet)&nbsp;+&nbsp;sizeof(crow::header_v1)&nbsp;+&nbsp;64;<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;uint8_t&nbsp;pool_buffer[elem_size&nbsp;*&nbsp;2];<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::engage_packet_pool(pool_buffer,&nbsp;sizeof(pool_buffer),&nbsp;elem_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Should&nbsp;not&nbsp;crash<br>
&nbsp;&nbsp;&nbsp;&nbsp;crow::deallocate_packet(nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_EQ(crow::allocated_count(),&nbsp;0);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
