<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/brocker/crowker.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**&nbsp;@file&nbsp;*/<br>
<br>
#include&nbsp;&lt;crow/brocker/crowker.h&gt;<br>
#include&nbsp;&lt;crow/defs.h&gt;<br>
#include&nbsp;&lt;crow/hostaddr_view.h&gt;<br>
#include&nbsp;&lt;igris/util/dstring.h&gt;<br>
#include&nbsp;&lt;nos/fprint.h&gt;<br>
#include&nbsp;&lt;nos/inet/tcp_client.h&gt;<br>
#include&nbsp;&lt;utility&gt;<br>
<br>
void&nbsp;crow::crowker::publish(const&nbsp;std::string&nbsp;&amp;theme,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::shared_ptr&lt;std::string&gt;&nbsp;&amp;data)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*thm&nbsp;=&nbsp;get_theme(theme);<br>
&nbsp;&nbsp;&nbsp;&nbsp;thm-&gt;publish(data);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(brocker_info&nbsp;||&nbsp;log_publish)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;publish:&nbsp;t:{}&nbsp;s:{}&nbsp;d:{}&quot;,&nbsp;theme,&nbsp;thm-&gt;count_clients(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris::dstring(*data));<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
crowker_implementation::theme&nbsp;*crow::crowker::get_theme(const&nbsp;std::string&nbsp;&amp;name)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(themes.count(name))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&amp;themes.at(name);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;it&nbsp;=&nbsp;themes.emplace(std::make_pair(name,&nbsp;CROW_DEFAULT_QUEUE_SIZE));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*thm&nbsp;=&nbsp;&amp;((it.first)-&gt;second);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;thm-&gt;set_name(name);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;thm;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::crowker::subscribe(const&nbsp;std::string&nbsp;&amp;theme,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;client&nbsp;*cl,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crowker_implementation::options&nbsp;opt)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*thm&nbsp;=&nbsp;get_theme(theme);<br>
&nbsp;&nbsp;&nbsp;&nbsp;cl-&gt;set_theme_options(thm,&nbsp;opt);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;thm-&gt;set_activity_timestamp(crowker_eval_timestamp());<br>
&nbsp;&nbsp;&nbsp;&nbsp;cl-&gt;set_activity_timestamp(crowker_eval_timestamp());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;added&nbsp;=&nbsp;thm-&gt;link_client(cl);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(added&nbsp;&amp;&amp;&nbsp;brocker_info)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;new&nbsp;subscribe(crow):&nbsp;t:{}&quot;,&nbsp;theme);<br>
}<br>
<br>
void&nbsp;crow::crowker::crow_subscribe(const&nbsp;crow::hostaddr_view&nbsp;&amp;addr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;theme,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;ackquant)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;saddr{(char&nbsp;*)addr.data(),&nbsp;(size_t)addr.size()};<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*thm&nbsp;=&nbsp;get_theme(theme);<br>
&nbsp;&nbsp;&nbsp;&nbsp;thm-&gt;set_activity_timestamp(crowker_eval_timestamp());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*sub&nbsp;=&nbsp;crowker_implementation::crow_client::get(saddr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;sub-&gt;set_activity_timestamp(crowker_eval_timestamp());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;TODO:&nbsp;Перенести.&nbsp;Незачем&nbsp;перезаписывать&nbsp;адресс&nbsp;каждый&nbsp;раз.<br>
&nbsp;&nbsp;&nbsp;&nbsp;sub-&gt;addr&nbsp;=&nbsp;saddr;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!thm-&gt;has_client(sub))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;thm-&gt;link_client(sub);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sub-&gt;set_theme_options(thm,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crowker_implementation::options{qos,&nbsp;ackquant});<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(brocker_info)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;new&nbsp;subscribe(crow):&nbsp;a:{}&nbsp;q:{}&nbsp;c:{}&nbsp;t:{}&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris::dstring(addr.data(),&nbsp;addr.size()),&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ackquant,&nbsp;theme);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;opts&nbsp;=&nbsp;sub-&gt;get_theme_options(thm);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(opts.qos&nbsp;!=&nbsp;qos&nbsp;||&nbsp;opts.ackquant&nbsp;!=&nbsp;ackquant)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;opts.qos&nbsp;=&nbsp;qos;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;opts.ackquant&nbsp;=&nbsp;ackquant;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;change&nbsp;subscribe(crow):&nbsp;a:{}&nbsp;q:{}&nbsp;c:{}&nbsp;t:{}&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris::dstring(addr.data(),&nbsp;addr.size()),&nbsp;qos,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ackquant,&nbsp;theme);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::crowker::tcp_subscribe(const&nbsp;std::string&nbsp;&amp;theme,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::inet::tcp_client&nbsp;*sock)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*thm&nbsp;=&nbsp;get_theme(theme);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*sub&nbsp;=&nbsp;crowker_implementation::tcp_client::get(sock-&gt;getaddr());<br>
&nbsp;&nbsp;&nbsp;&nbsp;sub-&gt;sock&nbsp;=&nbsp;sock;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!thm-&gt;has_client(sub))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;thm-&gt;link_client(sub);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(brocker_info)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;subscribe(tcp):&nbsp;a:{}&quot;,&nbsp;sock-&gt;getaddr());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;crow::crowker::unlink_theme_client(crowker_implementation::theme&nbsp;*thm,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crowker_implementation::client&nbsp;*sub)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!thm-&gt;has_client(sub))<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;unlink_theme_client:&nbsp;client&nbsp;not&nbsp;found&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;thm-&gt;unlink_client(sub);<br>
&nbsp;&nbsp;&nbsp;&nbsp;sub-&gt;forgot_theme(thm);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;TODO:&nbsp;Сделать&nbsp;политику&nbsp;удаления&nbsp;клиентов&nbsp;и&nbsp;тем.<br>
&nbsp;&nbsp;&nbsp;&nbsp;/*if&nbsp;(thm-&gt;count_clients()&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;themes.erase(thm-&gt;name);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}*/<br>
}<br>
<br>
void&nbsp;crow::crowker::send_latest(const&nbsp;std::string&nbsp;&amp;theme,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;client&nbsp;*cl,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;count_of_latest)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*thm&nbsp;=&nbsp;get_theme(theme);<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;cl-&gt;set_theme_options(thm,&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;thm-&gt;set_activity_timestamp(crowker_eval_timestamp());<br>
&nbsp;&nbsp;&nbsp;&nbsp;cl-&gt;set_activity_timestamp(crowker_eval_timestamp());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(count_of_latest&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::shared_ptr&lt;std::string&gt;&gt;&nbsp;latest_messages&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;thm-&gt;get_latest(count_of_latest);<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;msg&nbsp;:&nbsp;latest_messages)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cl-&gt;publish(theme,&nbsp;*msg,&nbsp;cl-&gt;get_theme_options(thm));<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
