<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>crow/brocker/theme.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**&nbsp;@file&nbsp;*/<br>
<br>
#include&nbsp;&quot;theme.h&quot;<br>
#include&nbsp;&quot;client.h&quot;<br>
#include&nbsp;&quot;crowker.h&quot;<br>
#include&nbsp;&lt;chrono&gt;<br>
#include&nbsp;&lt;igris/dprint.h&gt;<br>
#include&nbsp;&lt;igris/math.h&gt;<br>
#include&nbsp;&lt;nos/log.h&gt;<br>
#include&nbsp;&lt;nos/print.h&gt;<br>
<br>
crowker_implementation::theme::theme(size_t&nbsp;queue_size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_last_messages.resize(queue_size);<br>
}<br>
<br>
int64_t&nbsp;crowker_eval_timestamp()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;now&nbsp;=&nbsp;std::chrono::system_clock::now();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;duration&nbsp;=&nbsp;now.time_since_epoch();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;millis&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::chrono::duration_cast&lt;std::chrono::milliseconds&gt;(duration).count();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;millis;<br>
}<br>
<br>
std::vector&lt;std::shared_ptr&lt;std::string&gt;&gt;<br>
crowker_implementation::theme::get_latest(uint32_t&nbsp;count)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::shared_ptr&lt;std::string&gt;&gt;&nbsp;arr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;size&nbsp;=&nbsp;__MIN__(count,&nbsp;_last_messages.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(size_t&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;size;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;arr.push_back(_last_messages[i]);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;arr;<br>
}<br>
<br>
void&nbsp;crowker_implementation::theme::publish(<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::shared_ptr&lt;std::string&gt;&nbsp;&amp;data)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;client&nbsp;*&gt;&nbsp;killme_list;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::lock_guard&lt;std::mutex&gt;&nbsp;lock(mtx);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_last_messages.push(data);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;*sub&nbsp;:&nbsp;_subs)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crowker_implementation::options&nbsp;opts&nbsp;=&nbsp;sub-&gt;get_theme_options(this);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(opts.qos&nbsp;==&nbsp;0&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crowker_eval_timestamp()&nbsp;-&nbsp;sub-&gt;activity_timestamp()&nbsp;&gt;&nbsp;20000)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;killme_list.push_back(sub);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sub-&gt;publish(name(),&nbsp;{data-&gt;data(),&nbsp;data-&gt;size()},&nbsp;opts);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;*sub&nbsp;:&nbsp;killme_list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;crow::crowker::instance()-&gt;unlink_theme_client(this,&nbsp;sub);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;_publish_timestamp&nbsp;=&nbsp;_activity_timestamp&nbsp;=&nbsp;crowker_eval_timestamp();<br>
}<br>
<br>
void&nbsp;crowker_implementation::theme::unlink_client(client&nbsp;*sub)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(_subs.count(sub)&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::log::warn(&quot;try&nbsp;unlink&nbsp;unregistred&nbsp;client:{}&nbsp;theme:{}&quot;,&nbsp;sub-&gt;name(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::fprintln(&quot;unlink&nbsp;client:{}&nbsp;theme:{}&quot;,&nbsp;sub-&gt;name(),&nbsp;name());<br>
&nbsp;&nbsp;&nbsp;&nbsp;_subs.erase(sub);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
