name: Licant

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: 
          - { CXX: g++-11, CC: gcc-11 } 
          - { CXX: clang++-12, CC: clang-12 }
          
    steps:
    - uses: actions/checkout@master
      with:
          repository: mirmik/igris

    - uses: actions/checkout@v2

    - name: Setup dependencies
      run: |
        sudo apt-get install -y g++-11 clang-12
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/${{matrix.compiler.CXX}} 100
        sudo update-alternatives --install /usr/bin/cc  cc  /usr/bin/${{matrix.compiler.CC}} 100
        sudo python3 -m pip install licant

    - name: Install igris library
      run: |
        git clone https://github.com/mirmik/igris
        cd igris
        ./make.py
        sudo ./make.py install
        cd ..

    - name: Install nos library
      run: |
        git clone https://github.com/mirmik/nos
        cd nos
        ./make.py
        sudo ./make.py install
        cd ..

    - name: Build
      run: python3 ./make.py

    - name: Test
      run: ./runtests
      
